apache/incubator-pegasus

- src/server/pegasus_server_impl.cpp
[relevant rdsn pr](https://github.com/XiaoMi/rdsn/pull/11)
> pegasus_server_impl: some update according to rdsn's changes

- src/server/pegasus_write_service_impl.h
refer to https://github.com/XiaoMi/rdsn/pull/138
> update rdsn for bugfix: fix buf2signed/buf2unsigned/buf2double bug

- docker/dev/centos7/Dockerfile
> docker: add dockerfile for onebox

- src/shell/main.cpp
refer to https://github.com/XiaoMi/pegasus/issues/149
> shell: get cluster name when start shell

- src/server/pegasus_scan_context.h
- src/test/bench_test/config.ini
> scan: decrease the probility of context id conflict, and add more comments

- run.sh
1. should add "-CMAKE_BUILD_TYPE=debug" to "CMAKE_OPTIONS" too.
2. when there is an existing makefile, we shoudn't run cmake again. otherwise the build process may fail.
> build: fix rocksdb build

- src/base/pegasus_value_schema.h
- src/server/key_ttl_compaction_filter.h
> server: support default TTL for a table

- run.sh
- scripts/pegasus_offline_node.sh
- scripts/pegasus_rolling_update.sh
- src/shell/command_helper.h
- src/shell/commands.h
- src/shell/main.cpp
> shell: support get count of different hash keys in command count_data

- scripts/falcon_screen.json
- src/server/info_collector.cpp
- src/shell/commands.h
* add hit rate metric to falcon
* fix hit rate report bug
> monitor: add hit rate metric to falcon

- src/server/pegasus_server_impl.cpp
- src/server/pegasus_server_impl.h
> pegasus-server: fix manual compact coredump bug

- scripts/falcon_screen.json
include:
* add load balance screen
* add manual compact screen
* re-order the screens
> scripts: improve falcon screen

- scripts/clusters_show.sh
- scripts/pack_server.sh
- scripts/pack_tools.sh
The result of `clusters_show.sh` is like:
```
show_time = Tue Mar 12 11:24:17 CST 2019
Columns:
- cluster: name of the cluster
- rs_count: current count of replica servers
- version: current version of replica servers
- lb_op_count: current count of load balance operations to make cluster balanced
- app_count: current count of tables in the cluster
- storage_gb: current total data size in GB of tables in the cluster
cluster                       rs_count    version     lb_op_count app_count   storage_gb  
alsgsrv-account               5           1.11.3      0           3           17          
alsgsrv-ad                    5           1.11.3      0           4           70          
alsgsrv-ai                    5           1.11.3      0           4           2           
```
> scripts: add clusters_show.sh; fix pack scripts; update rdsn

- src/server/config-server.ini
- src/server/config.ini
add server config for connection threshold per endpoint
> *: add server config for connection threshold per endpoint

- scripts/falcon_screen.json
refer to https://github.com/XiaoMi/pegasus/issues/330 and https://github.com/XiaoMi/rdsn/pull/236
> scripts: add P999 latency falcon screens

- .gitignore
- run.sh
- scripts/create_table.py
According to the discussion in https://github.com/XiaoMi/pegasus/issues/311, enable
RelWithDebInfo will help for debugging.
Tests 
- No code
Side effects
> scripts: build rocksdb with RelWithDebInfo

- src/server/config-server.ini
- src/server/config.ini
- src/server/test/config.ini
update rdsn to https://github.com/XiaoMi/rdsn/commit/e9006a3c2071656f9baae3fcad18fad04133de16
add items in `src/config.ini` and `src/config-server.ini`:
- [core] tls_trans_memory_KB 
- [core] tcmalloc_release_rate (https://github.com/XiaoMi/rdsn/pull/278)
- [replication] mem_release_enabled & mem_release_interval_ms (https://github.com/XiaoMi/rdsn/pull/278)
remove items in `src/config-server.ini`:
- [core] cli_local & cli_remote (https://github.com/XiaoMi/rdsn/pull/156)
- [core] start_nfs (https://github.com/XiaoMi/rdsn/pull/142)
remove items is `src/server/test/config.ini`:
- [replication.app] package_id (https://github.com/XiaoMi/rdsn/pull/276)
> update rdsn & fix config

- .gitignore
- .travis.yml
- scripts/format_files.sh
- scripts/travis.sh
- src/base/test/CMakeLists.txt
- src/base/test/run.sh
- src/geo/bench/bench.cpp
- src/redis_protocol/proxy_ut/redis_proxy_test.cpp
- src/server/test/pegasus_compression_options_test.cpp
- src/shell/commands/data_operations.cpp
- src/test/bench_test/pegasus_bench.cpp
- src/test/function_test/test_recovery.cpp
Automatically run formatter for each commit.
> scripts: travis supports format

- scripts/clusters_show.sh
- scripts/clusters_stat.sh
- scripts/pegasus_stat_available.sh
fix clusters_stat.sh to check `app_stat` result correctly, because for the latest version, `app_stat` will not print succeed hint at the end.
clusters_stat.sh and related scripts.
Tests 
- Manual test
> scripts: fix clusters_stat.sh and related scripts

- src/server/CMakeLists.txt
fix cmake file; update rdsn
- Unit test
- Manual test
> fix cmake file; update rdsn

- .travis.yml
fix .travis.yml to provide correct dowload url for pegasus-common
- Unit test
> build: fix travis

- src/server/config.ini
Change default config for memory-release, to avoid major performance downgrade.
> fix(config): disable auto mem release by default

- src/server/config.ini
rdsn pr [343](https://github.com/XiaoMi/rdsn/pull/343) optimize tcmalloc release memory, this pr update rdsn and config.
Add two new config
```
mem_release_check_interval_ms = 3600000;
mem_release_max_reserved_mem_percentage = 10;
```
Remove config `mem_release_interval_ms`
> feat: update config for tcmalloc release memory optimization

- src/include/pegasus/version.h
This is what we regularly do during releasing a major/minor version. This commit is a little bit late.
> chore: upgrade dev version to 1.13.SNAPSHOT

- run.sh
- src/server/pegasus_manual_compact_service.cpp
- src/server/pegasus_server_impl.cpp
- src/server/pegasus_server_impl.h
- src/server/pegasus_write_service_impl.h
- src/server/test/manual_compact_service_test.cpp
- src/server/test/pegasus_compression_options_test.cpp
Only refactor
And also it's part of the work to use original rocksdb
no changes
> refactor: refactor rocksdb options usage

- src/server/available_detector.cpp
- src/server/pegasus_manual_compact_service.cpp
- src/server/test/manual_compact_service_test.cpp
- src/shell/command_helper.h
Minor fixes to adapt to https://github.com/XiaoMi/rdsn/pull/388.
Adds <dsn/utility/time_utils.h> to fix missing header problem.
> fix(rdsn): update rdsn and adapt to time_utils refactoring

- src/server/pegasus_server_impl.cpp
Simple refactor on code style, no logic changes.
> refactor: simplify logging in pegasus_server_impl

- src/server/capacity_unit_calculator.cpp
- src/server/capacity_unit_calculator.h
- src/server/config.min.ini
- src/server/info_collector.cpp
- src/server/info_collector.h
- src/server/pegasus_server_impl.cpp
- src/server/pegasus_write_service.cpp
- src/server/table_stats.h
- src/server/test/capacity_unit_calculator_test.cpp
- src/shell/command_helper.h
Add throughput statistic for table.
Tests 
- Manual test
> feat(collector): add throughput statistic for table

- docs/installation.md
Fix build problem on CentOS.
Add `zlib-devel` to list of dependencies.
> docs: update CentOS build dependencies

- src/server/info_collector.cpp
fix incorrect log message in info_collector::on_app_stat
> fix: fix incorrect log message in info_collector::on_app_stat

- src/shell/commands.h
- src/shell/commands/bulk_load.cpp
- src/shell/main.cpp
This pull request adds and implements bulk load shell command, including: start/pause/restart/cancel bulk load.
This pull request also adds query bulk load, but not implement it in this pull request.
Tests 
- Manual test
> feat(bulk-load): add bulk load shell command

- src/base/CMakeLists.txt
- src/server/info_collector_app.h
- src/test/bench_test/CMakeLists.txt
- src/test/function_test/CMakeLists.txt
- src/test/kill_test/CMakeLists.txt
- src/test/pressure_test/CMakeLists.txt
- src/test/upgrade_test/CMakeLists.txt
add library dependencies to fix compiler error
> fix: add library dependencies to fix compiler error

- rfcs/2020-08-27-metric-api.md
This is a proposal for the new metric API. Please review the doc in rfcs/2020-08-27-metric-api.md.
Tests 
- No code
> docs: add rfc for new metric api

- README.md
Tests 
- Unit test
- No code
Code changes
Side effects
> refactor: update license statement

- src/server/hotspot_partition_calculator.cpp
`std::make_unique` will produce compile error , so fix it in this pr
> fix(hotspot): using dsn::make_unique instead of std::make_unique

- .github/ISSUE_TEMPLATE/general_question.md
- README.md
> docs: use the apache domain for website link

- src/base/rrdb_types.cpp
- src/idl/rrdb.thrift
- src/include/rrdb/rrdb_types.h
- src/server/hotspot_partition_calculator.cpp
- src/server/hotspot_partition_calculator.h
- src/server/pegasus_read_service.h
- src/server/test/config.ini
- src/server/test/hotspot_partition_test.cpp
name change:
`hotkey_detect -> detect_hotkey`
> refactor(hotspot): remove hotkey_detect_request in rrdb.thrift

- src/server/test/capacity_unit_calculator_test.cpp
Determine the type of incoming key(raw_key/hash_key) according to the situation
> fix: fix unit test of capacity_unit_calculator

- scripts/pack_server.sh
add thirdparty lib when pack server
Tests 
- No code
> feat(security): add thirdparty lib when pack server

- .github/workflows/ci-pull-request.yaml
- src/server/info_collector.h
- src/server/table_stats.h
Previous yaml will check code format for master repo, and #705 is not formated. This pull request fix those problems.
> fix: do not get master while raise a new pull request

- .github/pull_request_template.md
- README.md
Minor grammar fixes, add some additional Markdown formatting to the PR template
Just some changes to the Markdown files.
N/A
> doc: Grammar fixes

- README.md
> doc: update README.md: fix a typo

- README.md
Fix pegasus logo missing error
> fix: fix logo missing

- rfcs/2021-05-27-user-specified-compaction.md
add rfc about user specified compaction
- No code
> doc: add rfc about user specified compaction

- src/server/compaction_filter_rule.cpp
- src/server/compaction_filter_rule.h
- src/server/test/compaction_filter_rule_test.cpp
> feat: add sortkey pattern rule

- src/server/compaction_filter_rule.cpp
- src/server/compaction_filter_rule.h
- src/server/test/compaction_filter_rule_test.cpp
> feat: add ttl range rule

- scripts/pack_tools.sh
add thirdparty lib when pack tools
Tests 
- No code
> fix: add lib while pack tools

- scripts/pegasus_rolling_update.sh
update usage hint for rolling update script
Tests 
- No code
> feat: update usage hint for rolling update script

- .github/workflows/ci-pull-request-markdown-links.yaml
- .github/workflows/ci-pull-request.yaml
Support to check markdown links, ref: https://github.com/gaurav-nelson/github-action-markdown-link-check
> chore: support markdown link check action

- src/server/compaction_filter_rule.cpp
- src/server/compaction_filter_rule.h
- src/server/main.cpp
- src/server/test/compaction_filter_rule_test.cpp
- src/server/test/main.cpp
> feat: add compaction filter rule creator

- src/server/compaction_filter_rule.cpp
- src/server/compaction_filter_rule.h
- src/server/compaction_operation.cpp
- src/server/compaction_operation.h
- src/server/main.cpp
- src/server/test/compaction_operation_test.cpp
- src/server/test/main.cpp
> feat: add creator for compaction operation

- src/server/config.ini
As #786 shows, this pr update related configuration.
> feat: update client rpc config

- src/server/config.ini
This pr update some configuration in `config.ini` file.
- No code
> feat: update configuration file

- .admin-cli-history
- src/base/pegasus_const.cpp
- src/base/pegasus_const.h
- src/server/capacity_unit_calculator.cpp
- src/server/capacity_unit_calculator.h
- src/server/pegasus_server_impl.cpp
- src/server/pegasus_server_impl.h
- src/server/pegasus_server_impl_init.cpp
- src/server/test/capacity_unit_calculator_test.cpp
Ref: https://github.com/apache/incubator-pegasus/issues/830
> feat: support read throttling by size

- scripts/pegasus_add_node_list.sh
- scripts/pegasus_offline_node_list.sh
- scripts/pegasus_rebalance_cluster.sh
https://github.com/XiaoMi/rdsn/pull/944 support disk rate limiter, this pr update the remote-command args name
-  deploy the test cluster
- test the `add_node_list` and `offline_node_list` script
**Note: It will cause the compatibility problem**
> refactor(script): update the nfs rate name of remote-command

- src/server/config.ini
This pull request updates RPC_RRDB_RRDB_BULK_LOAD config.
> feat(bulk_load): update ingestion config

- src/server/hotkey_collector.cpp
- src/server/test/hotkey_collector_test.cpp
- src/test/function_test/test_split.cpp
fix two ut test;
(1)hotkey_collector_test.cpp 
if all the 'coarse_collector.capture_data' async logic not run, but "coarse_collector.analyse_data(result)" executed will cause unit test fail; this phenomenon has appeared many times in my laptop computer and build machine in my company;
(2)test_split.cpp
variable 'count' should be initialized, if not will cause unit test fail randomly 
Unit test
only unit test related code change
only have impact on unit test
no relate changes
> fix: hotkey_collector bug and two function tests

- src/reporter/pegasus_counter_reporter.cpp
- src/server/available_detector.cpp
- src/server/info_collector.cpp
- src/server/pegasus_write_service.h
- src/server/pegasus_write_service_impl.h
Fix compile error produced by dist/common.h
Related pull request: https://github.com/XiaoMi/rdsn/pull/992
- No code
> fix: fix compile error produced by dist/common.h

- src/shell/commands/bulk_load.cpp
Adapt to modification in meta server. In Pegasus Shell command: "query_bulk_load_status", show the restult of bulk load.
> feat(bulk_load): adapt to modification in meta server

- src/server/rocksdb_wrapper.cpp
https://github.com/apache/incubator-pegasus/issues/851
> feat(online_migration): update log to print ingest_behind option

- src/server/pegasus_write_service_impl.h
> feat(bulk_load): support verify_before_ingest option

- src/base/pegasus_key_schema.h
- src/base/pegasus_value_schema.h
- src/base/test/CMakeLists.txt
- src/client_lib/CMakeLists.txt
- src/geo/bench/CMakeLists.txt
- src/geo/test/CMakeLists.txt
- src/redis_protocol/proxy/CMakeLists.txt
- src/redis_protocol/proxy_ut/CMakeLists.txt
- src/server/available_detector.cpp
- src/server/hashkey_transform.h
- src/server/pegasus_server_impl.cpp
- src/shell/commands/data_operations.cpp
- src/shell/commands/debugger.cpp
- src/test/bench_test/CMakeLists.txt
- src/test/bench_test/rand.cpp
- src/test/kill_test/CMakeLists.txt
- src/test/pressure_test/CMakeLists.txt
- src/test/upgrade_test/CMakeLists.txt
ref issue: https://github.com/apache/incubator-pegasus/issues/813
> feat(build): support to build on MacOS

- src/client_lib/CMakeLists.txt
ref: https://github.com/apache/incubator-pegasus/issues/900
> fix(build): Fix '__FILENAME__ was not declared' bug

- src/server/pegasus_server_impl.cpp
- src/server/pegasus_server_impl.h
https://github.com/apache/incubator-pegasus/issues/906
> fix: shutdown error while closing replica

- scripts/pack_server.sh
- scripts/pack_tools.sh
https://github.com/apache/incubator-pegasus/issues/910
> fix(script): change the library version of poco

- src/CMakeLists.txt
Related issue:
https://github.com/apache/incubator-pegasus/issues/898
related PR:
https://github.com/apache/incubator-pegasus-website/pull/14
> fix(build): update GCC and CMake checker

- src/redis_protocol/proxy_lib/redis_parser.cpp
- src/test/bench_test/benchmark.cpp
> refactor: use the correct cast operation

- .github/workflows/ci-pull-request.yaml
- src/server/pegasus_server_impl.cpp
- src/server/test/CMakeLists.txt
- src/server/test/pegasus_server_impl_test.cpp
- src/server/test/pegasus_server_test_base.h
- src/server/test/rocksdb_wrapper_test.cpp
- src/shell/commands/duplication.cpp
follower load duplication data if it's a replica follower
> feat(dup_enhancement#17):  replica follower load duplication data when open replica

- src/shell/commands/duplication.cpp
- src/shell/main.cpp
> refactor(dup_enhancement#24): delete useless `freezed` argument

- .asf.yaml
https://github.com/apache/incubator-pegasus/issues/903
https://issues.apache.org/jira/browse/INFRA-23054
> fix: asf file is invalid for the name is not right 

- .github/workflows/ci-pull-request.yaml
- src/base/rrdb_types.cpp
- src/idl/rrdb.thrift
- src/include/rrdb/rrdb_types.h
- src/server/pegasus_mutation_duplicator.cpp
- src/server/pegasus_mutation_duplicator.h
- src/server/pegasus_server_impl.cpp
- src/server/pegasus_write_service.cpp
- src/server/test/CMakeLists.txt
- src/server/test/pegasus_mutation_duplicator_test.cpp
- src/server/test/pegasus_server_impl_test.cpp
- src/server/test/pegasus_server_test_base.h
- src/server/test/pegasus_write_service_test.cpp
- src/server/test/rocksdb_wrapper_test.cpp
- src/shell/commands/duplication.cpp
- src/shell/main.cpp
> feat(dup_enhancement): support using nfs to duplicate checkpoint replace fds and support batch send plog

- src/shell/commands/duplication.cpp
- src/shell/main.cpp
> feat(dup_enhancement#25): add `-s | --sst` argument to support ignoring checkpoint when duplicate

- .github/workflows/ci-pull-request.yaml
- rfcs/2020-08-27-metric-api.md
- scripts/clear_zk.sh
- scripts/config_hdfs.sh
- scripts/pack_server.sh
- scripts/pack_tools.sh
- scripts/start_zk.sh
- scripts/stop_zk.sh
- src/server/CMakeLists.txt
- src/server/test/CMakeLists.txt
issue: https://github.com/apache/incubator-pegasus/issues/847
> feat: zookeeper client support kerberos

- .github/workflows/build-push-env-docker.yml
- .github/workflows/ci-pull-request.yaml
- .github/workflows/pegasus-regular-build.yml
- .github/workflows/thirdparty-regular-push.yml
- docker/README.md
- docker/ci-env/Dockerfile
- docker/pegasus-docker-compose/image_for_prebuilt_bin/Dockerfile
- docker/thirdparties-bin/Dockerfile
- docker/thirdparties-src/Dockerfile
ref: https://github.com/apache/incubator-pegasus/issues/948
DockerHub created by JIRA: https://issues.apache.org/jira/browse/INFRA-23150
> chore: Use official apache/pegasus repo on DockerHub

- python-client/pypegasus/pgclient.py
https://github.com/apache/incubator-pegasus/issues/945
cherry-pick https://github.com/XiaoMi/pegasus-python-client/pull/35
> fix(python-cient): python3 pass str value but not bytes

- admin-cli/cmd/create_table.go
https://github.com/apache/incubator-pegasus/issues/986
> fix(admin-cli): fix admin-cli usage doc

- java-client/pom.xml
https://github.com/apache/incubator-pegasus/issues/992
- Unit test
- No code
> build(java-cli): Remove redundant dependencies in java-client

- admin-cli/client/meta.go
- admin-cli/cmd/duplication.go
- admin-cli/executor/duplication.go
- admin-cli/go.mod
- admin-cli/go.sum
> feat(dup_enhancement#27): update dulication command in admin-cli

- .asf.yaml
Set more configs in .asf.yml
ref: https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features
https://github.com/apache/incubator-pegasus/issues/1029
> chore(github): set more configs in .asf.yaml

- .asf.yaml
Does need signatures.
ref: https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features
> chore(github): set required_signatures to false

- .licenserc.yaml
- src/rdsn/src/block_service/directio_writable_file.cpp
- src/rdsn/src/meta/CMakeLists.txt
- src/rdsn/src/utils/test/nth_element_bench/nth_element_bench.cpp
- thirdparty/CMakeLists.txt
- thirdparty/fix_libevent_for_macos.patch
https://github.com/apache/incubator-pegasus/issues/1052
I found Pegasus build failed on MacOS, I'll try to fix them before 2.4.0 released.
NOTE: Only build successfully on MacOS 12.4 with Intel CPU, and not run test yet.
> fix(build): fix build failure on MacOS

- src/rdsn/src/common/replication_common.h
- src/rdsn/src/meta/server_state.cpp
- src/rdsn/src/meta/server_state.h
- src/rdsn/src/replica/replica_stub.h
- src/test/function_test/test_recovery.cpp
As https://github.com/apache/incubator-pegasus/issues/1064 shows, this pr:
- fix recorery verification bug
- refactor meta recovery code by using rpc_holder structure
- update recovery function test to avoid unnecessary failure
> fix: fix recovery verification bug

- .github/workflows/labeler.yml
- .github/workflows/module_labeler_conf.yml
it would be more convenient for developers to see what module pull request changes.
https://github.com/apache/incubator-pegasus/issues/1075
> chore(action): Add actions/labeler to label modules automatically

- src/rdsn/src/meta/server_state.cpp
https://github.com/apache/incubator-pegasus/issues/1072
> fix: fix recovery code clang failed

- .github/workflows/lint_and_test_cpp.yaml
- cmake_modules/BaseFunctions.cmake
- run.sh
- thirdparty/CMakeLists.txt
https://github.com/apache/incubator-pegasus/issues/1052
https://github.com/apache/incubator-pegasus/issues/1059
Now support to build Pegasus on macOS.
**NOTE**: test and pack are not supportted now.
> chore(github): Add workflow of building Pegasus on macOS

- java-client/pom.xml
- java-client/src/main/java/org/apache/pegasus/client/ClientOptions.java
- java-client/src/main/java/org/apache/pegasus/rpc/interceptor/ReplicaSessionInterceptorManager.java
- java-client/src/main/java/org/apache/pegasus/security/AuthProtocol.java
- java-client/src/main/java/org/apache/pegasus/security/KerberosProtocol.java
> refactor(java-client): remove duplicate variable

- NOTICE
https://github.com/apache/incubator-pegasus/issues/1118
> chore: update NOTICE year to 2022

- .licenserc.yaml
- LICENSE
https://github.com/apache/incubator-pegasus/issues/1120
> chore: update file paths in LICENSE

- .github/workflows/lint_and_test_cpp.yaml
- .github/workflows/thirdparty-regular-push.yml
- docker/thirdparties-bin/Dockerfile
This PR is to solve https://github.com/apache/incubator-pegasus/issues/1135.
> fix(actions): build unit tests with portable rocksdb

- java-client/src/main/java/org/apache/pegasus/client/PegasusAdminClientInterface.java
- java-client/src/main/java/org/apache/pegasus/client/PegasusClientInterface.java
- java-client/src/main/java/org/apache/pegasus/client/PegasusScannerInterface.java
fix https://github.com/apache/incubator-pegasus/issues/1153
- make  PegasusAdminClientInterface / PegasusClientInterface / PegasusClientInterface closable
- fix pom
> feat: make java client interface closable

- .github/workflows/labeler.yml
https://github.com/apache/incubator-pegasus/issues/1181
> fix: fix workflow labeler not work

- nodejs-client/README.md
Added javascript syntax highlighting to your code snippets
https://github.com/apache/incubator-pegasus/issues/1166
Adds syntax highlighting to code snippets
Uses markdown syntax to highlight JS code snippets
- Unit test
- No code
> docs: Update nodejs-client/README.md

- .github/workflows/lint_and_test_cpp.yaml
https://github.com/apache/incubator-pegasus/issues/1162
> chore(CI): disable some flaky tests

- src/rdsn/src/utils/casts.h
This PR is to fix https://github.com/apache/incubator-pegasus/issues/1193.
> fix: fix wrong comments for down_cast

- src/rdsn/src/utils/metrics.cpp
- src/rdsn/src/utils/metrics.h
This PR is to solve https://github.com/apache/incubator-pegasus/issues/1191.
> refactor(metrics): drop template specialization for gauge

- run.sh
This PR is to fix https://github.com/apache/incubator-pegasus/issues/1209.
> fix(script): move zookeeper-bin under INSTALL_DIR rather than being it

- src/utils/metrics.h
- src/utils/test/metrics_test.cpp
This PR is solve https://github.com/apache/incubator-pegasus/issues/1218.
> feat(new_metrics): take snapshot of each metric as json format

- src/rdsn/src/replica/mutation_log.cpp
This PR is to cherry-pick https://github.com/apache/incubator-pegasus/pull/1208 into [v2.4](https://github.com/apache/incubator-pegasus/tree/v2.4) to solve issue https://github.com/apache/incubator-pegasus/issues/1207.
> fix: fix rollback by mistake for mutation_log::reset_from

- src/meta/test/balancer_simulator/balancer_simulator.cpp
- src/meta/test/balancer_validator.cpp
- src/meta/test/misc/misc.cpp
- src/runtime/rpc/network.cpp
- src/runtime/rpc/rpc_engine.cpp
- src/runtime/rpc/rpc_message.cpp
- src/runtime/rpc/rpc_stream.h
- src/runtime/rpc/rpc_task.cpp
- src/runtime/task/task_queue.cpp
- src/utils/fmt_logging.h
https://github.com/apache/incubator-pegasus/issues/1204
- `dbg_dassert` -> `DCHECK*`
- add debug type of `DCHECK*` for `CHECK*`
- remove self defined `ASSERT_*` from .cpp files
> refactor(macro): use DCHECK* to replace dbg_dassert and self defined ASSERT_*

- src/common/common.cpp
- src/redis_protocol/proxy_lib/redis_parser.cpp
- src/runtime/rpc/network.cpp
- src/runtime/security/kinit_context.cpp
- src/runtime/security/meta_access_controller.cpp
- src/utils/strings.h
- src/utils/test/utils.cpp
This PR is to implement https://github.com/apache/incubator-pegasus/issues/1227.
> feat: improve checking if C string is empty

- java-client/pom.xml
https://github.com/apache/incubator-pegasus/issues/1267
> refactor: Use spotless plugin to format pom file

- java-client/pom.xml
https://github.com/apache/incubator-pegasus/issues/1257
Also generate source jar when shading.
> build: Bump netty's version and shade it

- .gitignore
- java-client/pom.xml
https://github.com/apache/incubator-pegasus/issues/1275
> build: Use maven flatten plugin to generate resolved pom

- admin-cli/executor/partition_split.go
As https://github.com/apache/incubator-pegasus/issues/1288
> fix: fix judgment to disk for partition split

- src/http/test/http_server_test.cpp
- src/utils/CMakeLists.txt
- src/utils/metrics.cpp
- src/utils/metrics.h
- src/utils/test/CMakeLists.txt
- src/utils/test/metrics_test.cpp
This PR is to resolve https://github.com/apache/incubator-pegasus/issues/1280.
> feat(new_metrics): provide http service to process client query for metrics

- .github/workflows/test_python-client.yml
- python-client/test.sh
- python-client/tests/test_basics.py
https://github.com/apache/incubator-pegasus/issues/1313
> chore(CI): Add unit test workflow for python client

- thirdparty/CMakeLists.txt
issue: https://github.com/apache/incubator-pegasus/issues/1339
> fix: fix rocksdb build type

- src/replica/replica_base.cpp
- src/replica/replica_base.h
This PR is to resolve https://github.com/apache/incubator-pegasus/issues/1344.
> feat(new_metrics): add replica-level metric entity

- .asf.yaml
https://github.com/apache/incubator-pegasus/issues/1408
> chore(github): try to add some contributors into apache collaborators to allow them to use github actions

- docker/pegasus-build-env/centos6/Dockerfile
- src/geo/lib/geo_client.cpp
- src/redis_protocol/proxy_lib/redis_parser.cpp
- src/utils/errors.h
- src/utils/fmt_logging.h
add some macro definitions & fix a little docker build problem
issue: https://github.com/apache/incubator-pegasus/issues/1426
> feat: add new macro definitions & make the dockerfile compliant

- java-client/dev-support/findbugs-exclude.xml
- java-client/pom.xml
fix #1144 `mvn validate` will fail with generated code
uncomment maven spotbug plugin
- Unit test
- No code
> fix(java-client): Fix java spotbug

- src/runtime/rpc/rpc_host_port.cpp
- src/runtime/rpc/rpc_host_port.h
https://github.com/apache/incubator-pegasus/issues/1349
fix IWYU in `rpc_host_port.h` `rpc_host_port.cpp`
> fix(IWYU): fix include errors for rpc_host_port reported by IWYU

- go-client/pegasus/table_connector.go
fix #1446 
- Unit test
- No code
> doc(go-client): add deprecated marker to TableConnector.Close()

- src/runtime/rpc/group_host_port.h
- src/runtime/rpc/rpc_host_port.cpp
- src/runtime/rpc/rpc_host_port.h
- src/runtime/test/host_port_test.cpp
issue: https://github.com/apache/incubator-pegasus/issues/1404
Implement of struct `group_host_port` used by 'rpc_host_port'.
Also add some code on class `rpc_host_port` whose be related to `group_host_port`
used.
> feat(FQDN): Implement of struct host_port_group

- scripts/start_zk.sh
issue: https://github.com/apache/incubator-pegasus/issues/1513
change install zookeeper client way on `start_onebox`.
thirdparty -> $PEGASUSU_ROOT/.zk_install
> fix: fix install zookeeper client

- thirdparty/CMakeLists.txt
issue: https://github.com/apache/incubator-pegasus/issues/1515
update url to speed up the download
> chore: update rocksdb install url on thirdparty

- src/block_service/hdfs/hdfs_service.cpp
- src/common/fs_manager.cpp
- src/common/fs_manager.h
- src/replica/replica_stub.cpp
- src/replica/test/replica_test.cpp
https://github.com/apache/incubator-pegasus/issues/1541
> fix(new_metrics): total_capacity_mb and total_available_mb are not atomic

- src/common/serialization_helper/thrift_helper.h
- src/utils/test/metrics_test.cpp
fix `Lint and build regularly`
issue: https://github.com/apache/incubator-pegasus/issues/1554
> fix: fix build failure on older Ubuntu&GCC versions

- src/meta/distributed_lock_service_simple.h
- src/meta/dump_file.h
- src/meta/meta_state_service_simple.cpp
- src/meta/meta_state_service_simple.h
- src/meta/test/meta_state/meta_state_service.cpp
There is no functional changes, but only refactor the meta_state_service_simple and
related unit test.
> refactor(simple_meta_state): use rocksdb API to read/write file

- src/nfs/test/main.cpp
There is no functional changes, but only refactor the nfs unit test.
> refactor(nfs_test): make the tests more accurate and extendable

- src/replica/CMakeLists.txt
- src/replica/replica_restore.cpp
- src/replica/replication_app_base.cpp
- src/replica/replication_app_base.h
There is no functional changes, but only refactor the replica metadata
files read/write module.
> refactor(replica): use rocksdb API to read/write file

- src/block_service/test/CMakeLists.txt
- src/block_service/test/block_service_manager_test.cpp
- src/replica/bulk_load/test/CMakeLists.txt
- src/replica/bulk_load/test/replica_bulk_loader_test.cpp
- src/replica/duplication/test/load_from_private_log_test.cpp
- src/replica/test/CMakeLists.txt
- src/replica/test/mutation_log_test.cpp
- src/test/function_test/bulk_load/CMakeLists.txt
- src/test_util/CMakeLists.txt
- src/test_util/test_util.cpp
- src/test_util/test_util.h
- src/utils/test/CMakeLists.txt
- src/utils/test/env.cpp
There is no functional changes, but only refactor the files read/write method
of some unit tests.
> refactor(misc): use rocksdb API to read/write file

- src/test_util/CMakeLists.txt
- src/utils/configuration.cpp
There is no functional changes, but only refactor the files read/write method
of configuration module.
> refactor(configuration): use rocksdb API to read/write file

- src/utils/je_ctl.cpp
- src/utils/test/je_ctl_test.cpp
https://github.com/apache/incubator-pegasus/issues/1635
- Enlarge the buffer size to dump jemalloc stats
- Improve the jemalloc unit tests
> fix(jemalloc): enlarge the buffer size to dump jemalloc stats

- admin-cli/Makefile
- admin-cli/cmd/remote_command.go
- admin-cli/executor/server_config.go
- admin-cli/tabular/printer.go
- admin-cli/util/pegasus_node.go
- pegic/Makefile
Add fmt in Makefile for admin-cli and pegic, and format the golang files.
> chore(admin-cli&pegic): Add make fmt and fotmat files

- src/common/json_helper.h
- src/runtime/rpc/rpc_host_port.cpp
- src/runtime/rpc/rpc_host_port.h
- src/runtime/test/host_port_test.cpp
- src/utils/string_conv.h
- src/utils/test/json_helper_test.cpp
Issue: https://github.com/apache/incubator-pegasus/issues/1810
Implement json_decode & json_encode for class `rpc_host_port`.
> feat(fqdn): json decode & encode for rpc_host_port

- .github/actions/download_artifact/action.yaml
- .github/actions/rebuild_thirdparty_if_needed/action.yaml
- .github/actions/unpack_prebuilt_thirdparties/action.yaml
- .github/workflows/lint_and_test_cpp.yaml
- .github/workflows/lint_and_test_java-client.yml
- .github/workflows/regular-build.yml
- Make the "Unpack prebuilt third-parties" as a independent job
- Add names for the jobs which calling the action yamls
> chore(CI): Improve github actions (2nd)

- src/runtime/rpc/dns_resolver.cpp
- src/runtime/rpc/group_host_port.h
- src/runtime/rpc/rpc_host_port.cpp
- src/runtime/rpc/rpc_host_port.h
- src/runtime/test/host_port_test.cpp
- src/utils/fixed_size_buffer_pool.h
Issue: https://github.com/apache/incubator-pegasus/issues/1824
Complement the implementation of class host_port for immediate use in the future.
> feat(fqdn): add operator< and use shared_ptr for group_host_port() instead of raw pointer for host_port

- src/utils/errors.h
Add RETURN_ERRS_NOT_TRUE marco to simplify code
> feat(marco): Add RETURN_ERRS_NOT_TRUE marco to simplify code

- collector/metrics/metric_collector.go
https://github.com/apache/incubator-pegasus/issues/1820
> fix(collector): fix the parsing way of metrics returned by the server

- src/zookeeper/zookeeper_session.cpp
issue: https://github.com/apache/incubator-pegasus/issues/1863
Resolve the issue of Pegasus connection failure to zookeeper due to KDC service prohibiting DNS translation of IP to FQDN
> feat: Support meta_server connect to Kerberos sasl authenticated Zookeeper where KDC configured 'rdns = false'

- src/http/pprof_http_service.cpp
- src/utils/fmt_logging.h
- src/utils/test/logging.cpp
- src/utils/timer.h
This patch adds some useful LOG_TIMING* series macros to log the procedures
which may cost long time, they are helpful for trouble-shooting.
> feat(macro): Add LOG_TIMING* series macros

- src/replica/replica_stub.cpp
https://github.com/apache/incubator-pegasus/issues/1904
> fix(configs): add missing namespace in group validator of flags

- src/client/replication_ddl_client.cpp
- src/client/replication_ddl_client.h
fix bug from https://github.com/apache/incubator-pegasus/commit/2c9b5ed5d95ad89e2cd50ac3e34f57149788b9ce
> fix: fix recall_app with default app_name

- go-client/idl/base/host_port.go
- go-client/idl/base/host_port_test.go
https://github.com/apache/incubator-pegasus/issues/1947
> feat(go-client): Add new HostPort struct according to IDL

- idl/bulk_load.thrift
- src/meta/meta_bulk_load_service.cpp
- src/meta/test/meta_bulk_load_service_test.cpp
- src/replica/bulk_load/replica_bulk_loader.cpp
- src/replica/bulk_load/test/replica_bulk_loader_test.cpp
- src/runtime/rpc/rpc_host_port.h
- src/shell/commands/bulk_load.cpp
- Add a new macros SET_IP_AND_HOST_PORT, SET_VALUE_FROM_IP_AND_HOST_PORT,
SET_VALUE_FROM_HOST_PORT and FMT_HOST_PORT_AND_IP
- Add fill_partition_bulk_load_states() function to simplify code in
src/meta/test/meta_bulk_load_service_test.cpp
> refactor(FQDN): Add some convenient macros and update idl/bulk_load.thrift related code

- idl/duplication.thrift
- src/meta/duplication/meta_duplication_service.cpp
- src/meta/test/meta_duplication_service_test.cpp
- src/replica/duplication/duplication_sync_timer.cpp
- src/replica/duplication/test/duplication_sync_timer_test.cpp
- src/runtime/rpc/rpc_host_port.h
Add new convenient macros ASSERT_IP_AND_HOST_PORT for convenient using in tests.
> refactor(FQDN): Add some convenient macros and update idl/duplication.thrift related code

- src/utils/env.cpp
change encryption_method default value AES128 to AES256
> refactor(encryption): change default value of encryption_method from AES128 to AES256

- CMakeLists.txt
- run.sh
- src/base/test/CMakeLists.txt
- src/geo/test/CMakeLists.txt
- src/redis_protocol/proxy/CMakeLists.txt
- src/redis_protocol/proxy_ut/CMakeLists.txt
- src/sample/CMakeLists.txt
- src/server/CMakeLists.txt
- src/server/collector/CMakeLists.txt
- src/server/collector/main.cpp
- src/server/meta_server/CMakeLists.txt
- src/server/meta_server/main.cpp
- src/server/replica_server/CMakeLists.txt
- src/server/replica_server/main.cpp
- src/server/server_utils.cpp
- src/server/server_utils.h
- src/shell/command_helper.h
- src/test/function_test/backup_restore/CMakeLists.txt
- src/test/function_test/detect_hotspot/CMakeLists.txt
- src/test/function_test/partition_split/CMakeLists.txt
- src/test/function_test/recovery/CMakeLists.txt
- src/test/function_test/restore/CMakeLists.txt
- src/test/function_test/throttle/CMakeLists.txt
- src/test/kill_test/CMakeLists.txt
- src/test/pressure_test/CMakeLists.txt
This patch adds a new flag `--separate_servers` to indicate whether to build
`pegasus_collector`，`pegasus_meta_server` and `pegasus_replica_server` binaries
separately, otherwise a combined `pegasus_server` binary will be built. The
corresponding option in CMake is `SEPARATE_SERVERS`.
> feat: Support to build server binaries separately

- src/common/fs_manager.cpp
- src/meta/test/misc/misc.cpp
Use the current working directory rather than the fixed '/home/work/' directory.
> fix(ut): fix the dsn.meta.test using a directorty may has not permission

- src/meta/duplication/meta_duplication_service.cpp
https://github.com/apache/incubator-pegasus/issues/2025
> fix(duplication): fix the table name while checking if the table of the remote cluster has been created completely

- src/server/pegasus_server_impl.cpp
https://github.com/apache/incubator-pegasus/issues/2061
The monitor of the block cache usage is server-level and created by
`std::call_once` in a replica-level object, running periodically to update
the block cache usage.
However, once the replica-level object is stopped, the server-level
monitor would be cancelled; as a result,  the block cache usage would
never be updated.
> fix(rocksdb): fix the problem that the usage of block cache is not set for the metric

- .github/workflows/regular-build.yml
fix #2073 
- Unit test
- No code
> fix(CI): fix java regular workflow

- docker/pegasus-build-env/centos7/Dockerfile
Resolve https://github.com/apache/incubator-pegasus/issues/2071.
> fix(Dockerfile): Fix the yum install failure caused by its EOL

- .github/workflows/build-push-env-docker.yml
fix #2080 2080
- Unit test
- No code
> feat(docker): support arm64

- .github/workflows/labeler.yml
- .github/workflows/module_labeler_conf.yml
According to the actions/labeler@v5 configuration file format, this patch
updates the content.
> chore(CI): Update actions/labeler configuration file

- src/meta/meta_state_service_simple.cpp
- src/meta/meta_state_service_simple.h
- src/meta/test/balancer_validator.cpp
- src/replica/prepare_list.cpp
- src/test/bench_test/benchmark.cpp
Fix the build issues on my new develop environment with C/CXX compiler AppleClang 16.0.0.
> fix: fix some build errors on the latest MacOS
