apache/incubator-pegasus

.gitignore
docs/installation.md
scripts/pack_tools.sh
src/shell/CMakeLists.txt
src/shell/args.h
src/shell/command_executor.h
src/shell/commands.h
src/shell/linenoise/LICENSE
src/shell/linenoise/linenoise.c
src/shell/linenoise/linenoise.h
src/shell/main.cpp
src/shell/sds/LICENSE
src/shell/sds/sds.c
src/shell/sds/sds.h
src/shell/sds/sdsalloc.h

Since gnu readline is GPL licensed, it's conflicted with us apache license. In this PR we replace readline with antirez/linenoise, which is a lightweight line-edit lib identical with readline but has a much smaller code base. Futhermore we implemented **history**, **completion**, **commands hint** using linenoise.

shell: replace readline with linenoise

---

src/redis_protocol/proxy/config.ini
src/redis_protocol/proxy/main.cpp
src/redis_protocol/proxy_lib/proxy_layer.cpp
src/redis_protocol/proxy_lib/proxy_layer.h
src/redis_protocol/proxy_lib/redis_parser.cpp
src/redis_protocol/proxy_lib/redis_parser.h
src/redis_protocol/proxy_ut/config.ini
src/redis_protocol/proxy_ut/redis_proxy_test.cpp

1. fix the thread safety problem when socket is closed
2. when parse error, close the socket instead of abort
3. make the proxy_session & redis_parser's semantic more clear
4. make some rpc codes inline by declare it in source code

redis_proxy: several bug fix & some refactor

---

src/server/pegasus_server_write.cpp
src/server/pegasus_server_write.h
src/server/pegasus_write_service.cpp
src/server/pegasus_write_service.h
src/server/pegasus_write_service_impl.h

- **bugfix**: multi_put and multi_remove won't return error for invalid user argument
- batch_write and batch_remove will return error when rocksdb::WriteBatch failed. We used to assume it always returns OK.
- add logging on batch write error.

server: refine write process

---

src/reporter/pegasus_counter_reporter.h

```
In file included from /home/wutao1/work/boost_1_68_0/output/include/boost/asio.hpp:118:0,
from /home/wutao1/work/pegasus-boost68/src/reporter/pegasus_counter_reporter.h:11,
from /home/wutao1/work/pegasus-boost68/src/server/info_collector_app.cpp:6:
/home/wutao1/work/boost_1_68_0/output/include/boost/asio/signal_set.hpp:114:58: error: macro "signal_set" requires 4 arguments, but only 1 given
explicit signal_set(boost::asio::io_context& io_context)
^
/home/wutao1/work/boost_1_68_0/output/include/boost/asio/signal_set.hpp:132:70: error: macro "signal_set" requires 4 arguments, but only 2 given
signal_set(boost::asio::io_context& io_context, int signal_number_1)
^
/home/wutao1/work/boost_1_68_0/output/include/boost/asio/signal_set.hpp:157:26: error: macro "signal_set" requires 4 …
```

thirdparty: fix build failure on boost-1.68 enviroment

---

src/shell/commands.h
src/shell/main.cpp

This PR I introduce a new command called `cc [cluster_name]`, which can change the current working cluster. This command is useful when we open pegasus shell in [gotty](https://github.com/yudai/gotty), for example when we run `gotty -w ./run.sh shell`, we are not able to re-specify the cluster:
```
task_spec.cpp:94:register_task_code():overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX from THREAD_POOL_DEFAULT to THREAD_POOL_META_SERVER
task_spec.cpp:94:register_task_code():overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX_ACK from THREAD_POOL_DEFAULT to THREAD_POOL_META_SERVER
task_spec.cpp:94:register_task_code():overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX from THREAD_POOL_META_SERVER to …
```

shell: support change cluster

---

scripts/pack_common.sh

add 32/64-bit check when getting stdcpp or system lib
only allows one lib to be found

scripts: fix get_xx_lib funcs in pack_common.sh

---

src/server/brief_stat.cpp
src/server/info_collector.cpp
src/server/info_collector.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/shell/command_helper.h
src/shell/commands.h

https://github.com/XiaoMi/pegasus/issues/184

monitor: expose rocksdb statistics to pegasus

---

src/geo/bench/bench.cpp
src/server/CMakeLists.txt
src/shell/CMakeLists.txt
src/shell/command_helper.h
src/shell/commands.h

we can see more key/value size statistics now.
the key/value size statistics part of output of shell command `count_data -z` will look like:
```
INFO: split[0]: 103800 rows
INFO: split[1]: 68900 rows
INFO: split[2]: 75700 rows
INFO: split[3]: 55200 rows
Count partially, total 303600 rows.
[hash_key_size]
max = 32
med = 32.00
avg = 32.00
min = 32
P99 = 32.00
P95 = 32.00
P90 = 32.00
[sort_key_size]
max = 13
med = 13.00
avg = 13.00
min = 13
P99 = 13.00
P95 = 13.00
P90 = 13.00
[value_size]
max = 155004
med = 1714.41
avg = 3233.96
min = 999
P99 = 21555.07
P95 = 11357.16
P90 = 7609.97
[row_size]
max = 155049
med = 1726.63
avg = 3278.96
min = 1044
P99 = 21584.27
P95 = 11409.80
P90 = 7662.66
```

shell: use rocksdb's histogram for shell key-value size statistics

---

scripts/pack_common.sh

if ztsd is installed by yourself, then you can not get lib by ldconfig.

scripts: fix pack_common.sh

---

scripts/pegasus_check_clusters.py
scripts/pegasus_check_ports.py
scripts/py_utils/__init__.py
scripts/py_utils/lib.py

- scripts/pegasus_check_clusters.py: 检查集群状态，看是否负载不均衡，是否有 unhealthy 节点。目前均衡的判断还比较粗糙，可能有误报，后面可以结合 #237 来做这个事情。
如下图的 c3srv-xchat 没有不均衡的情况，所以输出为空
```
=== c3srv-ada
address                 status              replica_count       primary_count       secondary_count     
xxxxxxxxxxxxx:47801     ALIVE               86                  48                  38                  
xxxxxxxxxxxxx:47801     ALIVE               86                  48                  38                  
xxxxxxxxxxxxx:47801     ALIVE               93                  13                  80                  
xxxxxxxxxxxxx:47801     ALIVE               69                  12                  57                  
xxxxxxxxxxxxx:47801     ALIVE               87                  16                  70 …
```

scripts: check health status for all clusters

---

src/base/pegasus_const.cpp
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/test/manual_compact_service_test.cpp
src/server/test/pegasus_compression_options_test.cpp
src/server/test/pegasus_server_test_base.h
src/server/test/pegasus_server_write_test.cpp
src/server/test/pegasus_storage_options_test.cpp
src/server/test/pegasus_write_service_test.cpp

issue: https://github.com/XiaoMi/pegasus/issues/236
_暂不支持表级配置
暂不支持动态修改_

rocksdb: compression types are configurable for each level separately

---

scripts/pack_common.sh

because we need copy dir `scripts/py_utils`.
* add `-r` option to copy dir.
* add `-L` option to dereference symbolic link.

scripts: fix pack_common.sh to enable copy dir

---

scripts/falcon_screen.json

Fix invalid json format, otherwise falcon_screen.py can't decode current falcon_screen.json

falcon: fix invalid json format

---

src/shell/commands.h

```
>>> recover -s 127.0.0.1:39201
parse -s as a ip:port node failed
```
because `dsn::utils::split_args(args.argv[1], tokens, ',');` wants to split "-s", but it should split node_list_str.

shell: fix a bad parameter when split node_list_str

---

scripts/pack_common.sh
scripts/pack_server.sh
scripts/pack_tools.sh

to fix the `lib file name not match` problem like:
- ldd pegasus_server: libaio.so.1 => /lib64/libaio.so.1
- pack_server: DSN_ROOT/lib/libaio.so.1.0.0

scripts: fix pack tools to copy lib with the right name

---

src/server/info_collector.cpp
src/shell/command_helper.h
src/shell/commands.h
src/shell/main.cpp

for app_stat:
* split column `rdb_mem_mb` to `mem_tbl_mb` and `mem_idx_mb`.
for nodes:
* add `-r|--resolve_ip` option.
* add `-u|--resource_usage` option to add columns: `memused_res_mb`, `block_cache_mb`, `mem_tbl_mb  mem_idx_mb`, `disk_avl_total_ratio`, `disk_avl_min_ratio`.

 shell: improve subcommand app_stat and nodes

---

src/include/pegasus/client.h
src/redis_protocol/proxy_lib/redis_parser.cpp
src/test/function_test/test_ttl.cpp

fix the unit test failure:
```
/home/travis/build/XiaoMi/pegasus/src/test/function_test/test_ttl.cpp:221: Failure
Value of: ttl_seconds > default_ttl - sleep_for_expiring - sleep_for_envs_effect - error_allow && ttl_seconds <= default_ttl - sleep_for_expiring - sleep_for_envs_effect
Actual: false
Expected: true
ttl is 3526
```

bugfix: fix redis proxy set ttl bug; fix unit test

---

src/shell/commands/node_management.cpp
src/shell/commands/table_management.cpp
src/shell/main.cpp

`cluster_info`:
- remove useless output lines
- add options: `[-r|--resolve_ip]`, `[-o|--output file_name]` and `[-j|--json_pretty]`
`app`:
- remove useless output lines
- add options: `[-r|--resolve_ip]`, and `[-j|--json_pretty]`
`app_disk`:
- remove useless output lines
- add option: `[-j|--json_pretty]`
- output `partitions not counted` and `replicas not counted` by default
`app_stat`:
- remove useless output lines
- add option: `[-j|--json_pretty]`
`get_app_envs`:
- remove useless output lines
- add option: `[-j|--json_pretty]`
在这些命令都支持你json格式化输出后, 一些运维脚本也可从shell脚本改成python等语言, 提高可读性

shell: JSON output supported for more commands

---

scripts/falcon_screen.json
src/server/available_detector.cpp
src/server/available_detector.h
src/server/capacity_unit_calculator.cpp
src/server/capacity_unit_calculator.h
src/server/config-server.ini
src/server/config.ini
src/server/info_collector.cpp
src/server/info_collector.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_write_service.cpp
src/server/pegasus_write_service.h
src/server/pegasus_write_service_impl.h
src/server/result_writer.cpp
src/server/result_writer.h
src/server/test/CMakeLists.txt
src/server/test/capacity_unit_calculator_test.cpp
src/shell/command_helper.h
src/shell/commands/table_management.cpp

*:support capacity unit read/write statistics

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

the problem is: when the db is not opened, set_usage_scenario to normal will fail, and print some useless error log.

pegasus_server: fix set usage scenario problem when open db

---

.arcconfig
src/base/test/config.ini
src/geo/bench/config.ini
src/geo/test/config.ini
src/redis_protocol/proxy/config.ini
src/redis_protocol/proxy_ut/config.ini
src/sample/config.ini
src/server/config-server.ini
src/server/config.ini
src/server/test/config.ini
src/shell/config.ini
src/test/bench_test/config.ini
src/test/function_test/config.ini
src/test/kill_test/config.ini
src/test/upgrade_test/config.ini

The configurations 
- `max_input_queue_length ` 
- `hpc_logger`
- `cli_local`
- `cli_remote`
- ` updating_rocksdb_sstsize_interval_seconds`
- `start_nfs`
- `fast_execution_in_network_thread`
- `fast_run`
already have no codes related.
Previously @qinzuoyan had cleared `max_input_queue_length ` from rdsn: https://github.com/XiaoMi/rdsn/pull/191
@shengofsun has cleared `cli_local` and `cli_remote` from rdsn: https://github.com/XiaoMi/rdsn/pull/156
@acelyc111 has changed `updating_rocksdb_sstsize_interval_seconds` to `update_rdb_stat_interval` #212
@shengofsun  has cleared `start_nfs` from rdsn: https://github.com/XiaoMi/rdsn/pull/142
@qinzuoyan has cleared `fast_execution_in_network_thread` from rdsn in 2016: https://github.com/XiaoMi/rdsn/commit/2e43e94bb489af286691ed0f6bfdf3997cf10195 …

refactor: remove some useless configs

---

src/server/config-server.ini
src/server/config.ini
src/server/info_collector.cpp
src/server/info_collector.h
src/server/result_writer.cpp
src/shell/command_helper.h
src/shell/commands/node_management.cpp
src/shell/commands/table_management.cpp

Current capacity unit calculation (committed in #318) has these problems:
* not robust enough: 
* if get_apps_and_nodes returns false, then terminate, which may cause CU lost.
```
if (!get_apps_and_nodes(sc, apps, nodes))
return false;
```
**Solution**: retry for some times after several seconds.
* if decode_node_perf_counter_info failed for one node, then terminate all, which is not reasonable.
``` 
if (!decode_node_perf_counter_info(node_addr, results[i], info))
return false;
```
**Solution**: ignore failure nodes.
* stat result is not compact enough:
* in the old may, the stat result is like:
```
"2019-06-16 20:35:45" : "10.239.35.217:34801" => "{\"temp\":[8,11]}"
```
* in the new way, the stat result is like (using app id instead of app name, and add prefix `cu@` in sort_key to diff …

server: improve capacity unit calculation

---

scripts/create_table.py
scripts/py_utils/lib.py

Add convenience script for creating tables. Users can specify the table owners and their department, the write throttling, as well as the required attributes like 'partition count' and 'table name'.
If the table is created before, users can still reset the table's environments.
This script is at an early stage.
I use python for this script, reusing the utilities provided by py_utils/lib.py.
Tests 
```
➜  pegasus git:(create) ✗ ./scripts/create_table.py -t ai_user_info \
-d "云平台部-存储平台-KV系统组" \
-u "wutao1&qinzuoyan" \
-c c3tst-dup2 \
-w "2000*delay*100" \
-p 16
Confirm to create table:
{
"cluster": "c3tst-dup2", 
"depart": "云平台部-存储平台-KV系统组", 
"partition_count": 16, 
"table": "ai_user_info", 
"user": "wutao1&qinzuoyan", 
"write_throttling": …
```

scripts: add convenience script for creating table

---

src/server/config.ini
src/server/pegasus_server_impl.cpp
src/server/test/pegasus_compression_options_test.cpp

Keep default value in code the same as what it in config.ini, reduce users' and developers' confusion.
No user faced changes.
Tests 
- Unit test
Code changes
No
No
No
No
Side effects
No
No
If you are using `src/server/config.ini` as the replica-server config file, this PR changes nothing.
If you are using your own config file and not specify the following configurations, their default values will changed as follows:
```
rocksdb_abnormal_get_time_threshold_ns = 100000000
rocksdb_abnormal_get_size_threshold = 1000000 …
```

refactor: keep default value in code the same as what it in config.ini

---

src/geo/bench/bench.cpp
src/geo/bench/config.ini
src/geo/lib/geo_client.cpp
src/geo/lib/geo_client.h
src/geo/lib/latlng_extractor.cpp
src/geo/lib/latlng_extractor.h
src/geo/test/config.ini
src/geo/test/extractor_test.cpp
src/geo/test/geo_test.cpp
src/redis_protocol/proxy/config.ini
src/redis_protocol/proxy_lib/redis_parser.cpp
src/redis_protocol/proxy_ut/config.ini
src/shell/commands/data_operations.cpp

Support more configuration for geo_client.
set `min_level`, `latitude_index` and `longitude_index` in geo_client's config.ini before inserting data into DB, and they are immutable after data has been inserted.
```
[geo_client.lib]
...
min_level = 12
max_level = 16
latitude_index = 5
longitude_index = 4
```
`min_level` and `max_level` are parameters for data search algorithm in S2.
https://github.com/XiaoMi/pegasus/blob/d227b4c0b6f555572025f433de85ff6eca7abb86/src/geo/lib/geo_client.cpp#L463 https://github.com/XiaoMi/pegasus/blob/d227b4c0b6f555572025f433de85ff6eca7abb86/src/geo/lib/geo_client.cpp#L510
`latitude_index` and `longitude_index` are parameters for extracting latitude and longitude from string type value. 
https://github.com/XiaoMi/pegasus/blob/b7e9b2ecb292cbacfca4b08113190084155f …

GEO: Support more configuration for geo_client

---

src/geo/bench/bench.cpp
src/geo/lib/geo_client.cpp
src/geo/lib/geo_client.h
src/geo/test/geo_test.cpp
src/redis_protocol/proxy_lib/redis_parser.cpp
src/redis_protocol/proxy_lib/redis_parser.h
src/redis_protocol/proxy_ut/redis_proxy_test.cpp

Support GEOPOS API for geo_client and redis proxy
Add new client API
- Unit test
1. start geo redis proxy
2. excute commands as follows:
```
127.0.0.1:6379> set key1 11|111
OK
127.0.0.1:6379> set key2 22|122
OK
127.0.0.1:6379> geopos "" not_exist1 key1 not_exist2 key2 not_exist3
1) (nil)
2) 1) "111.000000"
2) "11.000000"
3) (nil)
4) 1) "122.000000"
2) "22.000000"
5) (nil)
```
Yes
Not relate
Yes
Not relate
No
A little
No
Yes
Yes
- …

GEO: support GEOPOS API for redis proxy

---

src/geo/bench/CMakeLists.txt
src/geo/bench/bench.cpp
src/shell/CMakeLists.txt
src/shell/command_helper.h
src/shell/commands/data_operations.cpp
src/test/bench_test/pegasus_bench.cpp

https://github.com/XiaoMi/pegasus/issues/361#issuecomment-515656652
Use rocksdb::Statistics to calc histogram, instead of using rocksdb::HistogramImpl.
rocksdb::HistogramImpl is not exposed, and it‘s crimping ’remove MY_PROJ_INC_PATH‘.
Perf:
[The overhead of rocksdb::Statistics is  is usually small but non-negligible. We usually observe an overhead of 5%-10%.](https://github.com/facebook/rocksdb/wiki/Statistics#stats-level-and-performance-costs)
But in our case, no high need for stat performance, and scan is low concurrency.
The command-output is changed.
```
>>> count_data -a
...
INFO: split[31]: 4597928 rows
Count done, total 153553396 rows.
============================[hash_key_size]============================
Count: 153553396 Average: 15.4846  StdDev: 4.87
Min: 7  Median: 13.0443 …
```

shell & bench: use rocksdb::Statistics to calc histogram

---

src/client_lib/CMakeLists.txt

On CMake <3.12, OBJECT libraries shouldn't link to anything. 
On CMake >=3.12, OBJECT libraries can use target_link_libraries().
As the minimun version of CMake is 3.5.2, we should not use target_link_libraries on OBJECT libraries.
use target_include_directories to include headers of rocksdb in client_lib
Tests 
- No code

CMake: fix client_lib

---

src/redis_protocol/proxy/CMakeLists.txt
src/server/CMakeLists.txt

fix dependency error of curl when compile project by gcc 7.4.0
link error looks like:
```
/home/laiyingchun/pegasus/rdsn/thirdparty/output/lib/libcurl.a(libcurl_la-url.o): In function `fix_hostname':
url.c:(.text+0xc28): undefined reference to `stringprep_check_version'
url.c:(.text+0xc46): undefined reference to `idna_to_ascii_lz'
url.c:(.text+0xc4d): undefined reference to `stringprep_locale_charset'
url.c:(.text+0xc7f): undefined reference to `idna_to_unicode_lzlz'
url.c:(.text+0xcda): undefined reference to `tld_check_lz'
url.c:(.text+0xcef): undefined reference to `idn_free'
url.c:(.text+0xcf8): undefined reference to `tld_strerror'
/home/laiyingchun/pegasus/rdsn/thirdparty/output/lib/libcurl.a(libcurl_la-url.o): In function `Curl_disconnect':
url.c:(.text+0x5c2a): undefined …
```

compile/link: fix dependency error of curl

---

scripts/travis.sh
src/base/test/main.cpp
src/geo/test/main.cpp
src/redis_protocol/proxy_ut/redis_proxy_test.cpp
src/server/test/main.cpp
src/shell/CMakeLists.txt
src/test/function_test/main.cpp

1. pegasus_unit_test doesn't return err when it failed
1. scripts/travis.sh exit 0 even tests failed
fix
Tests 
- Unit test

fix: unit tests & travis.sh exit with err

---

scripts/pack_client.sh
scripts/pack_server.sh
scripts/pack_tools.sh

Fix problem for missing boost regex library.
Pack up libboost_regex.so in pack_client.sh, pack_server.sh, pack_tools.sh.
Tests 
- No code

build: pack boost.regex with binaries

---

run.sh
src/CMakeLists.txt
src/geo/bench/CMakeLists.txt
src/geo/lib/CMakeLists.txt
src/geo/test/CMakeLists.txt
src/redis_protocol/proxy/CMakeLists.txt
src/redis_protocol/proxy_ut/CMakeLists.txt
src/reporter/CMakeLists.txt
src/server/CMakeLists.txt
src/server/config.min.ini
src/server/test/CMakeLists.txt
src/shell/CMakeLists.txt
src/test/bench_test/CMakeLists.txt
src/test/function_test/CMakeLists.txt

https://github.com/XiaoMi/pegasus/issues/361#issuecomment-515656652
1. cleanup prometheus links
1. cleanup default libs
1. disable create table stat in onebox
Tests 
- No code

build(cmake): cleanup lib links

---

src/CMakeLists.txt
src/reporter/CMakeLists.txt

使用find_package导入prometheus后, 由于prometheus-cpp的export写的不够灵活, INTERFACE_LINK_LIBRARIES中的curl库是绝对地址.
这就导致travis的build出现问题, 因为travis中thirdparty是prebuild的, 所以curl路径写死了为: `/home/travis/build/XiaoMi/pegasus/rdsn/thirdparty/output/lib/libcurl.a`. 
这样的话, 我们个人的pegasus分支跑travis都会出现找不到`/home/travis/build/XiaoMi/pegasus/rdsn/thirdparty/output/lib/libcurl.a`的问题, 而编译失败.
现在提的解决方法是, 通过替换prometheus的INTERFACE_LINK_LIBRARIES为当前工程中能find到的curl库路径.
还有一个工作量大点的方案是, 将prometheus改成optional的, 不指定编译, 就不要编了. 之后也可以考虑将redis/geo等也做成optional. 更进一步地, 下载thirdparty也可以选项化.
**大家看看有没有必要**
Tests 
- No code

build(cmake): fix curl link of prometheus

---

src/server/config.ini
src/server/config.min.ini
src/server/info_collector_app.h

In info collector server, there are four timer tasks(LPC_PEGASUS_APP_STAT_TIMER, LPC_PEGASUS_STORAGE_SIZE_STAT_TIMER, LPC_DETECT_AVAILABLE and LPC_PEGASUS_CAPACITY_UNIT_STAT_TIMER). Each of these timer task occupies a thread in THREAD_POOL_DEFAULT. Each of these timer tasks calls remote procedure to meta server(which produce a callback), and wait for the rpc's callback to execute. If the worker_count <= 4(it is 2 now), all of these threads are occupied by these timer tasks. so their rpc's callbacks can't get a thread to run. It comes to be a deadlock(timer task wait for rpc's callback to execute, and rpc's callback wait for the timer task to release the thread). 
https://github.com/XiaoMi/pegasus/issues/392
change the thread count of THREAD_POOL_DEFAULT to 5
- Need to …

fix: fix the bug of deadlock in info collector in onebox environment

---

src/shell/command_helper.h

Some new perf-counters were added in rdsn, which format are: `.*@app_name`. 
And in command_hepler::get_app_stat, we will get all of the perf-counters with format of `.*@.*`.
Well there is a assert to assume the string after `@` is gpid, so parsing the per-counters with format `.*@app_name` will result in info-collector server crash.
remove the assert that assuming the string after '@' is gpid
yes
no
no

refactor: remove the assert in get_app_stat

---

src/shell/commands.h
src/shell/commands/node_management.cpp
src/shell/main.cpp

We used to get server basic qps and latency information by command `server_stat`. However,  `server_stat` is hard to read, and some memory-related statistics have already be shown by command `nodes -u`. As a result, I add command `nodes -q` to show qps and latency information provided by `server_stat`.
Add command `nodes -q` to show server read, write qps and read, write latency.
The command sample is below:
```
>>> nodes -q
[details]
address   status    get_qps  get_p99(ms)  mget_qps  mget_p99(ms)  put_qps  put_p99(ms)  mput_qps  mput_p99(ms)
host1     ALIVE       23.86         0.13     86.63          0.44    42.57         3.27      0.00          0.00
host2     ALIVE       18.61         0.12     99.69          0.52     0.00         3.20      0.00          0.00
host3     ALIVE       21.88 …
```

feat(shell): add qps and p99 statistics while list_node

---

src/shell/command_helper.h

There is no interface to supply perf-counters of all partitions of all apps
Add a interface(get_app_partition_stat) to get perf-counters of all partitions of all apps.
yes
no
no

feat: add a interface to get perf-counters info of all partitions of all apps

---

src/server/info_collector.cpp
src/server/info_collector.h
src/shell/command_helper.h

#435 this pr provide table level statistics
yes
yes
no
- Need update falcon screen
yes

feat(collector): add statistics for estimate key number of table

---

src/server/info_collector_app.cpp
src/server/info_collector_app.h

HTTP is not supported in info collector now, so we can't get some info from info collector through http request
Add http_server for info collector

feat: add http_server for info collector

---

run.sh
scripts/start_zk.sh

`run.sh test` doesn't check for availability of zookeeper when it fails to start, it will continue and fail eventually when some unit tests (`function_test`) detect that the onebox is not started. 
```
~/build/XiaoMi/pegasus/src/builder/bin/pegasus_function_test ~/build/XiaoMi/pegasus
============
start global_env()
meta1 pid: 0
pegasus_function_test: /home/travis/build/XiaoMi/pegasus/src/test/function_test/global_env.cpp:39: void global_env::get_dirs(): Assertion `dsn::utils::pipe_execute(cmd2, ss2) == 0' failed.
./run.sh: line 35: 18247 Aborted                 (core dumped) GTEST_OUTPUT="xml:$REPORT_DIR/basic.xml" GTEST_FILTER="basic.*" ./$test_case $config_file $table_name
```
```
Decompressing zookeeper...
JMX enabled by default
Using config: …
```

fix: retry starting zookeeper if it failed on onebox environment

---

src/client_lib/pegasus_client_factory_impl.cpp
src/redis_protocol/proxy/main.cpp
src/server/main.cpp
src/shell/main.cpp

According to https://github.com/XiaoMi/rdsn/pull/379, we removed `DSN_CORE_VERSION`.
But this macro still has some usages on Pegasus side, we should remove them as well.
Tests 
- No code

refactor: update rdsn and remove DSN_CORE_VERSION

---

src/reporter/pegasus_counter_reporter.cpp
src/server/available_detector.cpp
src/server/config.ini
src/server/config.min.ini
src/server/info_collector.cpp

Currently, there are 3 places defining the cluster name:
- `[pegasus.collector] cluster = onebox`
- `[pegasus.server] perf_counter_cluster_name = onebox`
- `[replication] cluster_name = onebox`
Since both the rdsn module and pegasus need "cluster_name", we can use the common util
`dsn::replication::get_current_cluster_name` to retrieve this config (by reading `[replication] cluster_name`), instead of reading config in separate places.
Tests 
```sh
> ./run.sh start_onebox -r 3 -m 2 -c # start collector as well, use config.min.ini
> ./run.sh list_onebox # no coredump
wutao1   25359     1  0 17:10 pts/4    00:00:00 /home/wutao1/git/release/pegasus/onebox/collector/pegasus_server config.ini -app_list collector
wutao1   25136     1  0 17:10 …
```

refactor(config): remove duplicated config items for cluster name

---

src/shell/argh.h

argh is a library to replace getopts: https://github.com/adishavit/argh. It can improve the usability and codes' readability of pegasus shell. It will be used in https://github.com/XiaoMi/pegasus/pull/466.

feat(shell): add dependency argh to parse options and arguments

---

src/shell/commands.h
src/shell/commands/duplication.cpp
src/shell/main.cpp

This PR adds some shell commands for duplication, including: 
- add_dup
- query_dup
- remove_dup
- start_dup
- pause_dup
Tests 
**Add duplication**
```
>>> add_dup temp onebox3
adding duplication failed [app: temp, remote: onebox3, freeze: false, error: ERR_INVALID_PARAMETERS]
>>> add_dup temp onebox2
adding duplication succeed [app: temp, remote: onebox2, appid: 2, dupid: 1580962256, freeze: false]
>>> query_dup temp
duplications of app [temp] are listed as below:
dup_id      status    remote cluster  create time          
1580962256  DS_START  onebox2         2020-02-06 12:10:56  
>>> query_dup temp2
querying duplications of app [temp2] failed, error=ERR_APP_NOT_EXIST
>>> query_dup temp -d
duplications of app [temp] in detail: …
```

feat(dup): implement duplication related shell commands

---

src/client_lib/CMakeLists.txt

Our user reported that pegasus_client_shared had some libraries missing, which I found are
-    dsn_replication_client
-    dsn_replication_common
They are already linked to pegasus_client_static, but not to pegasus_client_shared.
This PR has been confirmed to work on our user's environment.

fix: add libraries missing for pegasus_client_shared

---

src/server/pegasus_server_impl.cpp

- It's a bug to call `rocksdb::CancelAllBackgroundWork` when close replica after db open failed
- Explicitly delete db in pegasus_server_impl's destructor
No related.
Tests 
- Unit test
No
No
Yes
- No code
No
Code changes
No
No
No
No
Side effects
No
No
No
Yes
No
No

fix: use db when it has been opened

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

Add definition of `partition_version`, used for partition split to guarantee data consistency. 
Tests 
- Unit test

feat(split): add partition_version

---

src/shell/command_helper.h

support of getting backup request perf-counter in command_helper
Using function get_app_partition_stat, we can get backup_request_qps for each app.

feat: support of getting backup request perf-counter in command_helper

---

src/server/meta_store.cpp
src/server/meta_store.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_write_service_impl.h
src/server/test/CMakeLists.txt

Step 2 of https://github.com/XiaoMi/pegasus/issues/468 : 
- Store `last_decree`, `data_version`, `last_manual_compact_finish_time` both in manifest and another column family.
- Still read these values from **manifest**.
No user faced changes.
before this patch | 读写比 | 运行时长 | 读QPS | 读Avg延迟 | 读P99延迟 | 写TPS | 写Avg延迟 | 写P99延迟 
-- | -- | -- | -- | -- | -- | -- | -- | --
(1)数据加载: 3客户端*10线程 | 0:1 | 1.98 | - | - | - | 41366 | 709 | 3565
(2)读写同时: 3客户端*15线程 | 1:3 | 1.29 | 16476 | 312 | 1041 | 48318 | 821 | 4355
(3)读写同时: 3客户端*30线程 | 30:1 | 0.29 | 273243 | 301 | 695 | 9042 | 660 | 3017
(4)数据只读: 6客户端*100线程 | 1:0 | 0.1 | 809753 | 690 | 2023 | - | - | -
after this patch | 读写比 | 运行时长 | 读QPS | 读Avg延迟 | 读P99延迟 | 写TPS | 写Avg延迟 | 写P99延迟 
-- | -- | -- | -- | -- | -- | -- | -- | --
(1)数据加载: 3客户端*10线程 | 0:1 | …

feat(rocksdb): write meta info both in manifest and meta CF

---

src/shell/commands/disk_rebalance.cpp

`disk_replica` command will crash due to the bug of ` multi_printer.add(std::move(disk_printer))`:
https://github.com/XiaoMi/pegasus/blob/47cea6363e963eeeb166cbd1661c5636324bb8e4/src/shell/commands/disk_rebalance.cpp#L235-L251
it can only be executed after the `disk_printer` was created, in other word, It should be move out of `for (const auto &disk_info : resp.disk_infos)` loop and in `for (const auto &err_resp : err_resps)` loop which will create new `disk_printer` every time.
Actually, It should be same with `disk_capacity` :https://github.com/XiaoMi/pegasus/blob/47cea6363e963eeeb166cbd1661c5636324bb8e4/src/shell/commands/disk_rebalance.cpp#L150-L169
Tests 
- Need to update …

fix(shell): disk_replica printer bug

---

src/shell/commands/data_operations.cpp
src/shell/commands/disk_rebalance.cpp

```
==12208== ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000cf0a04 at pc 0x5fe0c5 bp 0x7fff4b80eee0 sp 0x7fff4b80eed8
READ of size 1 at 0x000000cf0a04 thread T0
#0 0x5fe0c4 (/home/jiashuo1/work/pegasus/DSN_ROOT/bin/pegasus_shell/pegasus_shell+0x5fe0c4)
#1 0x586894 (/home/jiashuo1/work/pegasus/DSN_ROOT/bin/pegasus_shell/pegasus_shell+0x586894)
#2 0x59b230 (/home/jiashuo1/work/pegasus/DSN_ROOT/bin/pegasus_shell/pegasus_shell+0x59b230)
#3 0x5abb16 (/home/jiashuo1/work/pegasus/DSN_ROOT/bin/pegasus_shell/pegasus_shell+0x5abb16)
#4 0x462c28 (/home/jiashuo1/work/pegasus/DSN_ROOT/bin/pegasus_shell/pegasus_shell+0x462c28)
#5 0x463156 (/home/jiashuo1/work/pegasus/DSN_ROOT/bin/pegasus_shell/pegasus_shell+0x463156)
#6 0x465702 …
```

fix(asan): global-buffer-overflow in function escape_sds_argv of data_operations.cpp

---

src/shell/command_helper.h

#505 pr should support `table level` statistics, but some necessary code which in `command_helper.h` was deleted by mistake in some commit. This pr re-add it.
*  deploy latest code with latest pegasus server config
*  open falcon and get the table level qps and bytes statistics
*  calc theoretical bytes, and see whether `falcon_qps × single_request_size` ≈ `falcon_bytes`
The result as follow:
**Note:** for single scan bytes is unavailable, so don‘t calc it.

fix(collector): throughput statistics isn’t right

---

src/shell/commands.h
src/shell/commands/node_management.cpp

In shell tools, we can use `app_stat -q` to show app's qps, and we also can use `nodes -q` to show nodes' qps. However, the results of two command are different. This pull request fix this bug and add cu in `nodes -q` command.
Qps counters are like `replica*app.pegasus*put_qps@1.0`, we should use `perf-counters-by-prefix` to filter app id and partition index, and accumulate them to get qps of specific node.
We record P99 and P999 latency, those counters are like `zion*profiler*RPC_RRDB_RRDB_PUT.latency.server` and `zion*profiler*RPC_RRDB_RRDB_PUT.latency.server.p999`, and latency value won't be accumulated.
As a result, I separate qps and latency in two query-commands, and display them in `nodes -q`. 
`nodes -q` command example:
```
>>> nodes -q
[details]
address      status    get_qps …
```

fix: node qps sum inconsistent with app qps sum

---

src/shell/command_helper.h

```
#0  get_app_partition_stat (sc=sc@entry=0x3753450, rows=...) at /home/jiashuo1/work/pegasus/src/server/../shell/command_helper.h:784
#1  0x00000000004c43ad in pegasus::server::info_collector::on_app_stat (this=0x3753420) at /home/jiashuo1/work/pegasus/src/server/info_collector.cpp:136
#2  0x00007ff0d894cf61 in operator() (this=0x38d40e4) at /home/jiashuo1/app/toolchain/output/include/c++/4.8.2/functional:2464
#3  dsn::timer_task::exec (this=0x38d4014) at /home/jiashuo1/work/pegasus/rdsn/src/core/core/task.cpp:475
#4  0x00007ff0d894e059 in dsn::task::exec_internal (this=this@entry=0x38d4014) at /home/jiashuo1/work/pegasus/rdsn/src/core/core/task.cpp:180
#5  0x00007ff0d89a4c7d in dsn::task_worker::loop (this=0x3110bb0) at /home/jiashuo1/work/pegasus/rdsn/src/core/core/task_worker.cpp:211 …
```

fix(collector): no validate the app_name after parse_app_perf_counter_name

---

src/server/info_collector.cpp
src/server/info_collector.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/table_stats.h
src/shell/command_helper.h
src/shell/commands/table_management.cpp

Ref https://github.com/XiaoMi/pegasus/issues/496
- Support to monitor more rocksdb metrics to observe how the storage system works
- Provide a way to optimize rocksdb configurations and user workload
- `replica*app.pegasus*rdb.bf_seek_total@<gpid>`
Aka `rocksdb::Tickers::BLOOM_FILTER_PREFIX_CHECKED`. Number of times bloom was checked before creating iterator on a file.
- `replica*app.pegasus*rdb.bf_seek_negatives<gpid>`
Aka `rocksdb::Tickers::BLOOM_FILTER_PREFIX_USEFUL`.  The number of times the check was useful in avoiding iterator creation (and thus likely IOPs).
- `replica*app.pegasus*rdb.bf_point_positive_true<gpid>`
Aka `rocksdb::Tickers::BLOOM_FILTER_FULL_TRUE_POSITIVE`. Of times bloom FullFilter has not avoided the reads and data actually exist.
- …

feat(metrics): Add bloom filter related metrics

---

src/server/config.ini
src/server/pegasus_server_impl.cpp
src/shell/commands/table_management.cpp

- Support to config `bits_per_key` for Bloom filter to provide lower false positive rate
- Support to config `format_version` for SST to provide a faster and more accurate Bloom filter  implementation
Add config in replica server's config.ini:
```
[pegasus.server]
rocksdb_bloom_filter_bits_per_key = 10
rocksdb_format_version = 2
```
1. Write test data set A
2. Read test data set B, whose hashkey scale size is 100 times larger than test data set A.
So 99% of these items are not exist, but these point lookups will consult Bloom filters, then negative or positive will be returned by Bloom filters to indicate whether the key is definity not exist or may exist.
3. Oberve `point_fp_rate` in shell command `app_stat`
- When …

feat(rocksdb): Support more configurable items for bloom filter

---

scripts/pack_server.sh
src/reporter/pegasus_counter_reporter.cpp

The prometheus exposer formerly bound to an external IP address, for example "10.231.52.xxx:9091", and served on the HTTP URL '10.231.52.xxx:9091/metrics'. But it's unable to serve on '0.0.0.0:9091' and '127.0.0.1:9091'. It is therefore inconvenient to set up an onebox environment with prometheus.
This limitation can be resolved by binding to '0.0.0.0:9091' so that '0.0.0.0:9091', '127.0.0.1:9091', '10.231.52.xxx:9091' are all accessible.
Tests 

fix: bind prometheus exposer to 0.0.0.0

---

scripts/pack_server.sh
src/reporter/pegasus_counter_reporter.cpp
src/server/pegasus_write_service.cpp
src/server/pegasus_write_service.h
src/server/test/pegasus_mutation_duplicator_test.cpp

We need to know the time lag between master and slave.  So in this PR, I added two perf-counters:
- `replica*app.pegasus*dup.time_lag_ms@<app_name>`
The time lag between master and slave. A write to master will first record a timestamp (`ts1`) before running 2PC. Then when it duplicates to the slave and applies to the slave's rocksdb (`ts2`), this counter will calculate the duration between the two timestamps.
We can set an alert for this metric in order to detect failures on duplication. 
- `replica*app.pegasus*dup.lagging_writes@<app_name>`
A write with time lag larger than `dup_lagging_write_threshold_ms` is defined as a "lagging write".
This counter calculates the number of such lagging writes.
- [pegasus.server] dup_lagging_write_threshold_ms
Tests 
- Manual test (add detailed …

feat(dup): add metric for time lag between master&slave

---

src/server/pegasus_event_listener.cpp
src/server/pegasus_event_listener.h
src/server/pegasus_server_impl_init.cpp

Pegasus has metrics for rocksdb write-stalls, but no logging for which replica that was stalled.
So even we have been alerted for this event, we are not able to improve the situation. 
I add logs for each rocksdb write stall, including delayed and stopped.
Tests 

improvement: add logging on rocksdb write stalls

---

src/server/result_writer.cpp

To store capacity unit data we create a table (by config `[pegasus.collector] usage_stat_app`) for each Pegasus cluster. The data is currently stored without TTL, which means no space limit on the "usage_stat_app".
I add a configuration called 'capacity_unit_saving_ttl_days', each capacity unit data will expire after this period.
```diff
[pegasus.collector]
+ capacity_unit_saving_ttl_days = 90
```
Tests 
```
>>> use stat
OK
>>> full_scan -n 1
partition: all
hash_key_filter_type: no_filter
sort_key_filter_type: no_filter
value_filter_type: no_filter
max_count: 1
timout_ms: 5000
detailed: false
no_value: false
"2020-05-10 21:01:54" : "cu@10.232.52.147:34801" => "{\"2\":[9,9]}"
1 key-value pairs got.
>>> ttl "2020-05-10 21:01:54" …
```

improvement(cu): set ttl on capacity unit data

---

src/server/meta_store.cpp
src/server/meta_store.h
src/server/pegasus_server_impl.cpp

After https://github.com/XiaoMi/pegasus/pull/494, we have written meta info into both manifest and meta CF, and meta info is read from manifest all the same, if we want to read from meta CF, we have to modify code and pack a new release version.
This patch make meta info read source into config file, it's more convenient for testing and transit to use original rocksdb.
No functional changes.

feat(rocksdb): Support to config meta data read source

---

src/server/info_collector.cpp

if you do like this, there will be a core dump.
```bash
create aaa -p 8 -r 3
drop aaa
create aaa -p 16 -r 3
```
Because the previous design cannot change the number of partitions of table after the Collector starts.
And now I store a hotspot_calculator named `app_name+partition_num`

fix: fix bug in table_hotspot_policy

---

src/shell/sds/sds.c

Potential use of NULL pointer.
Check for NULL before `memset()`.

fix(shell/sds): NULL check before memset

---

src/test/function_test/test_restore.cpp

In restore test, it looks for the second backup timestamp to see if the first backup is complete.
But it doesn't take the `args`, which means the directory of block service, into accout.
So if we set `args`(like https://github.com/XiaoMi/pegasus/pull/534 shows), it can't find the second backup timestamp, and result in a timeout.
Tests 
- Unit test
Code changes

fix: fix bug in function_test/test_restore

---

src/shell/command_helper.h
src/shell/commands.h
src/shell/commands/node_management.cpp
src/shell/commands/table_management.cpp
src/test/kill_test/CMakeLists.txt
src/test/kill_test/partition_kill_testor.cpp
src/test/kill_test/partition_kill_testor.h

https://github.com/XiaoMi/rdsn/pull/473 refactored the remote command APIs. This PR adapts our code to the new API.
Tests 
I tested the shell commands: 'nodes -u' and 'app_stat'. The results show perfectly.

refactor: adapt to rdsn dist cmd refactoring

---

src/base/pegasus_rpc_types.h
src/server/config.ini
src/server/config.min.ini
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_server_write.cpp
src/server/pegasus_write_service.cpp
src/server/pegasus_write_service.h
src/server/pegasus_write_service_impl.h

This pull request is about how pegasus handle ingestion request.
Ingestion request is considered as a write request, but it is different from normal write request. Normal write request will not only write data but also write decree into rocksdb, but rocksdb ingestion won't write decree, so we should write an empty put to flush decree before execute ingestion. Besides, ingestion is time-consuming, it should not be executed in replication thread pool, so ingestion will execute in ingestion thread pool asynchronously, the result of ingestion will be got by ingestion_status. Before rocksdb do actual ingestion, we should verify files again.

feat(bulk-load): bulk load ingestion part3 - execute ingestion

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

[Pegasus 2.0](https://github.com/XiaoMi/pegasus/issues/536) has released many new features, as well as many code refactors and bugfixes since the previous release version [1.12.3](https://github.com/XiaoMi/pegasus/releases/tag/v1.12.3). And more important, 2.0 will introduce some uncompatible features, such as update rocksdb from 5.9.2 to 6.6.4, update 'pegasus data version' from 0 to 1, etc.
This patch provide an effort for Pegasus 1.x to be forward compatible with 2.0. When upgrade Pegasus server from 1.x to 2.0 and find some bugs in 2.0, you can downgrade Pegasus to this version.
**NOTE**: 
- Pegasus version (let's suppose it is 1.12.4) with this patch is forward compatible with 2.0.0
- Pegasus 1.12.3 and lower versions are not forward compatible with this patch!!!
Tests 
- Manual test …

feat(rocksdb): Support to open rocksdb with or without meta CF

---

src/server/pegasus_read_service.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/test/pegasus_server_impl_test.cpp

This PR plans to replace `rpc_replier` to `rpc_holder` in `pegasus_server_impl`
just a refactor

refactor: use rpc_holder to receive RPC in pegasus_server_impl

---

src/server/meta_store.cpp
src/server/meta_store.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

Ref: https://github.com/XiaoMi/pegasus/issues/468
We have store meta data(Pegasus data version, last manual compact timestamp, decree) both in RocksDB's manifest and meta column family in version [2.0.0](https://github.com/XiaoMi/pegasus/releases/tag/v2.0.0), now we are going to read meta data from meta CF instead of manifest.
Main changes of this PR:
- Validate meta CF existence when DB exist (means only allowed to upgrade from 2.0)
- Read meta data from meta CF
- Do checkpoint by rocksdb's original APIs.
**NOTE:** Since meta data is still wrote into manifest, so there is no compatibility problems with 2.0.0.
No user faced changes.
Tests 
1. Upgrade from 1.x.x
Will fail, only allowed from version 2.0.x
2. Upgrade from 2.0.0
- Deploy a …

feat(rocksdb): Use original CreateCheckpoint and read meta data from meta CF

---

src/server/meta_store.cpp
src/server/meta_store.h
src/server/pegasus_server_impl_init.cpp
src/server/pegasus_write_service_impl.h

Use official RocksdDB
Tests 
Test compatibility with 2.0.0:
Code changes
No
No
No
Yes.
Meta data (Pegasus data version, last manual compact finish timestamp, dcree) will **NOT** write to RocksDB's manifest anymore.
Side effects
No
No
**Upgrade:**
1.x -> this version: forbidden (server will core)
2.0 -> this version: compatible
**Downgrade:**
this version -> 1.x: forbidden (server will run with error, table can not be healthy, cause 1.x can't open RocksDB with multi-CFs)
this version -> 2.0: partial compatible, …

feat(rocksdb): Remove all calls of Pegasus introduced APIs on RocksDB

---

src/client_lib/CMakeLists.txt
src/server/CMakeLists.txt
src/server/test/CMakeLists.txt
src/shell/CMakeLists.txt
src/test/function_test/CMakeLists.txt
src/test/function_test/global_env.cpp
src/test/function_test/global_env.h
src/test/kill_test/CMakeLists.txt
src/test/upgrade_test/CMakeLists.txt

1.change lib name: In the refactors of rdsn, some lib name were changed. for example: name of client lib is changed from `dsn.repliation.ddlclient` to `dsn.client`, etc. so in pegasus,  we should change it synchronously.
2.use `dsn::utils::singleton` to refactor `global_env`

refactor: modify the dependent lib name which are generated by rdsn

---

src/base/test/CMakeLists.txt
src/client_lib/CMakeLists.txt
src/geo/bench/CMakeLists.txt
src/geo/test/CMakeLists.txt
src/redis_protocol/proxy_lib/CMakeLists.txt
src/server/CMakeLists.txt
src/server/test/CMakeLists.txt
src/shell/CMakeLists.txt
src/test/bench_test/CMakeLists.txt
src/test/function_test/CMakeLists.txt
src/test/kill_test/CMakeLists.txt
src/test/pressure_test/CMakeLists.txt
src/test/upgrade_test/CMakeLists.txt

In pr https://github.com/XiaoMi/rdsn/pull/517, we make utils decoupled from dsn_runtime. So in pegasus, we should add the depend of dsn_utils implicitly.

refactor: add the dependend lib which name is dsn_utils

---

src/server/meta_store.cpp

Compile failed as follow env:
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
cmake version 3.5.2
```
/home/jiashuo1/work/pegasus/src/server/meta_store.cpp: In static member function ‘static dsn::error_code pegasus::server::meta_store::get_value_from_meta_cf(rocksdb::DB*, rocksdb::ColumnFamilyHandle*, bool, const string&, uint64_t*)’:
/home/jiashuo1/work/pegasus/DSN_ROOT/include/dsn/c/api_utilities.h:90:78: error: cannot pass objects of non-trivially-copyable type ‘const string {aka const class std::basic_string<char>}’ through ‘...’
dsn_logf(__FILENAME__, __FUNCTION__, __LINE__, level, __VA_ARGS__);                    \
^
/home/jiashuo1/work/pegasus/DSN_ROOT/include/dsn/c/api_utilities.h:101:13: note: in expansion of macro ‘dlog’
dlog(LOG_LEVEL_FATAL, __VA_ARGS__); …
```

fix: compile failed under the "g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)"

---

src/shell/commands/bulk_load.cpp

This pull request implement query bulk load, this command support following ways to query bulk load status:
- `query_bulk_load_status -a <table_name>`: only show app bulk load status and total download progress if during downloading
-  `query_bulk_load_status -a <table_name> -i <pidx>`: only show app and partition bulk load status and total download progress if during downloading
-  `query_bulk_load_status -a <table_name> -d`: show app bulk load status and all partitions bulk load status
-  `query_bulk_load_status -a <table_name> -i <pidx> -d`: show specific partition bulk load status
**1. app is not executing bulk load**
```
>>> query_bulk_load_status -a temp -d
query bulk load failed, error=ERR_INVALID_STATE [hint:"app(temp) is not during bulk load"]
```
**2. query app summary status** …

feat(bulk-load): add query bulk load shell command

---

src/server/info_collector.cpp
src/server/table_hotspot_policy.h
src/server/test/pegasus_tablehotspot_test.cpp

This algorithm cannot support hotkey detection, so I decide to delete it.

fix: delete outdated algorithm of table_hotspot_policy

---

src/server/info_collector.cpp

This PR changes construction parameters of hotspot_calculator, it won't change the function of origin code, but it is helpful for hotkey detection.

fix: change the construction parameters of hotspot calculator

---

.asf.yml
.github/workflows/ci-pull-request-title.yaml

What is semantic pull request: https://github.com/zeke/semantic-pull-requests.
We used to manage it as a third-party [probot](https://probot.github.io/). It requires authorization from the code owner, which is now transferred to ASF. To not bother requesting from them, I manage this tool as a GitHub Action, which could be triggered every PR.
I add a workflow under .github/workflows/ci-pull-request-title.yml. This config is copied from https://github.com/amannn/action-semantic-pull-request.
Tests 
- No code

build(ci): add asf.yml file and github action for semantic commits

---

DISCLAIMER-WIP
NOTICE

Because headers in Pegasus are still copy-righted to XiaoMi, we are not compliant with ASF policy now.
Thus to be able to release the incoming version, we must disclaim that the ip-clearance is still working on.
http://www.apache.org/legal/release-policy.html
I add a DISCLAIMER-WIP file under root dir.
Tests 
- No code

chore: add disclaimer for not compliant with asf policy

---

src/server/meta_store.cpp
src/server/meta_store.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/test/pegasus_server_impl_test.cpp

#571 
RocksDB database automatically persisted its current set of options into a file since RocksDB 4.3[1], 
so when DB exists, we should open the rocksdb instance using the options file stored in the db directory.
This patch also adds usage scenario into meta column family to initialize `_usage_scenario`.
[1] https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File
Tests 
- Unit test
Code changes
Side effects

fix: Load options from file when open an exist DB

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

When we reopen an existing db, we will use latest option file to construct options. However,
if this file is an old version file which has incompatible options with official rocksdb, we would
get an error and fail to open db.
https://github.com/apache/incubator-pegasus/blob/ae7caa2599357f83cbbf79c4367a5d0a72f04288/src/server/pegasus_server_impl.cpp#L1341-L1349
If the option file has known incompatible options `pegasus_data_version` and `pegasus_data`,
we skip loading options from file and use default options to open db.
A new version option file will be generated when we succeed to open db, after that we could use
existing option file to construct options. That means the first time we open an old version db, we
must use default options, and that may lead to unexpected flushes and …

fix: Use default options to open db when latest option file has incompatible db options

---

src/server/info_collector_app.cpp
src/server/info_collector_app.h

In pervious, the info collector use the way of `new ::dsn::http_server()` to start http server. But it will produce a compile error, since the pr(https://github.com/XiaoMi/rdsn/pull/610) in rdsn change the way to start http server.

fix(http): change the way to start http server

---

src/server/pegasus_write_service_impl.h
src/server/test/pegasus_write_service_impl_test.cpp

https://github.com/apache/incubator-pegasus/pull/598 introduced a bug, which makes incr continue to proceed even the rocksdb::get failed.
This PR fixes this bug and adds some unit tests using fail-point library to mock rocksdb get failure.
Tests 
- Unit test

fix: bugfix on incr

---

.asf.yml

The notification of pull-requests is currently automatically sent to dev@pegasus.apache.org. They are with less priority but usually with large amounts. So I in this PR move them to commits@pegasus.apache.org. For the convenience of mail filtering.
See this doc:
https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
Tests 
- No code

chore: move github pullrequests to commits mail-list

---

src/server/capacity_unit_calculator.cpp
src/server/capacity_unit_calculator.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_write_service.cpp
src/server/test/capacity_unit_calculator_test.cpp

hotkey capturing is executed in `capacity_unit_calculator`.
Both `capture_raw_key` and `capture_hash_key` have two params: `key` `weight`
`key`: raw_key or hash_key
`weight`: In some scenarios, some keys will be counted several times, we can capture these keys just one time.

feat(hotkey): add an interface of hotkey capture

---

src/server/pegasus_server_impl.cpp

In fuction multi_get,  there is a statistical error in result size, which is used for logging. So this pr fix this bug.
Tests 
1. change to print the log when a multi_get request is coming.
2. send a multi_get request to onebox
```
>>> use temp
OK
>>> set a b c
OK
decree          : 1
>>> multi_get a
"a" : "b" => "c"
1 key-value pairs got, fetch completed.
```
3. grep the abnormal log, the result_size is not 0.
```
➜  onebox git:(log-bug) ✗ grep -rn -I "abnormal" .
./replica3/data/log/log.1.txt:877:W2020-12-08 12:04:32.4495 (1607400272449200763 13bb) …
```

fix: fix log bug in multi_get

---

src/server/pegasus_write_service_impl.h

use rocksdb_wrapper::get to reimplement `check_and_set`.
Tests 
There are a lot of function tests in `test_check_and_test.cpp`.
```
>>> use temp
OK
>>> check_and_set a -c b -t exist -s b1 -v c1 -r
hash_key: "a"
check_sort_key: "b"
check_type: exist
set_sort_key: "b1"
set_value: "c1"
set_value_ttl_seconds: 0
return_check_value: true
Set failed, because check not passed.
Check value not exist.
decree          : 16
>>> set a b c
OK
decree          : 17
>>> get a b
"c"
>>> check_and_set a -c b -t exist -s b1 -v …
```

refactor: use rocksdb_wrapper::get to reimplement check_and_set

---

src/server/pegasus_write_service_impl.h

use rocksdb_wrapper::get to reimplement `check_and_mutate`.
Tests 
There are a lot of function tests in `test_check_and_mutate.cpp`.
```
>>> use temp
OK
>>> exist a b 
False
>>> check_and_mutate a -c b -t exist -r
Load mutations, like
set <sort_key> <value> [ttl]
del <sort_key>
Print "ok" to finish loading, "abort" to abort this command
>>> set b1 c1
LOAD: set sortkey "b1", value "c1", ttl 0
>>> set b2 c2
LOAD: set sortkey "b2", value "c2", ttl 0
>>> ok
INFO: load mutations done.
hash_key: "a"
check_sort_key: "b"
check_type: exist
return_check_value: true
mutations:
mutation[0].type: SET
mutation[0].sort_key: "b1"
mutation[0].value: "c1" …
```

refactor: use rocksdb_wrapper::get to reimplement check_and_mutate

---

src/server/config.ini
src/server/config.min.ini
src/shell/commands/bulk_load.cpp
src/shell/main.cpp
src/test/function_test/test_bulk_load.cpp

rdsn [686](https://github.com/XiaoMi/rdsn/pull/686) support user-defined remote file provider root path, this pr update shell command and tests, and remove useless `bulk_load_provider_root` in config file.

feat(bulk_load): add remote_file_root for start_bulk_load_request

---

config_hdfs.sh
scripts/travis.sh

Add config_hdfs.sh to help users set `LD_LIBRARY_PATH` and `CLASSPATH` when running
pegasus binaries which use libhdfs.
- Add config_hdfs.sh
Tests 
Build and run pegasus with libjvm.so directory not set in `LD_LIBRARY_PATH`

chore: add config_hdfs.sh

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

As [rdsn#706](https://github.com/XiaoMi/rdsn/pull/706) shows, this pr implement query data_version.

feat: add query app data_version

---

src/server/pegasus_write_service_impl.h

use rocksdb_wrapper::write_batch_put to reimplement incr
There are a lot of function tests in `test_incr.cpp.`
```
>>> use temp
OK
>>> incr a b 0
0
decree          : 5
>>> get a b 
"0"
>>> incr a b 1
1
decree          : 6
>>> get a b 
"1"
>>> incr a b 5
6
decree          : 7
>>> get a b 
"6"
server          : …
```

refactor: use rocksdb_wrapper::write_batch_put to reimplement incr

---

src/server/pegasus_write_service_impl.h

use `rocksdb_wrapper::write_batch_put_ctx` to reimplement multi_put.
```
>>> use temp
OK
>>> ls -d
[general_info]
app_id  status     app_name  app_type  partition_count  replica_count  is_stateful  create_time          drop_time  drop_expire  envs_count  
1       AVAILABLE  stat      pegasus   4                3              true         2020-12-31_14:40:35  -          -            0           
2       AVAILABLE  temp      pegasus   8                3              true         2020-12-31_14:40:35  -          -            0           
[healthy_info]
app_id  app_name  partition_count  fully_healthy  unhealthy  write_unhealthy  read_unhealthy  
1       stat      4                4              0          0                0               
2 …
```

refactor: use rocksdb_wrapper::write_batch_put_ctx to reimplement multi_put

---

src/server/pegasus_mutation_duplicator.cpp
src/server/pegasus_write_service_impl.h
src/server/rocksdb_wrapper.cpp
src/server/rocksdb_wrapper.h

move write_batch_delete into rocksdb_wrapper, and use it to reimplement `multi_remove`
```
>>> use temp
OK
>>> multi_set hash sort1 value1 sort2 value2 sort3 value3 sort4 value4
OK
decree          : 9
>>> multi_get hash
"hash" : "sort1" => "value1"
"hash" : "sort2" => "value2"
"hash" : "sort3" => "value3"
"hash" : "sort4" => "value4"
4 key-value pairs got, fetch completed.
>>> multi_del hash sort1
1 key-value pairs deleted.
decree          : 10
>>> multi_get hash
"hash" : "sort2" => "value2"
"hash" : "sort3" …
```

refactor: move write_batch_delete into rocksdb_wrapper

---

src/server/pegasus_write_service_impl.h

use rocksdb_wrapper to reimplement `empty_put`
Tests 
- Unit test
There are some unit tests in `pegasus_write_service_test.cpp` to test `empty_put`
Use incr to trigger empty_put
```
>>> use temp
OK
>>> set a b c
OK
decree          : 1
>>> incr a b 1
ERROR: invalid argument
decree          : 2
>>> incr a b 1
ERROR: invalid argument
decree          : 3
>>> incr a b 5
ERROR: invalid argument
decree          : 5
```

refactor: use rocksdb_wrapper to reimplement empty_put

---

src/server/pegasus_write_service_impl.h

use rocksdb_wrapper to reimplement check_and_mutate
Tests 
There are a lot of function tests in `test_check_and_mutate.cpp`.
```
>>> use temp
OK
>>> exist a b 
False
server          : 10.232.55.210:34803
>>> check_and_mutate a -c b -t exist -r
Load mutations, like
set <sort_key> <value> [ttl]
del <sort_key>
Print "ok" to finish loading, "abort" to abort this command
>>> set b1 c1
LOAD: set sortkey "b1", value "c1", ttl 0
>>> set b2 c2
LOAD: set sortkey "b2", value "c2", ttl 0
>>> ok
INFO: load mutations done.
hash_key: "a"
check_sort_key: "b"
check_type: exist
return_check_value: true
mutations:
mutation[0].type: SET
mutation[0].sort_key: "b1"
mutation[0].value: "c1"
mutation[0].expire_seconds: 0 …
```

refactor: use rocksdb_wrapper to reimplement check_and_mutate

---

src/server/pegasus_write_service_impl.h
src/server/rocksdb_wrapper.cpp
src/server/rocksdb_wrapper.h

move func ingestion_files to rocksdb_wrapper
Tests 
There are some function tests in `test_bulk_load.cpp`

refactor: move func ingestion_files to rocksdb_wrapper

---

src/server/test/pegasus_write_service_impl_test.cpp

I will remove `write_batch_put` and `write_batch_put_ctx` in pegasus_write_service_impl.h. And there are tests in rocksdb_wrapper_test.cpp to test `rockdb_wrapper::write_batch_put` and `rocksdb_wrapper::write_batch_put_ctx`, which are substitutes for the functions with same name in pegasus_write_service_impl.h. So the unit tests in pegasus_write_service_impl_test  for `pegasus_write_service::impl::write_batch_put` and `pegasus_write_service::impl::write_batch_put_ctx` are useless.
Tests 
- No code

refactor: remove unused unit tests in pegasus_write_service_impl_test

---

src/server/pegasus_write_service_impl.h
src/server/rocksdb_wrapper.cpp
src/server/rocksdb_wrapper.h
src/server/test/pegasus_server_write_test.cpp
src/server/test/pegasus_write_service_impl_test.cpp
src/server/test/pegasus_write_service_test.cpp

use rocksdb_wrapper to reimplement batch operations
Tests 
```
>>> use temp
OK
>>> set a c b
OK
decree          : 4
>>> get a c 
"b"
>>> del a c 
OK
decree          : 31
>>> get a c 
Not found
```

refactor: use rocksdb_wrapper to reimplement batch operations

---

src/server/pegasus_server_write.cpp
src/server/pegasus_server_write.h

reimplement pegasus_server_write::on_batched_write_requests
Tests 
- Manual test
```
>>> ls
[general_info]
app_id  status     app_name  app_type  partition_count  replica_count  is_stateful  create_time          drop_time  drop_expire  envs_count  
1       AVAILABLE  stat      pegasus   4                3              true         2021-01-13_11:14:51  -          -            0           
2       AVAILABLE  temp      pegasus   8                3              true         2021-01-13_11:14:51  -          -            0           
[summary]
total_app_count  : 2
>>> use temp
OK
>>> multi_set a b1 c1 b2 c2
OK
decree          : 1
>>> get a b1
"c1"
server          : …
```

refactor: reimplement pegasus_server_write::on_batched_write_requests

---

src/base/pegasus_utils.h

```
/home/wutao1/git/pegasus/src/base/test/../pegasus_utils.h:65:32: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
65 |         return std::move(result);
|                                ^
/home/wutao1/git/pegasus/src/base/test/../pegasus_utils.h:65:32: note: remove ‘std::move’ call
```

fix: compilation error in pegasus_utils

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

As rdsn pr [729](https://github.com/XiaoMi/rdsn/pull/729) shows, this pr add an option flush_memtable for function `copy_checkpoint_to_dir`. If `flush_memtable=true`, it will flush memtable before create a checkpoint, otherwise, not flush memtable.

fix(split): add flush_memtable for copy_checkpoint_to_dir

---

.github/workflows/ci-pull-request.yaml
scripts/pack_server.sh
src/server/config.min.ini

Problem:
https://github.com/pegasus-kv/pegasus-docker/runs/1999116228?check_suite_focus=true
Only ubuntu1804 failed on the master branch. It's because the package script uses an invalid function.

fix: package script on ubuntu1804

---

src/base/test/config.ini
src/geo/bench/config.ini
src/geo/test/config.ini
src/redis_protocol/proxy/config.ini
src/redis_protocol/proxy_ut/config.ini
src/sample/config.ini
src/server/test/config.ini
src/shell/config.ini
src/test/bench_test/config.ini
src/test/function_test/config.ini
src/test/kill_test/config.ini
src/test/pressure_test/config-pressure.ini
src/test/upgrade_test/config.ini

In rdsn(https://github.com/XiaoMi/rdsn/pull/778), we decoupled aio from dsn runtime. And make the config `aio_factory_name` unused. So in this pr, I remove the unused config `aio_factory_name` in each *.ini file
```diff
-  aio_factory_name
```
Tests 
- No code

refactor: delete unused config aio_factory_name

---

rfcs/2021-02-22-disk-migrater.md
rfcs/2021-02-22-disk-migrator.md

* support disk migration rpc request(`RPC_REPLICA_DISK_MIGRATE`)  and check whether the request is valid. https://github.com/XiaoMi/rdsn/pull/660
* add `migrate_replica` to support migrate origin data https://github.com/XiaoMi/rdsn/pull/664
* close origin replica and update replica dir https://github.com/XiaoMi/rdsn/pull/668
- add node, disk, server, remote-command related command https://github.com/pegasus-kv/admin-cli/pull/1
- refactor the disk info and support resolve host name  https://github.com/pegasus-kv/admin-cli/pull/8

doc: add disk-migrater rfc 

---

.github/workflows/ci-pull-request.yaml
scripts/pack_common.sh

Some environments may build pegasus with less dependencies than we expected. For example, we assume that ubuntu18.04 must require icui18n icuuc icudata, but with image [pegasus-kv/thirdparties-bin:ubuntu1804](https://github.com/orgs/pegasus-kv/packages/container/thirdparties-bin/1553681) I found it always builds without linking these libs. So when we package pegasus, the script will fail if it can't find them in the system path (apt-get doesn't find this package). This is annoying and needs endless fixes.
I add a check before packaging a lib, if it's not required, the script prints an error log and goes on.
```
'./scripts/sendmail.sh' -> 'pegasus-server-2.1.SNAPSHOT-eca50e0-glibc2.27-release/bin/sendmail.sh'
'./src/server/config.ini' -> …
```

fix(scripts): skip packaging irrelevant libs

---

src/base/pegasus_const.cpp
src/base/pegasus_const.h
src/base/pegasus_key_schema.h
src/server/config.min.ini
src/server/key_ttl_compaction_filter.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

If app's `validate_partition_hash=true`, it will check partition_hash when execute rocksdb compaction, to gc old data during partition split.

feat(split): gc useless data after partition split

---

src/base/test/CMakeLists.txt
src/client_lib/CMakeLists.txt

Because [rdsn#778](https://github.com/XiaoMi/rdsn/pull/778) made `dsn_aio` decoupled from `dsn_runtime`,
we don't need to link `dsn_aio` to client and test libraries.
revert changes in src/base/test/CMakeLists.txt and src/client_lib/CMakeLists.txt.
Tests 
- Unit test

revert: do not link dsn_aio to client and test libraries

---

src/server/info_collector.cpp
src/server/info_collector.h
src/server/table_stats.h
src/shell/command_helper.h
src/shell/commands/table_management.cpp

add read rate limiter perfcounter in info collector
Tests 
1. start onebox
2. set read limiter for table `stat` to a little value, such as '1*reject*100'
3. read table `stat` repeatly
4. the perf counter of read reject count is not zero:
```
2405:[collector*app.pegasus*app.stat.recent_read_throttling_reject_count#stat, NUMBER, 6.00]
```

feat: add read rate limiter perfcounter in info collector

---

src/shell/commands/cold_backup.cpp
src/test/function_test/test_restore.cpp

[rdsn#716](https://github.com/XiaoMi/rdsn/pull/716) remove 'policy_name' from backup files' path, we don't need to specify `policy_name` when restore a table which is backed up after this change.
Make `old_policy_name` an optional parameter in shell, when we want to restore an old table, we still need to add `-p <old_policy_name>`, otherwise `old_policy_name` could be an empty string.
Tests 
- Funtion test
I ran `test_restore` test on my local cluster successfully.

fix(restore): make 'old_policy_name' an optional parameter

---

src/shell/commands/table_management.cpp

```
>>> app_stat
F2021-04-07 16:11:32.546 (1617783092546521940 16004)  mimic.io-thrd.16004: output_utils.cpp:150:append_string_data(): assertion expression: last_index <= _max_col_width.size()
F2021-04-07 16:11:32.546 (1617783092546549469 16004)  mimic.io-thrd.16004: output_utils.cpp:150:append_string_data(): column data exceed
```
https://github.com/apache/incubator-pegasus/pull/705 This PR appends two columns to `app_stat`. But they don't have a column title. So when they are appended, the shell coredumped.
This PR removes the incorrect two columns.
Manually call `app_stat`, everything works.

fix: shell app_stat removes unexpected columns

---

scripts/pegasus_add_node_list.sh
scripts/pegasus_offline_node_list.sh
scripts/pegasus_rebalance_cluster.sh

default nfs copy rate is not appropriate when add/offline node
- update  `pegasus_add_node_list.sh` support pass `replica.nfs.max_copy_rate_megabytes`(**default 200**) 
- update  `pegasus_offline_node_list.sh` support pass `replica.nfs.max_copy_rate_megabytes`(**default 100**) 

refactor: update default nfs copy rate when add_node_list and offline_node_list

---

src/shell/command_helper.h

add incr_qps and duplicate_qps to total_write_qps
1. start onebox
2. do incr operation in app "temp" repeatly
3. the perf counter of write qps for _all_ is not zero
```
[collector*app.pegasus*app.stat.incr_qps#temp, NUMBER, 2.00]
[collector*app.pegasus*app.stat.write_qps#_all_, NUMBER, 2.00]
```

fix: add incr_qps and duplicate_qps to total_write_qps

---

src/test/function_test/run.sh
src/test/function_test/test_backup_and_restore.cpp

Add  one-time backup function tests.
- Fuction test : test backup and restore using `local_service`
- Has exported new tests

feat(test): add one-time backup function tests

---

src/base/pegasus_value_schema.h
src/base/test/value_manager_test.cpp
src/base/test/value_schema_test.cpp
src/base/value_schema_manager.cpp
src/base/value_schema_v0.cpp
src/base/value_schema_v0.h
src/base/value_schema_v1.cpp
src/base/value_schema_v1.h

proposal https://github.com/apache/incubator-pegasus/blob/master/rfcs/2020-10-09-data-version-v3.md
implement value_schema_v1, which represents data version 1.
- Unit test

refactor: implement value schema 1

---

src/base/pegasus_value_schema.h
src/base/test/value_manager_test.cpp
src/base/test/value_schema_test.cpp
src/base/value_schema_manager.cpp
src/base/value_schema_v2.cpp
src/base/value_schema_v2.h

proposal https://github.com/apache/incubator-pegasus/blob/master/rfcs/2020-10-09-data-version-v3.md
implement value_schema_v2, which represents data version 2.
The format of data version 2:
```
|- 1bit -|- version(7bits) -|- expire_ts(4bytes) -|- timetag(8 bytes) -|- user value(bytes) -|
```
- Unit test

feat: implement data version 2

---

src/server/config.min.ini
src/server/hotspot_partition_calculator.cpp
src/server/hotspot_partition_calculator.h
src/server/test/hotspot_partition_test.cpp

This PR adds a new perf_counter to show the count of hotspots in one table, it can help us intuitively find the hotspot in the cluster.
```
[collector*app.pegasus*app.stat.hotspots.temp.write.total, NUMBER, 2.00]
```
this perf_counter means in app `temp` has a hotspot in 2 partition

feat(hotspot): add a cluster level perf_counter to display hotspot

---

src/server/compaction_filter_rule.cpp
src/server/compaction_filter_rule.h
src/server/test/CMakeLists.txt
src/server/test/compaction_filter_rule_test.cpp

feat: add hashkey pattern rule

---

run.sh

Since we've supported portable building for rocksdb in rdsn (https://github.com/XiaoMi/rdsn/pull/690), we should also support this feature in the building for pegasus.
As we've discussed in https://github.com/XiaoMi/rdsn/pull/690, supporting this feature is for the purpose of doing some functional tests or running a sample service on a non-portable node where pegasus server will exit abnormally with `Illegal instruction (core dumped)`. For the performance-critical scenarios, such as production environment, it is better to build pegasus with non-portable mode(default mode), which will make full use of the optimization for the particular platform.
To build pegasus on the portable mode, do `./run.sh build --enable_rocksdb_portable [some other options ...]`. By default, without …

feat: support to build a portable rocksdb binary

---

src/server/info_collector.cpp
src/server/info_collector.h
src/shell/command_helper.h
src/shell/commands/table_management.cpp

add perf counter for backup request limiter.  Related issue: https://github.com/apache/incubator-pegasus/issues/778
1. `set_app_envs replica.backup_request_throttling 1*delay*100`
2. send read request to server with backup request
3. log shows that the backup request is delayed: `[collector*app.pegasus*app.stat.recent_backup_request_throttling_delay_count#_all_, NUMBER, 4.00]`
4.  `set_app_envs replica.backup_request_throttling 1*reject*100`
5. send read request to server with backup request
6. log shows that the backup request is rejected: `[collector*app.pegasus*app.stat.recent_backup_request_throttling_reject_count#_all_, NUMBER, 66.00]`

feat: add perf counter for backup request limiter

---

scripts/pegasus_rolling_update.sh

rolling update cluster may cause `learn with copy checkpoint` to new node if updating node is unhealthy for a `long time`,  which will impact on cluster availability.  `the long time` threshold actually is `meta.lb.assign_delay_ms`. 
```
D2021-07-15 16:10:32.947 (1626336632947688521 14680)   meta.meta_state0.0201000000000018: server_load_balancer.cpp:706:on_missing_secondary(): gpid(10.1): is emergency due to lose secondary for a long time, last_dropped_node(.......:54801), drop_time(2021-07-15 16:00:32.857), delay_ms(600000)
D2021-07-15 16:10:32.947 (1626336632947702632 14680)   meta.meta_state0.0201000000000018: server_load_balancer.cpp:726:on_missing_secondary(): gpid(10.1): try to choose node in dropped list, dropped_list(....:54801), prefered_dropped(0)
D2021-07-15 16:10:32.947 …
```

fix(script): increase the assign-delay time

---

src/server/info_collector.cpp
src/server/info_collector.h
src/shell/command_helper.h

See https://github.com/XiaoMi/rdsn/pull/862, this pr support table level `dup_recent_mutation_loss_count` perfcounter
```diff
+ collector*app.pegasus*app.stat.dup_recent_mutation_loss_count#{table_name}
```

feat: support dup_recent_mutation_loss_count perf-counter

---

src/base/pegasus_const.cpp
src/base/pegasus_const.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

Sometimes, there are some apps of different business in a cluster.Some apps  want to enable block cache, others my be not.
So we need add an env to enable or disable block cache of an app.

feat: add an env to enable or disable block cache of an app

---

src/server/pegasus_server_write.cpp

use reference to catch exception, to avoid build error.
1. send a dirty request by java client
2. and we can see there is a log about it
```
E2021-08-02 10:04:42.28 (1627869882028274338 6762) replica.replica0.0304000000000098: pegasus_server_write.cpp:115:on_batched_writes(): [2.4@{ip}:{port}] pegasus batch writes handler failed, from = {ip}:{port}, exception = no more data to read after end-of-buffer
```

fix: use reference to catch exception

---

src/server/info_collector.cpp
src/server/info_collector.h
src/shell/command_helper.h
src/shell/commands/table_management.cpp

This pull requests add the table-level rejecting read/write requests count during partition split.
```
collector*app.pegasus*app.stat.recent_write_splitting_reject_count#[table_name] - VOLATILE_NUMBER
collector*app.pegasus*app.stat.recent_read_splitting_reject_count#[table_name]  - VOLATILE_NUMBER
```
Tests in onebox

feat(split): add table level split reject counters

---

src/server/info_collector.cpp
src/server/info_collector.h
src/shell/command_helper.h
src/shell/commands/table_management.cpp

This pull requests add the table-level rejecting read/write requests count during bulk load ingestion.
```
collector*app.pegasus*app.stat.recent_write_bulk_load_ingestion_reject_count#[table_name] - NUMBER
```
Tests in onebox

feat(bulk-load): add table-level bulk load reject count

---

src/server/info_collector.cpp
src/server/info_collector.h
src/server/pegasus_event_listener.cpp
src/server/pegasus_event_listener.h
src/shell/command_helper.h

See https://github.com/apache/incubator-pegasus/issues/744
```
1. deploy to test cluster
2. start write operation
3. check the perfcounter 
```
```diff
+ collector*app.pegasus*app.stat.recent_rdb_compaction_input_bytes#{table_name}
+ collector*app.pegasus*app.stat.recent_rdb_compaction_output_bytes#{table_name}
```

feat: support table level rocksdb compaction perfcounter

---

src/server/pegasus_server_impl.cpp
src/test/function_test/run.sh
src/test/function_test/test_basic.cpp
src/test/function_test/test_range_read.cpp

As https://github.com/apache/incubator-pegasus/issues/808 shows, this pull request update the range read count.

feat: range read count enhancement

---

src/server/compaction_filter_rule.cpp
src/server/compaction_filter_rule.h
src/server/compaction_operation.cpp
src/server/compaction_operation.h
src/server/key_ttl_compaction_filter.h
src/server/pegasus_server_impl.cpp
src/server/test/compaction_filter_rule_test.cpp
src/server/test/compaction_operation_test.cpp

1. add some logs
2. remove user specified compaction if the corresponding appenv was removed
3. make user specified compaction applicable to default_ttl 
1. insert data into app 'temp'
```
>>> set hashkey sortkey value
OK
partition_index : 2
decree          : 36
server          : 10.231.57.100:34803
>>> get hashkey sortkey
"value"
partition_index : 2
server          : 10.231.57.100:34803
```
2. add user specified compaction 
```
Pegasus-AdminCli-1.1.0 » add-compaction-operation -o delete --hashkey-pattern "hashkey" --hashkey-match "perfix"
```
3. start manual compaction
```
➜  pegasus git:(fix-compaction) ✗ ./scripts/pegasus_manual_compact.sh -c 127.0.0.1:34601,127.0.0.1:34602 -a temp
```
4. get …

fix: remove user specified compaction if the corresponding appenv was removed

---

scripts/minos_common.sh

This script "pegasus_add_node_list.sh" in "/scripts/" used script "minos_common.sh", In "minos_common.sh", function "minos_bootstrap()" has an error when you are using Minos2 to operate clusters. This PR fixed the error.
When you are using "pegasus_add_node_list.sh" to operate clusters on Minos2：
```
Set meta level to steady...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./deploy bootstrap pegasus azmbcloudsrv-security --job replica --task 0
usage: deploy.py [-h] [--version] [-v VERBOSITY] [--remote_user REMOTE_USER]
{cleanup,decommission,reprocess,fetch,reconfigure,update_rackinfo,start,convert,stop,restart,show,reload,version_list,shell,pack,check,getconf,rolling_update}
...
deploy.py: error: invalid choice: …
```

fix: ops tools--minos2 have no bootstrap function

---

src/test/bench_test/benchmark.cpp
src/test/bench_test/main.cpp

when I use pegasus benchmark, I found that it can't stop. Just like this
```
➜  pegasus git:(master) ✗ ./run.sh bench
W2021-11-04 19:01:22.598 (1636023682598965061 2940) : overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX from THREAD_POOL_META_SERVER to THREAD_POOL_DEFAULT
W2021-11-04 19:01:22.598 (1636023682598998924 2940) : overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX_ACK from THREAD_POOL_META_SERVER to THREAD_POOL_DEFAULT
Init pegasus succeed
Hashkeys:       16 bytes each
Sortkeys:       16 bytes each
Values:         100 bytes each
Entries:        10000
FileSize:       1 MB (estimated)
WARNING: Assertions are enabled; benchmarks unnecessarily slow
------------------------------------------------
Statistics for write: …
```

fix: fix bug that benchmark can't exit

---

src/server/config.ini

While running the pegasus server with the default server config,  some logs will be found like:
```
overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX from THREAD_POOL_META_SERVER to THREAD_POOL_DEFAULT
overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX_ACK from THREAD_POOL_META_SERVER to THREAD_POOL_DEFAULT
...
WARNING: skip redefinition of option [threadpool.THREAD_POOL_BLOCK_SERVICE] worker_count (line 137), already defined as [threadpool.THREAD_POOL_BLOCK_SERVICE] worker_count (line 135)
```
By checking the server config, we can find:
- `THREAD_POOL_META_SERVER` that is used as a thread pool for meta is not defined in the server config below, thus related tasks are pushed to `THREAD_POOL_DEFAULT`
- There is a duplicate …

fix(config): duplicate worker_count and undefined thread pool in server config

---

scripts/pegasus_rebalance_cluster.sh
scripts/pegasus_rolling_update.sh

fix pegasus scripts bug;
1) pegasus_rolling_update.sh
Do not let the cluster perform replica learning during the upgrade process，change the meta.lb_assign_delay_ms from 30min to 3000min, Ensure transactional closure;
Added the rounds of closing replica during upgrade to ensure stable data access:
2) pegasus_rebalance_cluster.sh
Change the op_count_check_remain_times value from 1 to 3 to prevents the script from exiting before the load balancing rounds are calculated;
Tests
Manual test (Test on 1 working clusters)

feat(scripts): update rolling_update and rebalance scripts

---

src/server/pegasus_manual_compact_service.cpp
src/server/pegasus_manual_compact_service.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

As #850 shows, meta server should know the status of manual compaction.
This pull request is the part2 of the replica servers report manual compaction status to meta server, implement function `query_compact_status`.

feat(manual_compaction): replica report status part2. implement function query_compact_status

---

src/server/rocksdb_wrapper.cpp

This pull request set move_files=true for IngestExternalFileOptions. IngestExternalFileOptions is the option for ingest operation.
As RocksDB code(https://github.com/facebook/rocksdb/blob/v6.6.4/include/rocksdb/options.h#L1443) show:
> struct IngestExternalFileOptions {
> // Can be set to true to move the files instead of copying them.
> bool move_files = false;
> ...
> }
If IngestExternalFileOptions.move_files = true, ingest will move files, and its default value is false.
I did tests and found that setting move_files as true can **speed up ingestion**, more details can be found in Test section.
Target table have 32 partitions, each partition has 16G data to be ingested. In my test, all partitions will ingest at the same time:
- move_files = false, ingestion_time(s) = 420
- move_files = …

feat(bulk_load): set move_files as true while ingest files

---

src/base/pegasus_const.cpp
src/base/pegasus_const.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_server_write.cpp
src/server/pegasus_write_service.cpp
src/server/pegasus_write_service.h
src/server/pegasus_write_service_impl.h
src/server/rocksdb_wrapper.cpp
src/server/rocksdb_wrapper.h
src/shell/commands/bulk_load.cpp
src/shell/main.cpp
src/test/function_test/run.sh
src/test/function_test/test_bulk_load.cpp

As apache/incubator-pegasus#851 show, we decide to support online migration.
This pull request support it for pegasus, including:
1. Parse `allow_ingest_behind` from app->envs, and set rocksdb `allow_ingest_behind`, reference function `start` and function `update_allow_ingest_behind`.
2. Support `ingest_behind` for ingestion, reference `ingest_files` functions.
3. Update start_bulk_load cmd to support `ingest_behind`
4. Add bulk_load_ingest_behind function test

feat(online_migration): part3 - support ingestion_behind for pegasus

---

src/shell/commands/bulk_load.cpp

https://github.com/XiaoMi/rdsn/pull/1009 updates `is_bulk_loading` filed of `query_bulk_load_response` optional to support #856. 
This pull request adapt it in shell command.

fix: adapt query_bulk_load_response is_bulk_loading filed optional

---

scripts/pegasus_rebalance_cluster.sh
scripts/pegasus_update_ingest_behind.sh

As #851 show, we decide to support online migration. 
This pull request adds a script to update table envs and reopen all partitions to make rocksdb option updated.
Usage：`./scripts/pegasus_update_ingest_behind.sh <cluster-name> <cluster-meta-list> <app_name> <ingestion_behind>`
For example：
```
./scripts/pegasus_update_ingest_behind.sh onebox 127.0.0.1:34601,127.0.0.1:34602 temp false
```

feat(online_migration): part4 - add script to update table ingest_behind

---

src/server/pegasus_write_service.cpp
src/server/pegasus_write_service_impl.h

As #877 shows, move files during ingestion will speech up ingestion and decrease disk write throughput. (#864)
However, it exposes that in some error handling cases, it is possible to execute an out-dated ingestion request repeated.
In previous copy_files mode, it won't have problems, just ingest files repeatly, now is move_files mode, once ingestion is succeed, the original files doesn't exist, which will lead to unexpected ingestion failed.
This pull request adds ballot check before executing ingestion request.

fix(bulk_load): add ballot check before executing ingestion

---

src/shell/command_helper.h
src/shell/commands/data_operations.cpp
src/shell/config.ini
src/shell/main.cpp

https://github.com/apache/incubator-pegasus/issues/923
pegasus_shell copy_data use async_set write now, I want use async_multi_set improve speed sometimes
You can use pegasus_shell exec "copy_data -c cluster_name -a app_name -u"  for it
The same row show different cost from copy the same table to a new empty table. 
|  total_data_count   | row data pre hash_key | async_set (secs) | async_multi_set (secs)  |
|  ----  | ----  |----  | ----  |
| 152,354 | 1   | 8 | 16 |
| 417,408 | 4   | 29 | 11 |
| 657,950 | 50   | 32 | 9 |
| 2,079,400 | 200   | 87 | 18 |
| 1,842,400 | 800   | 399 | 19 |
| 14,374,001 | 2,000   | 631 | 131 |
You should use async_multi_set for copy when your data have multi count per hash_key.

feat: Using multi_set in shell tool to speedup data copy

---

src/server/pegasus_mutation_duplicator.cpp
src/server/pegasus_mutation_duplicator.h
src/server/test/pegasus_mutation_duplicator_test.cpp
src/shell/main.cpp

In test, batch send not need `MB`, `bytes` is ok.
```diff
[pegasus.server]
- duplicate_log_batch_megabytes = 4MB
[replication]
+ duplicate_log_batch_bytes = 4096
```
This pr need be merged after https://github.com/XiaoMi/rdsn/pull/1080 merged

fix(dup_enhancement#22): change batch send config by using rdsn config value

---

.github/workflows/ci-pull-request-issue.yaml

https://github.com/apache/incubator-pegasus/issues/869 add `issue-ref required`, but it will auto-update the title when request merge new branch of `https://github.com/apache/incubator-pegasus` to master and left bot comment. This pr fix it.
Note: if your pr is from your own repository, it will not trigger this problem

fix: update issue-ref github action title format

---

src/server/hotspot_partition_calculator.cpp

https://github.com/apache/incubator-pegasus/issues/985#issue-1251839824
当某张表 partition 为 1 时，可能导致 stat_histories_analyse 提前 return，进而 hot_points 和 _hot_points size 不一致，使得后续的 assert fail
```
D2022-05-28 06:29:48.34 (1653719388034076919 383) collector.default1.0101000000000001: compiler_depend.ts:108:stat_histories_analyse(): _partitions_stat_histories size <= 1, not enough data for calculation
F2022-05-28 06:29:48.34 (1653719388034089894 383) collector.default1.0101000000000001: compiler_depend.ts:135:update_hot_point(): assertion expression: _hot_points.size() == hot_points.size()
F2022-05-28 06:29:48.34 (1653719388034125236 383) collector.default1.0101000000000001: compiler_depend.ts:135:update_hot_point(): 1 vs 0
```
将 hot_points 的 resize 提前到函数入口处，确保其 size 和 _hot_points 的 size 一致
- Unit …

fix(collector): fix unexpected crash

---

src/server/config.ini

This is a subtask of https://github.com/apache/incubator-pegasus/issues/865.
Firstly, for details about `max_reserved_dropped_replicas` please see https://github.com/XiaoMi/rdsn/pull/1109.
As is described in https://github.com/XiaoMi/rdsn/pull/1109, cluster-level `max_replicas_in_group` has been replaced with `max_reserved_dropped_replicas`. To be consistent with `max_replicas_in_group`, `max_reserved_dropped_replicas` should be set to 0 for production environments. It should be added into server config file and set to 0. 
```diff
[meta_server]
+ max_reserved_dropped_replicas = 0
```

feat(update_replication_factor#11): add max_reserved_dropped_replicas into server config file

---

java-client/pom.xml

https://github.com/apache/incubator-pegasus/issues/992
- Unit test
- No code

ci(java-client): remove spotless dependency

---

src/server/config.ini
src/server/pegasus_server_impl_init.cpp

This PR is to solve the problem of https://github.com/apache/incubator-pegasus/issues/994. 
The replica server can run for a very long without any fault. Each instance of rocksdb will generate a lot of info logs that occupies considerable disk spaces. Thus each instance of rocksdb should clear out-dated logs themselves periodically.
We can use 3 options provided by `rocksdb::DBOptions` to restrict the size of info logs: 
- `max_log_file_size`
- `log_file_time_to_roll`
- `keep_log_file_num`
This option specifies the maximal size of the info log file.
Once the log file is larger than this option, a new info log file will be created.
If this option is set to 0, all logs will be written to one log file.");
This options specifies time for the info log file to roll (in seconds).
If this option …

feat: support to restrict the size of rocksdb info logs

---

.github/workflows/build-push-env-docker.yml
.github/workflows/thirdparty-regular-push.yml
docker/ci-env/Dockerfile
docker/pegasus-build-env/centos7/Dockerfile
docker/thirdparties-bin/Dockerfile
docker/thirdparties-src/Dockerfile
rdsn/thirdparty/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1015
The thirdparty build failed because JAVA_HOME set not correctly, and some output dir is not exist before `cp`

build: Fix build failed on some platforms

---

.asf.yaml

https://github.com/apache/incubator-pegasus/issues/1029
Currently, github actions will cost much time, it's too waste. we can disable required_linear_history to avoid re-run actions when all actions passed and the master branch has new commits.

chore(github): set required_linear_history to false

---

README.md
go-client/test.sh

https://github.com/apache/incubator-pegasus/issues/1032

chore: update some links

---

src/rdsn/src/common/replication_common.cpp

https://github.com/apache/incubator-pegasus/issues/1058
meta server conf change:
```
[meta_server]
server_list = hybrid01.com.deployoctopus-xxxx-debugbox:8170
```
1. change the configuration server_list of the meta server to fqdn:port 
2. The service can be started 
3. The related pegasus shell is running normally

feat: The conf server_list of meta_server support use fqdn:port

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/general_question.md
.licenserc.yaml

The github issue template not work after adding license header, now remove the header.
https://github.com/apache/incubator-pegasus/issues/1055

chore(github): Fix issue template not work bug

---

run.sh
src/base/pegasus_utils.cpp
src/base/pegasus_value_schema.h
src/geo/bench/bench.cpp
src/geo/lib/latlng_codec.cpp
src/rdsn/include/dsn/cpp/json_helper.h
src/rdsn/include/dsn/utility/casts.h
src/rdsn/include/dsn/utility/endians.h
src/rdsn/src/aio/aio_task.cpp
src/rdsn/src/block_service/test/fds_service_test.cpp
src/rdsn/src/client/partition_resolver_simple.cpp
src/rdsn/src/client/replication_ddl_client.cpp
src/rdsn/src/common/fs_manager.cpp
src/rdsn/src/http/http_call_registry.h
src/rdsn/src/http/http_message_parser.cpp
src/rdsn/src/http/uri_decoder.cpp
src/rdsn/src/meta/meta_backup_service.cpp
src/rdsn/src/runtime/rpc/thrift_message_parser.cpp
src/test/bench_test/benchmark.cpp
src/test/bench_test/benchmark.h
src/test/function_test/global_env.cpp
src/test/function_test/global_env.h
src/test/function_test/test_restore.cpp
src/test/kill_test/killer_handler_shell.cpp
src/test/kill_test/process_kill_testor.cpp
src/test/upgrade_test/process_upgrader.cpp
src/test/upgrade_test/upgrader_handler_shell.cpp

In https://github.com/apache/incubator-pegasus/pull/1062, we passed the debug/release to CMAKE_BUILD_TYPE in cmake, then `assert` will be disabled. Some function calls are in `assert` in the former, but now build the project in release type, these functions will not be called, which will lead the test failures as described in:
https://github.com/apache/incubator-pegasus/issues/1077

fix: fix 'assert' disabled caused function_test failed bug

---

.licenserc.yaml
thirdparty/CMakeLists.txt
thirdparty/fix_jemalloc_for_m1_on_macos.patch

issue: https://github.com/apache/incubator-pegasus/issues/1093
patch relate by https://github.com/jemalloc/jemalloc/issues/1997

feat: Support Build on M1 MacOS

---

src/rdsn/src/block_service/block_service_manager.cpp
src/rdsn/src/block_service/block_service_manager.h
src/rdsn/src/block_service/test/block_service_manager_test.cpp
src/rdsn/src/block_service/test/block_service_mock.h

This pr adds following functions for block service manager:
- upload_file
- read_file
- write_file
- remove_path
All of them will be used for backup and restore in further prs.

feat: add some functions for block service manager

---

scripts/clear_zk.sh
scripts/start_zk.sh
scripts/stop_zk.sh
src/rdsn/src/failure_detector/test/CMakeLists.txt
src/rdsn/src/meta/CMakeLists.txt
src/rdsn/src/meta/test/CMakeLists.txt
src/rdsn/src/meta/test/balancer_simulator/CMakeLists.txt
src/rdsn/src/meta/test/meta_state/CMakeLists.txt
src/rdsn/src/replica/backup/test/CMakeLists.txt
src/rdsn/src/replica/bulk_load/test/CMakeLists.txt
src/rdsn/src/replica/duplication/test/CMakeLists.txt
src/rdsn/src/replica/split/test/CMakeLists.txt
src/rdsn/src/replica/storage/simple_kv/CMakeLists.txt
src/rdsn/src/replica/storage/simple_kv/test/CMakeLists.txt
src/rdsn/src/replica/test/CMakeLists.txt
src/rdsn/src/runtime/security/init.cpp
src/rdsn/src/runtime/security/init.h
src/rdsn/src/runtime/security/kinit_context.cpp
src/rdsn/src/runtime/security/negotiation.cpp
src/rdsn/src/runtime/service_api_c.cpp
src/rdsn/src/zookeeper/CMakeLists.txt
src/rdsn/src/zookeeper/test/CMakeLists.txt
src/rdsn/src/zookeeper/zookeeper_session.cpp
src/server/CMakeLists.txt
src/server/test/CMakeLists.txt
thirdparty/CMakeLists.txt

Related issue: https://github.com/apache/incubator-pegasus/issues/1092
This pr revert zk c client to 3.4.10, this need merge into Pegasus 2.4:  https://github.com/apache/incubator-pegasus/issues/1032
- Unit test

fix: revert zk c client to 3.4.10 for compatibility

---

.github/workflows/lint_and_test_cpp.yaml
.github/workflows/pegasus-regular-build.yml
.github/workflows/thirdparty-regular-push.yml
docker/README.md
docker/thirdparties-bin/Dockerfile

https://github.com/apache/incubator-pegasus/issues/1113
Now different branches of apache repo will push docker images to DockerHub, this will introduce conflicts if they are not compatiable(e.g. thirdparty changes and not compatiable).
This patch is aim to push differnet name of docker images to DockerHub and will use different images according to the target branch name.

fix(actions): fix docker images conflict on different branches

---

.github/workflows/lint_and_test_cpp.yaml

This PR is to solve https://github.com/apache/incubator-pegasus/issues/1122.
To filter all the file changes that should trigger actions for github, at beginning of CI all of the path patterns are listed, which means workflows for build and test will never be run for the files that are irrelevant.

fix(github): fix the conditions for file changes that trigger workflows

---

.github/workflows/pegasus-regular-build.yml

https://github.com/apache/incubator-pegasus/issues/1125
When pegasus run regular ci, it will clone `master` code, but use the current branch docker images, this will cause ci falied.
clone code and checkout the current branch
Note: 
need merge v2.4 https://github.com/apache/incubator-pegasus/issues/1032
- Unit test

fix: update pegasus regular ci docker version base branch

---

.github/workflows/pegasus-regular-build.yml

This PR is used for fixing https://github.com/apache/incubator-pegasus/pull/1124, which only clone master and cause checkout failed, the issue ref: https://github.com/apache/incubator-pegasus/issues/1125

fix: update pegasus clone branch when regular ci docker

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h

https://github.com/apache/incubator-pegasus/issues/1025
The specific reason is that if you open an existing rocksdb, the usage scenario will be set to normal first, and then set to the corresponding mode according to the actual usage scenario. This process will change the relevant options, causing rocksdb to execute flush and compact, so in order to avoid this situation (https://github.com/apache/incubator-pegasus/pull/587), rocksdb::LoadLatestOptions is called, and these parameters are initialized with the last value, so the last thing you see is that if the configuration file is modified, and without changing the usage scenario mode, these modified configurations will not take effect after restart.
Options involved:
```
level0_file_num_compaction_trigger
level0_slowdown_writes_trigger …
```

fix: rocksdb options not changed even if update in Pegasus config file

---

.github/workflows/lint_and_test_cpp.yaml

This PR is to resolve https://github.com/apache/incubator-pegasus/issues/1135.
Since `thirdparties-bin-test-*` images had been committed to be built in https://github.com/apache/incubator-pegasus/pull/1136, first portable image of third-parties for master branch such as [apache/pegasus/thirdparties-bin-test-ubuntu1804-master](https://hub.docker.com/layers/pegasus/apache/pegasus/thirdparties-bin-test-ubuntu1804-master/images/sha256-d35457046181cb8575b2c30912f478cdea5c84b54b035be8ffce77a5a81df7ee?context=explore) was already pushed to [dockerhub](https://hub.docker.com).
To run unit tests on github `thirdparties-bin-test-*` image should be added to C++ workflow. This is the purpose of this PR.

fix(actinos): use portable thirdparties-bin-test-* as the base image to build and run unit tests for CI on github

---

src/rdsn/src/replica/backup/replica_backup_manager.cpp
src/rdsn/src/replica/backup/replica_backup_manager.h
src/rdsn/src/replica/backup/test/replica_backup_manager_test.cpp
src/rdsn/src/replica/replica_stub.cpp
src/rdsn/src/replica/replica_stub.h

This pr is about that replica server receive `backup_request` with checkpointing status, including:
- replica server handle `backup_request`, in function `on_cold_backup` and function `on_backup`
- replica start to create backup checkpoint, in function `start_checkpointing` and function `generate_checkpoint`
- replica report checkpoint status, in function `report_checkpointing`
- add related unit test

feat(backup): 5. replica create backup checkpoint

---

idl/rrdb.thrift
src/client_lib/pegasus_client_impl.h
src/client_lib/pegasus_scanner_impl.cpp
src/geo/lib/geo_client.cpp
src/include/pegasus/client.h
src/server/pegasus_scan_context.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/shell/command_helper.h
src/shell/commands/data_operations.cpp
src/shell/main.cpp
src/test/function_test/test_scan.cpp

issue: https://github.com/apache/incubator-pegasus/issues/1090
same job as before: https://github.com/apache/incubator-pegasus/pull/728
When we precisely count data for a large table, it will cost minutes or hours. 
However, it's unnecessarily return key-values from server to client. 
Actually, we just need the count of data. So we just need transfer the count of data from server to client, but not the detailed data.
**In my test, it will 2x on onebox faster than before.**
for my bench on onebox：
1> before
2> this commit
- Unit test

feat: improve performance of count_data

---

.github/workflows/thirdparty-regular-push.yml
docker/thirdparties-bin/Dockerfile

This PR is one of the sub-tasks of https://github.com/apache/incubator-pegasus/issues/1134. Third-parties images for both the purpose of production and test should be built firstly before they can be referenced by derived images.

feat(jemalloc): support building third-parties images for both production and test with jemalloc

---

src/rdsn/src/meta/meta_backup_engine.cpp
src/rdsn/src/meta/meta_backup_engine.h
src/rdsn/src/meta/test/meta_backup_engine_test.cpp

This pr is about the meta server receive `backup_response` with checkpoint status:
- if one partition failed during checkpoint, whole backup process will be failed
- if all partitions finish checkpoint, turn app backup_status into uploading
- resend backup_request to replica if backup is not finished
Besides, this pr adds related unit tests.

feat(backup): 6. meta handle backup_response during checkpointing

---

src/rdsn/src/common/backup_restore_common.cpp
src/rdsn/src/common/backup_restore_common.h
src/rdsn/src/replica/backup/replica_backup_manager.cpp
src/rdsn/src/replica/backup/replica_backup_manager.h
src/rdsn/src/replica/backup/test/config-test.ini
src/rdsn/src/replica/backup/test/replica_backup_manager_test.cpp
src/rdsn/src/replica/replica_stub.h

This pr is about that replica server receive `backup_request` with uploading status, including:
- replica start to upload backup files, in function `start_uploading`, `upload_checkpoint` and `upload_file`, when replica upload all files, it will write some files onto remote block service, in function `upload_file_completed`.
- replica report upload process, in function `report_uploading`
- add related unit test

feat(backup): 7. replica upload backup files

---

.github/workflows/lint_and_test_cpp.yaml
src/rdsn/include/dsn/utility/enum_helper.h
src/rdsn/src/replica/replica_stub.cpp
src/rdsn/src/replica/replica_stub.h
src/rdsn/src/utils/je_ctl.cpp
src/rdsn/src/utils/je_ctl.h
src/rdsn/src/utils/test/je_ctl_test.cpp

This PR is a sub-task for https://github.com/apache/incubator-pegasus/issues/1134, to implement a tool to dump stats for jemalloc.

feat(jemalloc): support to dump stats

---

src/rdsn/src/meta/meta_backup_engine.cpp
src/rdsn/src/meta/meta_backup_engine.h
src/rdsn/src/meta/test/meta_backup_engine_test.cpp

This pr is about meta server handle `backup_response` during uploading and succeed status:
- if partition status is uploading, continue to send request to replica server
- if all partitions succeed, write backup_info onto remote block service and update backup status on zk
Besides, this pr adds related unit test.

feat(backup): 8. meta handle backup_response during uploading and succeed

---

.github/workflows/regular-build.yml
README.md
docker/README.md

https://github.com/apache/incubator-pegasus/issues/1053
Revert changes on `.github/workflows/regular-build.yml`, since context `github.base_ref` is not valid when workflow triggered by push.
Of course, this workflow will not be triggered by pull_request event, which is the same behavior as before, we have to run it mannually.
manual test passed: https://github.com/apache/incubator-pegasus/actions/runs/3019576718

fix: fix bad links and bad image names

---

.github/workflows/lint_and_test_cpp.yaml
run.sh

This PR is to fix https://github.com/apache/incubator-pegasus/issues/1160.

fix(workflow): drop --on_travis option for unit tests of jemalloc

---

src/server/config.ini

This PR is to fix https://github.com/apache/incubator-pegasus/issues/1151.
The reason that table `stat` should be created by meta server on bootstrap is that once cpp collector is started it will report error if `stat` does not exist.
The configuration for `stat` is added in [src/server/config.ini](https://github.com/apache/incubator-pegasus/blob/master/src/server/config.ini), which is usually adopted by new users as their first configuration file.

fix(config): create stat table as required by cpp collector on bootstrap

---

.github/workflows/thirdparty-regular-push.yml

This PR is to solve https://github.com/apache/incubator-pegasus/issues/1159.

build(images): parallelize images building for all binary third-parties and only build ubuntu1804 for test images

---

docker/README.md
src/rdsn/src/common/backup_restore_common.cpp
src/rdsn/src/common/backup_restore_common.h
src/rdsn/src/common/replication_common.cpp
src/rdsn/src/common/replication_common.h
src/rdsn/src/replica/backup/replica_backup_manager.cpp
src/rdsn/src/replica/backup/replica_backup_manager.h
src/rdsn/src/replica/backup/test/replica_backup_manager_test.cpp
src/rdsn/src/replica/replica_config.cpp

This pr is about replica handle clear after backup succeed or failed, and add invalid status check, including:
- add backup_status check in function `on_backup`
- implement function `clear_context` to clear backup context
- implement function `background_clear_backup_checkpoint` and `clear_backup_checkpoint` to delete replica checkpoint directory created by backup
- when replica configuration changed, call clear_context to stop possible backup, in `replica_config.cpp`
- add related unit tests

feat(backup): 9. replica handle backup clear context and invalid status

---

.github/workflows/thirdparty-regular-push.yml
docker/thirdparties-bin/Dockerfile
scripts/download_hadoop.sh

This PR is to fix https://github.com/apache/incubator-pegasus/issues/1164. This has been tested by manually running BuildThirdpartyDockerRegularly as https://github.com/apache/incubator-pegasus/actions/runs/3094818838.

build(images): download hadoop-2.8.4.tar.gz during third-parties image building for unit tests

---

run.sh
src/test/function_test/backup_restore_test/test_backup_and_restore.cpp
src/test/function_test/base_api_test/test_basic.cpp
src/test/function_test/base_api_test/test_batch_get.cpp
src/test/function_test/base_api_test/test_check_and_mutate.cpp
src/test/function_test/base_api_test/test_check_and_set.cpp
src/test/function_test/base_api_test/test_copy.cpp
src/test/function_test/base_api_test/test_incr.cpp
src/test/function_test/base_api_test/test_range_read.cpp
src/test/function_test/base_api_test/test_recall.cpp
src/test/function_test/base_api_test/test_scan.cpp
src/test/function_test/base_api_test/test_ttl.cpp
src/test/function_test/bulk_load_test/test_bulk_load.cpp
src/test/function_test/detect_hotspot_test/test_detect_hotspot.cpp
src/test/function_test/partition_split_test/test_split.cpp
src/test/function_test/recovery_test/test_recovery.cpp
src/test/function_test/restore_test/test_restore.cpp
src/test/function_test/throttle_test/test_throttle.cpp
src/test/function_test/utils/CMakeLists.txt
src/test/function_test/utils/global_env.cpp
src/test/function_test/utils/test_util.cpp
src/test/function_test/utils/test_util.h
src/test/function_test/utils/utils.h

https://github.com/apache/incubator-pegasus/issues/1166
This is a flow up to https://github.com/apache/incubator-pegasus/pull/1149, now refactoring these function tests to inherit from test_util to reduce duplicate code.
And also include some other non-functional refactors.

refactor(function_test): use test_util to reduce duplicate code

---

.github/workflows/lint_and_test_cpp.yaml
scripts/config_hdfs.sh

This PR is to fix https://github.com/apache/incubator-pegasus/issues/1164. Once third-parties have changed, image will not be used thus hadoop-2.8.4.tar.gz should be downloaded.
On the other hand, an error was reported as:
This told that `source` should be used since it will quit from `return` rather than `exit`, as following code in [config_hdfs.sh](https://github.com/apache/incubator-pegasus/blob/master/scripts/config_hdfs.sh):
```bash
export HADOOP_HOME="${HADOOP_HOME:-${PEGASUS_HADOOP_HOME}}"
if [ ! -d "$HADOOP_HOME/etc/hadoop" ] || [ ! -d "$HADOOP_HOME/share/hadoop" ]; then
echo "HADOOP_HOME must be set to the location of your Hadoop jars and core-site.xml."
return 1
fi
```
Thus in [lint_and_test_cpp.yaml](https://github.com/apache/incubator-pegasus/blob/master/.github/workflows/lint_ …

ci: download hadoop-2.8.4.tar.gz during release building for unit tests once third-parties have changed

---

src/rdsn/src/utils/metrics.cpp
src/rdsn/src/utils/metrics.h

This PR is to solve https://github.com/apache/incubator-pegasus/issues/1195.

feat(new_metrics): use rwlock instead of mutex to protect a metric entity or registry against few writes and numerous reads

---

src/aio/disk_engine.cpp
src/common/replication_common.cpp
src/replica/duplication/duplication_pipeline.cpp
src/replica/duplication/mutation_batch.cpp
src/replica/log_file.cpp
src/replica/prepare_list.cpp
src/replica/replica_learn.cpp
src/replica/replication_app_base.cpp
src/replica/split/replica_split_manager.cpp
src/reporter/pegasus_counter_reporter.cpp
src/runtime/task/task_spec.cpp
src/server/hotkey_collector.cpp
src/server/pegasus_server_impl.cpp
src/utils/endians.h
src/utils/fmt_logging.h
src/utils/je_ctl.cpp
src/utils/metrics.cpp
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1204
- `dcheck_ge` -> `CHECK_GE`
- `dcheck_le` -> `CHECK_LE`
- `dcheck_gt` -> `CHECK_GT`
- `dcheck_lt` -> `CHECK_LT`
- `dcheck_ge_replica` -> `CHECK_GE_PREFIX`
- `dcheck_le_replica` -> `CHECK_LE_PREFIX`
- `dcheck_gt_replica` -> `CHECK_GT_PREFIX`
- `dcheck_lt_replica` -> `CHECK_LT_PREFIX`

refactor(macro): use CHECK_* to replace dassert_*

---

java-client/pom.xml

https://github.com/apache/incubator-pegasus/issues/1224
漏洞详情
Apache Commons Configuration是一个Java应用程序的配置管理工具，可以从properties或者xml文件中加载软件的配置信息，用来构建支撑软件运行的基础环境。在一些配置文件较多较复杂的情况下，使用该配置工具比较可以简化配置文件的解析和管理，提高开发效率和软件的可维护性。
从2.4版到2.7版，默认的Lookup实例集包括可能导致任意代码执行或与远程服务器联系的插值器。如公告中提到“script” 可使用JVM脚本执行引擎(javax.script)执行表达式，若使用了不受信任的配置值，在受影响的版本中使用插值默认值的应用程序就很可能受到远程代码执行的影响。
update Apache Commons Configuration version to 2.8.0

fix: update commons-configuration2 version to 2.8.0

---

src/meta/duplication/duplication_info.cpp
src/meta/duplication/duplication_info.h
src/replica/duplication/load_from_private_log.cpp
src/replica/duplication/mutation_batch.cpp
src/replica/prepare_list.cpp
src/replica/replica.cpp
src/replica/replica_config.cpp
src/replica/replica_disk_migrator.cpp
src/replica/replica_learn.cpp
src/replica/replica_restore.cpp
src/replica/replication_app_base.cpp
src/replica/split/replica_split_manager.cpp
src/server/meta_store.cpp
src/server/pegasus_mutation_duplicator.cpp
src/server/pegasus_server_impl.cpp
src/utils/fmt_logging.h

https://github.com/apache/incubator-pegasus/issues/1204
Adds some more general macros `CHECK_PREFIX_MSG`, `CHECK_NOTNULL_PREFIX_MSG`, `CHECK_NE/EQ/GE/GT/LE/LT_PREFIX[_MSG]` to replace `dassert_replica`

refactor(macro): use the more general CHECK_PREFIX* to replace dassert_replica

---

.licenserc.yaml
src/server/pegasus_server_impl.cpp
thirdparty/CMakeLists.txt
thirdparty/rocksdb_fix_atomic_flush_0879c240.patch

https://github.com/apache/incubator-pegasus/issues/1047
For some historical reasons, we use the Xiaomi modified rocksdb library. Since Pegasus 2.1.0, we have removed all modifications on rocksdb, only left some code to keep compatiable [1], now we are planning to switch to the official version.
It's expect that `thirdparty/rocksdb_fix_atomic_flush_0879c240.patch` must be corresponding to this patch [2].
**ATTENTION**: There is a limit that the server must be upgraded from 2.1, 2.2, 2.3 or 2.4, to ensure that there is no Pegasus introduced tags which the official rocksdb doesn't recognize left in MANIFEST file.
1. https://github.com/XiaoMi/pegasus-rocksdb/commits/v6.6.4-compatible
2. https://github.com/XiaoMi/pegasus-rocksdb/commit/ef29819c7a1ea9334ae170f506b653757f517a52

feat(thirdparty): use official rocksdb

---

src/aio/aio_provider.h
src/aio/aio_task.h
src/aio/disk_engine.cpp
src/aio/disk_engine.h
src/aio/file_io.cpp
src/aio/native_linux_aio_provider.cpp
src/aio/native_linux_aio_provider.h
src/nfs/nfs_server_impl.cpp
src/nfs/nfs_server_impl.h

https://github.com/apache/incubator-pegasus/issues/1234
including changes:
1. change `dsn_handle_t` which is used for files descriptor to `linux_fd_t` which wrap an `int`
2. remove useless `dsn_handle_t` type member from `class aio_context`, `struct callback_para`
3. change `file_object` from `void *` to `disk_file *`

refactor: use linux_fd_t instead of dsn_handle_t for file descriptor

---

scripts/clear_zk.sh

https://github.com/apache/incubator-pegasus/issues/1243
`clear_zk.sh` is invalid.

fix: valid zookeeper directory for clear

---

src/utils/simple_logger.cpp

https://github.com/apache/incubator-pegasus/issues/1199
In commit https://github.com/apache/incubator-pegasus/pull/1200, we exchange DEBUG level and INFO level, but the log header prefixes have been forgot to update. This patch fix it.

fix: fix log header not corresponding to level

---

src/utils/enum_helper.h
src/utils/metrics.cpp
src/utils/metrics.h
src/utils/test/metrics_test.cpp

This PR is to solve https://github.com/apache/incubator-pegasus/issues/1236.

feat(new_metrics): support filters for selected metric fields in response

---

src/geo/bench/config.ini
src/redis_protocol/proxy/config.ini
src/server/config.ini
src/server/config.min.ini
src/shell/config.ini
src/test/bench_test/config.ini
src/test/function_test/config.ini
src/test/kill_test/config.ini
src/test/pressure_test/config-pressure.ini
src/utils/logging.cpp

https://github.com/apache/incubator-pegasus/issues/1249
Adjust the default log level from DEBUG to INFO to reduce too verbose logs for server, shell tool, and benchmark tests. The other unit tests are left in DEBUG level for debug.

refactor(log): adjust default log level from DEBUG to INFO

---

java-client/pom.xml

https://github.com/apache/incubator-pegasus/issues/1255
Add different profiles when building with jdk8 and jdk11+.
Also bump the maven compiler plugin to 3.10.1.

build(pom): Use --release when building java client with java11+

---

java-client/pom.xml

https://github.com/apache/incubator-pegasus/issues/1259
The plugin versions in the parent are newer, so I also bumped most of the maven plugin versions.

build(pom): Inherit apache pom

---

.github/workflows/standardization_lint.yaml

This PR is to solve #1269.
BTW, while trying to upgrade [neofinancial/ticket-check-action](https://github.com/marketplace/actions/pull-request-ticket-check-action) to the latest version 1.3.3, error message is showed as below:
```
neofinancial/ticket-check-action@v1.3.3 is not allowed to be used in apache/incubator-pegasus. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, …
```

chore(action): support checking issue number prefixed with '#' in github actions for PRs

---

java-client/pom.xml
java-client/src/main/java/org/apache/pegasus/client/ClientOptions.java
java-client/src/main/java/org/apache/pegasus/security/Credential.java
java-client/src/main/java/org/apache/pegasus/security/KerberosCredential.java
java-client/src/main/java/org/apache/pegasus/util/PropertyUtils.java

https://github.com/apache/incubator-pegasus/issues/1268
For commons-lang3, we expose its `Pair` class in our public API, so we still need it.

refactor: Remove usage of commons-configuration

---

src/common/replication_common.cpp
src/common/replication_common.h
src/http/builtin_http_calls.cpp
src/http/builtin_http_calls.h
src/http/config_http_service.cpp
src/http/http_call_registry.h
src/http/http_server.cpp
src/http/http_server.h
src/meta/meta_http_service.h
src/replica/duplication/test/dup_replica_http_service_test.cpp
src/replica/replica_http_service.cpp
src/replica/replica_http_service.h
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/test/replica_http_service_test.cpp
src/runtime/task/async_calls.h
src/runtime/task/task.cpp
src/runtime/task/task.h
src/server/info_collector_app.cpp
src/utils/flags.h

https://github.com/apache/incubator-pegasus/issues/1197
This patch implement a mechanism to make the configs take effect for the FLAGS_* only used once. They are used once to create some runtime objects, and then will never use the FLAGS_* again, which means update the config by HTTP is meanless.
This patch takes `config_sync_interval_ms` for example, showing how to update a config.

feat(config): Make the configs take effect for the FLAGS_* only used once

---

java-client/pom.xml

https://github.com/apache/incubator-pegasus/issues/1276
Add nexus-staging-maven-plugin to support auto closing of staging repo.
Also need to add doclint none, otherwise it will fail the deploy processing while generating javadoc.

build: Support publish artifacts to repository.a.o

---

.github/workflows/lint_and_test_admin-cli.yml
.github/workflows/lint_and_test_go-client.yml
README.md
admin-cli/README.md
java-client/README.md

https://github.com/apache/incubator-pegasus/issues/1281
Fix some bad links.
Since Java-client and Admin-cli are lint and built by `.github/workflows/regular-build.yml`, the status is shown on the main page, it's not needed to show again in sub-pages.

fix: fix some bad links of docs

---

.github/workflows/regular-build.yml

https://github.com/apache/incubator-pegasus/issues/1291
- Use `ubuntu-20.04` instaed of `ubuntu-latest` in order to install thrift-0.13
- Reorder lint and build steps, because some files are generated after building successfully
It can be previewed in https://github.com/apache/incubator-pegasus/actions/runs/3681562714.
NOTE:
- Please ignore the CPP build failures, it will only work on master branch
- The failure of `Build Cpp (ubuntu1604, gcc)` on master branch will be fixed by another patch

chore(ci): use ubuntu-20.04 and install thrift-0.13 specially

---

src/runtime/task/task_code.cpp

as https://github.com/apache/incubator-pegasus/issues/1294
with gcc bug：https://gcc.gnu.org/legacy-ml/gcc-patches/2010-10/msg00054.html

fix(ci): fix build failure on ubuntu-16.04

---

src/runtime/nativerun.cpp
src/runtime/providers.common.cpp
src/runtime/task/task_spec.cpp

issue: https://github.com/apache/incubator-pegasus/issues/1131
Disable UDP service when not use it.
Add a configuration 'enable_udp' with a default value of 'false' in the 'network' section. It gives the server control over whether to start the UDP service.

feat(server): disable UDP service by config

---

go-client/admin/client.go
java-client/src/main/java/org/apache/pegasus/client/PegasusAdminClient.java
java-client/src/main/java/org/apache/pegasus/client/PegasusAdminClientInterface.java
src/client/replication_ddl_client.cpp
src/client/replication_ddl_client.h
src/shell/commands/table_management.cpp
src/shell/main.cpp

https://github.com/apache/incubator-pegasus/issues/1147

feat: expose parameter success_if_exist for interface create_app

---

src/utils/metrics.cpp
src/utils/test/metrics_test.cpp

This PR is to resolve https://github.com/apache/incubator-pegasus/issues/1301.

feat(new_metrics): support frequently-used combinations of metric fields in the query string

---

src/replica/backup/replica_backup_server.cpp
src/replica/mutation_log.cpp
src/replica/mutation_log_replay.cpp
src/replica/replica.cpp
src/replica/replica_2pc.cpp
src/replica/replica_backup.cpp
src/replica/replica_check.cpp
src/replica/replica_chkpt.cpp
src/replica/replica_config.cpp
src/replica/replica_failover.cpp
src/replica/replica_init.cpp
src/replica/replica_learn.cpp
src/replica/replica_restore.cpp
src/replica/test/mock_utils.h

https://github.com/apache/incubator-pegasus/issues/1305
This patch aim to use LOG_INFO_F instead of LOG_INFO. Includes:
- Use `LOG_INFO_F` instead of `LOG_INFO` in replica module.
- Use `LOG_INFO_PREFIX` instaed of `LOG_INFO` for class `replica`

refactor(log): use LOG_INFO_F instead of LOG_INFO (1/3)

---

src/meta/app_balance_policy.cpp
src/meta/greedy_load_balancer.cpp
src/meta/load_balance_policy.cpp
src/meta/meta_backup_service.cpp
src/meta/meta_backup_service.h
src/meta/meta_data.cpp
src/meta/meta_server_failure_detector.cpp
src/meta/meta_service.cpp
src/meta/meta_service.h
src/meta/meta_state_service_zookeeper.cpp
src/meta/partition_guardian.cpp
src/meta/server_state.cpp
src/meta/server_state_restore.cpp
src/meta/test/backup_test.cpp
src/meta/test/meta_state/meta_state_service.cpp
src/meta/test/update_configuration_test.cpp

https://github.com/apache/incubator-pegasus/issues/1305
This patch aim to use LOG_INFO_F instead of LOG_INFO Includes:
- Use `LOG_INFO_F` instead of `LOG_INFO` in meta module.

refactor(log): use LOG_INFO_F instead of LOG_INFO (2/3)

---

src/http/http_server.cpp
src/runtime/task/simple_task_queue.cpp
src/server/pegasus_mutation_duplicator.cpp
src/shell/commands/duplication.cpp
src/test/kill_test/data_verifier.cpp
src/test/kill_test/process_kill_testor.cpp
src/utils/api_utilities.h
src/utils/fail_point.cpp

https://github.com/apache/incubator-pegasus/issues/1305
This patch aim to use LOG_FATAL_F instead of LOG_FATAL for all parts:
- Remove the defination of `LOG_FATAL`
- Use `LOG_FATAL_F` instead of `LOG_FATAL`

refactor(log): use LOG_FATAL_F instead of LOG_FATAL

---

src/replica/log_file.cpp
src/replica/mutation_log.cpp
src/replica/mutation_log_replay.cpp
src/replica/replica.cpp
src/replica/replica_2pc.cpp
src/replica/replica_backup.cpp
src/replica/replica_check.cpp
src/replica/replica_config.cpp
src/replica/replica_init.cpp
src/replica/replica_learn.cpp
src/replica/replica_stub.cpp

#1305
This patch aim to use LOG_WARNING_F instead of LOG_WARNING for replica module. Includes:
- Use LOG_WARNING_F instead of LOG_WARNING in replica module.
- Use LOG_WARNING_PREFIX instaed of LOG_WARNING for class replica

refactor(log): use LOG_WARNING_F instead of LOG_WARNING (1/3)

---

src/meta/load_balance_policy.cpp
src/meta/meta_backup_service.cpp
src/meta/meta_data.cpp
src/meta/meta_server_failure_detector.cpp
src/meta/meta_service.cpp
src/meta/meta_state_service_zookeeper.cpp
src/meta/partition_guardian.cpp
src/meta/server_state.cpp

https://github.com/apache/incubator-pegasus/issues/1305
This patch aim to use LOG_WARNING_F instead of LOG_WARNING. Includes:
Use LOG_WARNING_F instead of LOG_WARNING in meta module.

refactor(log): use LOG_WARNING_F instead of LOG_WARNING (2/3)

---

src/block_service/test/fds_service_test.cpp
src/common/replication_common.cpp
src/common/replication_common.h
src/meta/meta_backup_service.cpp
src/meta/meta_service.cpp
src/meta/test/backup_test.cpp
src/replica/backup/replica_backup_manager.cpp
src/replica/mutation_cache.h
src/replica/replica.cpp
src/replica/replica_2pc.cpp
src/replica/replica_check.cpp
src/replica/replica_chkpt.cpp
src/replica/replica_init.cpp
src/replica/replica_learn.cpp
src/replica/replica_stub.cpp
src/replica/split/replica_split_manager.cpp
src/replica/test/mock_utils.h
src/server/pegasus_server_impl_init.cpp
src/shell/commands/data_operations.cpp
src/test/bench_test/benchmark.cpp
src/test/bench_test/config.cpp
src/test/bench_test/config.h

This patch refactor code to use `DSN_DEFINE_int32` instead of `dsn_config_get_value_uint64` to load int32 type of configurations, and doesn't introduce any functional changes.
- all default value and most of description are kept as before, except moving some comments to description for some config items to make them self-explanation when using http APIs.
- move the defination of flags closer to the place where uses it
- use `DSN_DEFINE_group_validator` instaed of `replication_options::sanity_check()` and remove the later

refactor(conf): use DSN_DEFINE_int32 to load int32 type of configs

---

.github/workflows/test_nodejs-client.yml
nodejs-client/test.sh

https://github.com/apache/incubator-pegasus/issues/1330
There is no functional changes in this patch, but only adding unit test workflow for node.js client.
See the workflow by link "Test - node.js client / test (pull_request)" below.

chore(CI): Add unit test workflow for node.js client

---

src/utils/strings.cpp
src/utils/strings.h
src/utils/test/utils.cpp

https://github.com/apache/incubator-pegasus/issues/1337
- Unit test

feat(utils): add an utility function to find string prefix by separator

---

.github/workflows/build-push-env-docker.yml
.github/workflows/regular-build.yml
.github/workflows/thirdparty-regular-push.yml
.licenserc.yaml
cmake_modules/BaseFunctions.cmake
docker/README.md
docker/pegasus-build-env/ubuntu2204/Dockerfile
thirdparty/CMakeLists.txt
thirdparty/fix_prometheus-cpp_limits.patch

https://github.com/apache/incubator-pegasus/issues/1349
Introduce Ubuntu 22.04 to supported OS list.

build: Support Ubuntu 22.04 and clang 14

---

src/geo/lib/geo_client.cpp
src/meta/test/main.cpp
src/runtime/rpc/asio_net_provider.cpp
src/runtime/rpc/network.cpp
src/runtime/rpc/network.h
src/runtime/rpc/network.sim.cpp
src/runtime/rpc/network.sim.h
src/runtime/rpc/rpc_engine.cpp
src/runtime/rpc/rpc_message.cpp
src/runtime/rpc/rpc_message.h
src/runtime/service_engine.cpp
src/runtime/test/netprovider.cpp
src/server/available_detector.cpp
src/server/available_detector.h
src/server/info_collector.cpp
src/server/info_collector.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_server_impl_init.cpp
src/test/kill_test/data_verifier.cpp
src/test/kill_test/kill_testor.cpp
src/test/kill_test/kill_testor.h
src/test/kill_test/partition_kill_testor.cpp
src/test/kill_test/process_kill_testor.cpp

This patch refactor the code to use `DSN_DEFINE_uint32` instead of `dsn_config_get_value_uint64` to load uint32 type of configurations, and doesn't introduce any functional changes.
- all default value and most of description are kept as before
- move the defination of flags closer to the places where they're used

refactor(conf): use DSN_DEFINE_uint32 to load uint32 type of configs

---

src/common/replication_common.cpp
src/common/replication_common.h
src/server/config.ini
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_server_impl_init.cpp
src/server/pegasus_write_service.cpp
src/server/pegasus_write_service.h
src/server/test/config.ini
src/test/pressure_test/main.cpp

This patch refactors the code to use `DSN_DEFINE_int64` instead of `dsn_config_get_value_int64/uint64` to load int64 type of configurations, and doesn't introduce any functional changes.
- all default value and most of description are kept as before
- move the defination of flags closer to the places where they're used
- remove `checkpoint_min_decree_gap` which is never used
NOTE: `rocksdb_max_open_files` is type of `int32` because `_db_opts.max_open_files` is type of `int32`.

refactor(conf): use DSN_DEFINE_int64 to load int64 type of configs

---

src/block_service/test/fds_service_test.cpp
src/failure_detector/test/failure_detector.cpp
src/meta/meta_options.cpp
src/meta/meta_options.h
src/meta/meta_server_failure_detector.cpp
src/meta/meta_service.cpp
src/meta/partition_guardian.cpp
src/meta/test/meta_app_operation_test.cpp
src/meta/test/update_configuration_test.cpp
src/replica/replica_2pc.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/server/capacity_unit_calculator.cpp
src/server/capacity_unit_calculator.h
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_server_impl_init.cpp
src/server/range_read_limiter.h
src/server/test/capacity_unit_calculator_test.cpp
src/test/bench_test/benchmark.cpp
src/test/bench_test/config.cpp
src/test/bench_test/config.h
src/test/bench_test/config.ini

This patch refactors the code to use `DSN_DEFINE_uint64` instead of `dsn_config_get_value_uint64` to load uint64 type of configurations, and doesn't introduce any functional changes.
- all default value and most of description are kept as before
- move the defination of flags closer to the places where they're used
- rename `num` and `seed` to `benchmark_num` and `benchmark_seed` in section `[pegasus.benchmark]`, it's acceptable because they're just in benchmark tests

refactor(conf): use DSN_DEFINE_uint64 to load uint64 type of configs

---

src/runtime/service_api_c.cpp
src/server/pegasus_server_impl_init.cpp

This patch refactors the code to use `DSN_DEFINE_double` instead of `dsn_config_get_value_double` to load double type of configurations, and doesn't introduce any functional changes.
- all default value and most of description are kept as before

refactor(conf): use DSN_DEFINE_double to load double type of configs

---

src/runtime/CMakeLists.txt
src/runtime/ranger/CMakeLists.txt
src/runtime/ranger/ranger_resource_policy.cpp
src/runtime/ranger/ranger_resource_policy.h
src/runtime/test/ranger_resource_policy_test.cpp

This patch aim to define ranger policy:
- Define the ranger policy data structure.
- Realized the judgment logic function when performing ACL with different priorities.
- Add some unit test for test

feat(security): Use Apache Ranger for access control(1/n)

---

src/meta/meta_service.h
src/runtime/ranger/ranger_resource_policy_manager.cpp
src/runtime/ranger/ranger_resource_policy_manager.h

This patch aim to define ranger_resource_policy_manager:
- Define the ranger_resource_policy_manager data structure(currently, only some member variables are included).
- Implementation of constructor，it will classify and match resources according to the type of `rpc_code`.

feat(security): Use Apache Ranger for access control(2/n)

---

src/common/CMakeLists.txt
src/remote_cmd/CMakeLists.txt
src/runtime/security/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1377
It seems CLion is not able to resolve the `../..` path in CMakeList.txt, and the Pegasus project could not be loaded by CLion correctly.
This patch fixes the issue by useing `${PROJECT_ROOT}`, and the Pegasus project can be loaded and indexed by CLion on my own Macbook now.

chore(cmake): fix project load failure by CLion

---

run.sh
src/test/bench_test/benchmark.cpp
src/test/bench_test/benchmark.h
src/test/bench_test/config.cpp
src/test/bench_test/config.ini
src/test/bench_test/statistics.cpp
src/test/bench_test/utils.h

Issue: https://github.com/apache/incubator-pegasus/issues/1372

feat(test): add bench type multi set/get

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_server_impl_init.cpp
src/server/pegasus_write_service_impl.h
src/server/rocksdb_wrapper.cpp
src/server/rocksdb_wrapper.h
src/server/test/pegasus_server_impl_test.cpp
src/utils/metrics.h
src/utils/test/metrics_test.cpp
src/utils/time_utils.h

This PR is to migrate replica-level metrics of `pegasus_server_impl` to new framework
(https://github.com/apache/incubator-pegasus/issues/1333). Since there are many replica-level
metrics in `pegasus_server_impl`, this PR is part 1 for this migration and other metrics (all
of which are gauges) will be migrated in the later PRs.

feat(new_metrics): migrate replica-level metrics for pegasus_server_impl (part 1)

---

.github/workflows/build-push-env-docker.yml
.github/workflows/labeler.yml
.github/workflows/lint_and_test_admin-cli.yml
.github/workflows/lint_and_test_cpp.yaml
.github/workflows/lint_and_test_go-client.yml
.github/workflows/lint_and_test_pegic.yml
.github/workflows/regular-build.yml
.github/workflows/standardization_lint.yaml
.github/workflows/test_java-client.yml
.github/workflows/test_scala-client.yml
.github/workflows/thirdparty-regular-push.yml
src/http/http_server.cpp
src/replica/duplication/replica_follower.cpp
src/runtime/ranger/ranger_resource_policy_manager.cpp
src/runtime/ranger/ranger_resource_policy_manager.h
src/utils/string_conv.h

https://github.com/apache/incubator-pegasus/issues/1349
Now we have introduced Ubuntu 22.04 (with GCC 11.3.0) Dockerfile, and use it for daily regular build workflow, but the workflow for pull requests is using Ubuntu 18.04 (with GCC 7.5.0). Some warnings or errors will be reported in daily regular build workflow lately. GCC 11.3.0 has more default CXXFLAGS to check hidden code troubles, so I suggest using Ubuntu 22.04 (with GCC 11.3.0) for pull requests.
This patch also includes some other improvements, including:
- upgrade `actions/checkout@v2` to `actions/checkout@v3`
- remove `fetch-depth` option since the default is `1` which is which we need
- remove `submodules` option since it's meaningless now
- remove `/root/thirdparties-bin.zip` after it has been unzipped
- move `--exclude` to …

chore(CI): Use Ubuntu 22.04 as the default test platform

---

src/replica/replica_config.cpp
src/runtime/security/access_controller.cpp
src/runtime/security/access_controller.h
src/runtime/security/replica_access_controller.cpp
src/runtime/security/replica_access_controller.h

This patch is compatible with old and new acl.
- Modify some method names and parameter names to make them more accurate.
- Defines the configuration parameters that the new ACL needs to use.
- Two new 'allowed()' methods are provided for meta_server and replica_server.
- Some incompatible methods will be removed, (allowed&pre_check)commented.

feat(Ranger): Compatible with the old ACL and the new ACL

---

src/common/json_helper.h
src/runtime/ranger/access_type.cpp
src/runtime/ranger/access_type.h
src/runtime/ranger/ranger_resource_policy.cpp
src/runtime/ranger/ranger_resource_policy.h
src/runtime/ranger/ranger_resource_policy_manager.cpp
src/runtime/ranger/ranger_resource_policy_manager.h
src/runtime/test/CMakeLists.txt
src/runtime/test/ranger_resource_policy_manager_test.cpp
src/runtime/test/ranger_resource_policy_test.cpp

This patch is to prepare for parse policies and dump policies:
- 'DEFINE_JSON_SERIALIZATION' for data structure.
- Preparations for json parsing
- add unit test for 'parse_policies_from_json'

feat(Ranger): Support encode and decode Ranger policies

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_server_impl_init.cpp
src/utils/metrics.h

This PR is to migrate replica-level metrics of pegasus_server_impl to new framework, 
2nd part, for https://github.com/apache/incubator-pegasus/issues/1333.
This PR focuses on migrating all rocksdb-related metrics for each replica, including
total number and size of sst files, estimated number of keys, memory usage and hit
rate, write/read amplification, negatives/positives of bloom filters.

feat(new_metrics): migrate replica-level metrics for pegasus_server_impl (part 2)

---

run.sh
scripts/downgrade_node.sh

https://github.com/apache/incubator-pegasus/issues/1368
- Manual test

chore(script): Script downgrade_node.sh supports using specified config file when using shell client

---

run.sh
scripts/migrate_node.sh

https://github.com/apache/incubator-pegasus/issues/1368
- Manual test

chore(script): Script migrate_node.sh supports using specified config file when using shell config

---

src/server/capacity_unit_calculator.cpp
src/server/capacity_unit_calculator.h
src/server/pegasus_write_service.cpp
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1334
Migrate the metrics in capacity_unit_calculator to new framework, including read/write capacity units
and the number of bytes consumed by get, multi_get, batch_get, scan, put, multi_put, check_and_set,
check_and_mutate and backup requests.

feat(new_metrics): migrate replica-level metrics for capacity_unit_calculator

---

src/utils/output_utils.h

Fixes #1394
Includes `<cmath>` in `src/utils/output_utils.h`.

chore(CI): include cmath to fix ambiguous std::abs on ubuntu1604

---

java-client/src/main/java/org/apache/pegasus/security/KerberosProtocol.java

fix #1389 
- Unit test
- No code

fix: jaas conf; make thread daemon

---

.github/workflows/lint_and_test_cpp.yaml
.gitignore
run.sh
scripts/pack_client.sh
scripts/pack_common.sh
scripts/pack_server.sh
scripts/pack_tools.sh

https://github.com/apache/incubator-pegasus/issues/1400
- Move cmake build directory from `./src/builder/` to a standalone
directory in `./build/`
- Avoid to re-generate thrift and git commit header files to speedup
re-build the project

chore(build): make build dir standalone and speedup re-build

---

src/meta/meta_service.cpp
src/meta/meta_service.h

https://github.com/apache/incubator-pegasus/issues/1405
The purpose of this patch is to make method `check_leader` return enumeration class
type(`meta_leader_state`) instead of int, to avoid making mistake.
Refactor the following two methods and the methods that use them：
```
int check_leader(dsn::message_ex *req, dsn::rpc_address *forward_address);
template <typename TRpcHolder>
int check_leader(TRpcHolder rpc, /*out*/ rpc_address *forward_address);
void meta_service::on_start_recovery(configuration_recovery_rpc rpc);
bool meta_service::check_status(TRpcHolder rpc, rpc_address *forward_address);
```

refactor: Refactor the method 'check_leader' make it return a enum class type

---

java-client/src/main/java/org/apache/pegasus/client/PegasusTable.java

https://github.com/apache/incubator-pegasus/issues/1410
In batchGetByPartitions, once some exception happens (such as timeout), resultMapList
will miss element which will lead to misalignment and IndexOutOfBoundsException. Just
add an empty element for resultMapList to align it while exception happens.

fix(java-client): add missing elements that will lead to misalignment and IndexOutOfBoundsException for resultMapList in batchGetByPartitions

---

src/server/pegasus_event_listener.cpp
src/server/pegasus_event_listener.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1343
Migrate replica-level metrics in pegasus_event_listener class to new framework, all of which
are rocksdb-related, including the number of completed flushes/compactions, the size of
flush output in bytes, the size of compaction input/output in bytes.
Note that in old perf counters there are just 2 replica-level metrics for pegasus_event_listener
while all of others are server-level. Migrated to new framework all of the metrics have become
replica-level; once server-level metrics are needed, just aggregate on replica-level ones.

feat(new_metrics): migrate replica-level metrics for pegasus_event_listener

---

src/server/pegasus_mutation_duplicator.cpp
src/server/pegasus_mutation_duplicator.h

https://github.com/apache/incubator-pegasus/issues/1412
Migrate replica-level metrics in pegasus_mutation_duplicator class to new
framework, including the numbers of successful/failed DUPLICATE requests
sent from mutation duplicator.

feat(new_metrics): migrate replica-level metrics for pegasus_mutation_duplicator

---

src/utils/metrics.cpp
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1414
Add server-level metric entity, including:
- Define server-level entity prototype in metrics.cpp;
- Implement getter to acquire the (only) instance of server entity;
- Provide convenient macros to simplify operations for server entity.

feat(new_metrics): add server-level metric entity

---

.github/workflows/regular-build.yml
run.sh

https://github.com/apache/incubator-pegasus/issues/1419
This patch fixes the regular build failure bug, and unify the steps of build by
gcc and clang in .github/workflows/regular-build.yml.

chore(CI): fix regularly build failure

---

src/nfs/nfs_client_impl.cpp
src/nfs/nfs_client_impl.h
src/nfs/nfs_server_impl.cpp
src/nfs/nfs_server_impl.h
src/nfs/test/CMakeLists.txt
src/server/pegasus_server_write.cpp

https://github.com/apache/incubator-pegasus/issues/1329
Migrate server-level metrics to new framework for both server/client sides
of nfs, including the data size in bytes that are requested by client or read
from local file in server, the number of nfs copy requests that fail for client
or server, the data size in bytes that are written to local file in client, the
number of failed writes to local file in client.
The old type in perf counters of all these metrics are volatile counter, while
all of them become accumulated counter for new metrics.

feat(new_metrics): migrate server-level metrics for nfs

---

src/common/fs_manager.cpp
src/common/fs_manager.h
src/replica/duplication/mutation_batch.h
src/replica/prepare_list.h
src/replica/replica_learn.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/replication_app_base.h
src/replica/split/replica_split_manager.cpp
src/replica/test/mock_utils.h
src/replica/test/replica_test.cpp

https://github.com/apache/incubator-pegasus/issues/1383
This patch fix some minor issues includes:
- short return id `FLAGS_fd_disabled` is true in `remove_replica_on_meta_server`
to avoid running meaningless logic
- encapsulate a new function `wait_closing_replicas_finished()` in `replica_stub`
- marks some functions as `const` or `override`
- marks some parameters or variables as `const`
- adds missing lock
- fixes some typos
- use short-circuit return style

refactor: minor refactor on replica module

---

src/meta/meta_backup_service.cpp
src/meta/meta_service.cpp
src/meta/meta_service.h
src/meta/server_state.cpp
src/meta/server_state.h
src/meta/server_state_restore.cpp
src/meta/test/meta_service_test.cpp
src/meta/test/meta_service_test_app.h
src/replica/CMakeLists.txt
src/replica/backup/test/CMakeLists.txt
src/runtime/ranger/ranger_resource_policy_manager.cpp
src/runtime/ranger/ranger_resource_policy_manager.h
src/runtime/security/access_controller.cpp
src/runtime/security/access_controller.h
src/runtime/security/meta_access_controller.cpp
src/runtime/security/meta_access_controller.h
src/runtime/test/meta_access_controller_test.cpp
src/runtime/test/ranger_resource_policy_manager_test.cpp
src/shell/CMakeLists.txt

This patch implements meta access controller using Ranger for ACL.
1. Re-implemented the access control logic of RPCs registered in `meta_serivce.h`, and adapt the old and new ACL.
2. Some internal RPCs are registered in the `_allowed_rpc_code_list`.
2. Realize periodic update of resource strategy from Ranger service.
3. Changed some ut.

feat(Ranger): Use Apache Ranger for meta access controller

---

src/replica/replication_app_base.cpp
src/replica/replication_app_base.h

https://github.com/apache/incubator-pegasus/issues/1383
The replica instance path will be removed to trash path, a.k.a
`<table_id>.<pid>.<timestamp>.err`, but it may not complete when
a replica server crash, then the path is left but some files
(e.g. `.init-info`) in the path have been moved. When restart
the server after that, server will crash because of a check on
existence of the files, which is not necessary, the server is
able to trash the corrupt path and start normally, the missing
replica can be recovered from other servers automatically.
This patch removes the check.

fix: log error but not crash if found an imcomplete replica path

---

src/common/fs_manager.cpp
src/common/fs_manager.h
src/common/test/CMakeLists.txt
src/meta/test/misc/misc.cpp
src/replica/replica_stub.cpp
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1425
In perf counters, all metrics of `fs_manager` are server-level. For example,
the total capacity and the available capacity of all disks where there are
data of pegasus.
However, sometimes the capacity and the available capacity of each disk
seem more important: no space left on the disk will lead to serious problems.
Therefore, after being migrated to new framework, the server-level metrics
of perf counters become disk-level, including the capacity and the available
capacity of a disk. As for another disk-level metric -- the available percentage
of each disk used by a replica server, just use division operator.
Once server-level metrics are needed, just aggregate on the disk-level ones.
To compute another 2 server-level metrics -- …

feat(new_metrics): add disk-level metric entity and migrate disk-level metrics for fs_manager

---

src/meta/meta_service.cpp
src/meta/meta_service.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1331
Migrate metrics to new framework for meta_service, including the number
of disconnections with replica servers, and the number of unalive and alive
replica servers. All of these metrics are server-level, maintained in meta
server.
The old type in perf counters of the number of disconnections is volatile
counter, which would be changed to non-volatile, while another 2 metrics
would keep the type of gauge.

feat(new_metrics): migrate server-level metrics for meta_service

---

src/meta/meta_backup_service.cpp
src/meta/meta_backup_service.h
src/meta/test/backup_test.cpp
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1331
In perf counters, there's only one metric for meta_backup_service, namely
the recent backup duration for each policy, which means this metric is
policy-level. Therefore policy-level entity would also be implemented in
new metrics.

feat(new_metrics): add backup-policy-level metric entity and migrate backup-policy-level metrics for meta_backup_service

---

src/meta/partition_guardian.cpp
src/meta/partition_guardian.h
src/meta/table_metrics.cpp
src/meta/table_metrics.h

https://github.com/apache/incubator-pegasus/issues/1331
In perf counters, there's only one metric for partition_guardian, namely
the number of operations that fail to choose the primary replica, which
is server-level. It would be changed to partition-level in new metrics
since this could give which partitions fail to choose primaries and how
frequency those happen. Still, to compute table-level or server-level
metrics just aggregate on partition-level ones.

feat(new_metrics): migrate partition-level metrics for partition_guardian

---

src/test/function_test/base_api_test/integration_test.cpp
src/test/function_test/utils/test_util.cpp
src/test/function_test/utils/test_util.h

https://github.com/apache/incubator-pegasus/issues/1383
Commit 9303c3aba87c8392705e52baeeee768ad385d5b3 introduced a flaky test, this
patch try to fix it.
This patch also introduce some integration test utils, they would be helpful
for following patches.

fix(ut): fix a flaky test integration_test.write_corrupt_db

---

go-client/pegasus/table_connector.go
go-client/pegasus/table_connector_test.go
go-client/session/session.go

fix #1385 
after replica server restart，The client should be able to reconnect with node without considering the client configuration update (reselecting the primary replica).
Actually, client configuration update is another issue we should talk about. I'd like to discuss that in another issue.
In this pr, we focus on why client cannot reconnect with restarted server.
1. SDK use several loop to monitor rpc.conn, when server is closed, `loopForDialing` will continue to retry dialling until connected with server(when server is restart),then,  two new loop `loopForRequest` & `loopForResponse`  will be created to handle request.
however,  `loopForRequest` will not return when correlative `loopForResponse`  returned because of IsNetworkClosed(EOF), since latter only return nil and will not …

fix(go-client): loopForRequest not return and retry forever

---

src/replica/replica_stub.cpp

This patch add ACL to the learn action of replica. 
1. specifically, regard learn as a write action, and use the Ranger 
policy to determine whether the master-slave can learn.

feat(Ranger): Use Apache Ranger for ACL when replica master-slave learn

---

src/utils/defer.h

Add function cancel() for class defer to cancel the callback, it's useful
if using defer to short circuit failures and cancel it after all conditions
passed.
For example:
```c++
auto cleanup = dsn::defer([this]() { release_db(); });
RETURN_NOT_OK(a);
RETURN_NOT_OK(b);
RETURN_NOT_OK(c);
cleanup.cancel();
```

feat(util): add cancel() for class defer

---

src/replica/replication_app_base.cpp
src/runtime/ranger/ranger_resource_policy_manager.cpp
src/utils/fmt_logging.h

Update `ERR_LOG_AND_RETURN_NOT_*` to `LOG_AND_RETURN_NOT_*` with a user
specified level, they would be more general to use.

refactor(log): make macros LOG_AND_RETURN_NOT_* more general

---

src/server/meta_store.cpp
src/server/meta_store.h
src/server/pegasus_server_impl.cpp
src/test/function_test/base_api_test/integration_test.cpp
src/test/function_test/config.ini
src/test/function_test/utils/global_env.cpp
src/test/function_test/utils/test_util.cpp
src/test/function_test/utils/utils.h
src/test_util/test_util.cpp
src/test_util/test_util.h
src/utils/fmt_logging.h

https://github.com/apache/incubator-pegasus/issues/1450
If replica server attempt to open an incomplete RocksDB instance (maybe caused
by a previous crash), it will crash before moving the incomplete path to ".err"
trash path, and it will crash again if restart the server.
This patch avoid to crash before moving the incomplete RocksDB path to ".err" path,
thus the replica has an opportunity to recovery automatically without move the
incomplete RocksDB path manually.

fix: fix a crash bug when open an incomplete created RocksDB instance

---

src/nfs/nfs.thrift
src/nfs/nfs_client_impl.cpp
src/nfs/nfs_node.cpp
src/nfs/nfs_node.h
src/nfs/nfs_node_impl.cpp
src/nfs/nfs_node_simple.h
src/nfs/nfs_server_impl.h
src/nfs/test/main.cpp
src/replica/replica.cpp
src/replica/replica.h
src/replica/replica_learn.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h

This patch add ACL to the NFS copy of replica.
1. Added `gpid` info to the data structure defined in `nfs.thrift`
2. Perform ACL through the Ranger policy matched by `gpid`
3. The registration of nfs is moved to `replica_stub.cpp`, and the original registration 
information is retained, which is convenient for testing

feat(Ranger): Use Apache Ranger for ACL when replica performs nfs copy

---

src/replica/replica.cpp
src/replica/replica.h
src/replica/replica_learn.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1454
This is the 2nd part of migrating metrics of `replica_stub` to new framework,
all of which are learn-related.
During this migration, there are 3 metrics still keeping server-level, including
the number of learning replicas, the max duration and the max size of files that
are copied from learnee among all learning replicas.
Another 11 metrics are changed from server-level to replica-level, since they
should be observed for each replica. All of them are observed from the view
of learners, namely the potential secondary replica. The learnee is the primary
replica. These metrics include: the number of learns launched by learner, the
number of learn rounds launched by learner (during a learn there might be
multiple rounds, the number of …

feat(new_metrics): migrate metrics for replica_stub (part 2)

---

src/replica/duplication/duplication_sync_timer.cpp
src/replica/duplication/replica_duplicator.cpp
src/replica/duplication/replica_duplicator.h
src/replica/duplication/replica_duplicator_manager.cpp
src/replica/duplication/replica_duplicator_manager.h
src/replica/replica.cpp
src/replica/replica.h
src/replica/replica_2pc.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/test/replica_test.cpp
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1454
This is the 4th part of migrating metrics of replica_stub to new framework.

feat(new_metrics): migrate metrics for replica_stub (part 4)

---

src/replica/replication_app_base.cpp

When `LOG_AND_RETURN_NOT_*` and `*_PREFIX` macros are used together, it's
not needed to add the prefix manually, otherwise the prefix will be printed
duplicated.
This patch removes the manually added prefixes.

fix(log): fix using of macro LOG_AND_RETURN_NOT_* print duplicate prefixes

---

src/meta/meta_http_service.cpp
src/meta/partition_guardian.cpp
src/server/pegasus_manual_compact_service.cpp
src/shell/commands/recovery.cpp
src/tools/mutation_log_tool.cpp
src/utils/process_utils.cpp
src/utils/test/time_utils_test.cpp
src/utils/time_utils.cpp
src/utils/time_utils.h

https://github.com/apache/incubator-pegasus/issues/1467
Because `fmt::format_to()` does not append a terminating null character, it
may cause garble words if not initialize the buffer's memory as zero.
This patch initialize all callers of `time_ms_to_string`'s buffer memory as zero.

fix: fix garble words of time filed in logs

---

src/runtime/rpc/dns_resolver.cpp
src/runtime/rpc/dns_resolver.h
src/runtime/rpc/rpc_address.cpp
src/runtime/rpc/rpc_address.h
src/runtime/rpc/rpc_host_port.cpp
src/runtime/rpc/rpc_host_port.h
src/runtime/test/host_port_test.cpp

issue: https://github.com/apache/incubator-pegasus/issues/1404
Implement of struct `dns_resolver ` in order to transfer 'host_port' to 'rpc_address'.
`rpc_address` is used to rpc communication.

feat(FQDN): Implemention of struct dns_resolver

---

src/replica/bulk_load/replica_bulk_loader.cpp
src/replica/bulk_load/replica_bulk_loader.h
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1454
This is the 6th part of migrating metrics of replica_stub to new framework,
all of which are bulk-load-related.
During this migration, there are 7 metrics which are changed from server-level
to replica-level, including the number of downloading/ingesting bulk loads, the
number of successful/failed bulk loads, the number of files that have been
downloaded successfully or have failed to be downloaded for bulk loads, the
size of files that have been downloaded successfully for bulk loads.
Another 3 metrics are still kept server-level, including the number of current
running bulk loads, the max duration of ingestions or the whole bulk loads.

feat(new_metrics): migrate metrics for replica_stub (part 6)

---

java-client/src/main/java/org/apache/pegasus/client/ListAppInfoType.java
java-client/src/main/java/org/apache/pegasus/client/PegasusAdminClient.java
java-client/src/main/java/org/apache/pegasus/client/PegasusAdminClientInterface.java
java-client/src/main/java/org/apache/pegasus/operator/list_apps_operator.java
java-client/src/main/java/org/apache/pegasus/rpc/async/MetaSession.java
java-client/src/test/java/org/apache/pegasus/client/TestAdminClient.java

https://github.com/apache/incubator-pegasus/issues/1470
add new interface `public List<app_info> listApps(ListAppInfoType listAppInfoType) throws PException` in `PegasusAdminClient.java` for get all app infos.
add ut `public void testListApps() throws PException` in `TestAdminClient.java`.
- Unit test

feat(java-client): add listApps interface

---

src/replica/duplication/duplication_pipeline.cpp
src/replica/duplication/duplication_pipeline.h
src/replica/duplication/load_from_private_log.cpp
src/replica/duplication/load_from_private_log.h
src/replica/duplication/mutation_batch.cpp
src/replica/duplication/mutation_batch.h
src/replica/duplication/test/load_from_private_log_test.cpp
src/server/pegasus_mutation_duplicator.cpp
src/server/pegasus_mutation_duplicator.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1481
Some duplication-related classes, including `ship_mutation`, `mutation_buffer`,
`load_from_private_log`, are migrated to the new framework.
During this migration, there are 6 metrics which are changed from server-level
to replica-level, all of which are duplication-related, including the shipped size of
private log, the number of times private log files have failed to be loaded, the bytes
of mutations that have been skipped due to failed loadings of private log files, the
size read from private log, the number of mutations read from private log, the number
of lost mutations recently.
Another 2 metrics, the numbers of failed/successful DUPLICATE requests sent from
client, are renamed according to the new style of naming for …

feat(new_metrics): migrate metrics for some duplication class

---

src/common/fs_manager.cpp
src/common/fs_manager.h
src/common/test/fs_manager_test.cpp
src/meta/test/misc/misc.cpp
src/replica/disk_cleaner.cpp
src/replica/disk_cleaner.h
src/replica/duplication/test/load_from_private_log_test.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/test/mock_utils.h
src/replica/test/mutation_log_test.cpp
src/replica/test/open_replica_test.cpp
src/replica/test/replica_disk_migrate_test.cpp
src/replica/test/replica_disk_test.cpp
src/replica/test/replica_disk_test_base.h
src/replica/test/replica_test_base.h
src/server/test/pegasus_server_test_base.h

https://github.com/apache/incubator-pegasus/issues/1383
This patch moves some functions to fs_manager which are more reasonable to be
responsibilities of class fs_manager rather than those of class replica_stub.

refactor: improve the single-responsibility of class fs_manager

---

.github/workflows/lint_and_test_cpp.yaml

https://github.com/apache/incubator-pegasus/issues/1485
Github actions `Build Release` and `Build with jemalloc` failed for the branch
`migrate-metrics-dev` due to running out of disk space. Both failed jobs would
pack servers and tools while another successful job `Build ASAN` would never
do.
After packaging, generated directories and tarballs would consume 2.7GB disk
space. Therefore, we could drop the generated directories and tarballs to spare
more disk space after packaging, though this problem has not been found for
master branch.
This problem is also tracked by another PR: https://github.com/apache/incubator-pegasus/pull/1484

chore(github): remove directories and tarballs after packing server and tools for github actions in case of running out of disk space

---

.github/workflows/lint_and_test_cpp.yaml

https://github.com/apache/incubator-pegasus/issues/1497
After `Build Release` and `Build with jemalloc` had failed due to running out of 
disk space (resolved by https://github.com/apache/incubator-pegasus/pull/1486)
for the branch `migrate-metrics-dev`, Github actions `Build ASAN` failed too due
to the same reason for the same branch.
It was found that `CMakeFiles` directories had occupied much disk space, about
3.4 GB. Once these directories were cleared, more space would be spared.
This problem is also tracked by another PR: https://github.com/apache/incubator-pegasus/pull/1491.

chore(github): remove CMakeFiles during Tar files in case of running out of disk space

---

.github/workflows/lint_and_test_cpp.yaml
src/replica/test/replica_disk_test_base.h
src/runtime/task/task_queue.cpp
src/utils/enum_helper.h
src/utils/metrics.h
src/utils/test/enum_helper_test.cpp

https://github.com/apache/incubator-pegasus/issues/1490
For the enum classes, such as metric type and unit, in addition to the declaration
of all enumerators, extra code is needed to implement `enum_to_string` for each
enumerator. However, the "extra code" tended to be forgotten, just as what has
been said in the above issue #1490.
Therefore, we should find a way that could share all the enumerators between
the declaration and `enum_to_string`. Each enumerator would be written only
once, and there is no need to remember to add `enum_to_string` for each
enumerator.
We could implement the "sharing" by function-like macros. They have the names
of all the enumerators, and accept an argument to perform custom actions over
the names to implement the "sharing". Both metric types and units would …

refactor(new_metrics): refactor enum definition for metric types and units

---

src/failure_detector/failure_detector.cpp
src/failure_detector/failure_detector.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1501
The only server-level metric of failure detector is migrated to the new framework,
i.e. the number of failed beacons sent by failure detector.

feat(new_metrics): migrate metrics for failure detector

---

src/runtime/ranger/ranger_resource_policy_manager.cpp
src/runtime/test/ranger_resource_policy_manager_test.cpp

- The access control management of RPC RPC_CM_LIST_APPS is removed from the global level resource, which is managed by the database resource.

feat(Ranger): remove ACL of RPC_CM_LIST_APPS from global resource

---

src/runtime/rpc/network.cpp
src/runtime/rpc/network.h
src/runtime/rpc/rpc_message.cpp
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1503
The only server-level gauge of network is split into 2 gauges, and migrated
to the new framework. The only gauge is a metric about TCP connections:
from client side, the network could connect to different remote servers;
while from server side, it could receive connections from remote clients.
In the past, the only gauge has been used to measure either the number of
different remote servers from client side, or the number of different remote
clients from server side, which might result in confusion. Therefore, it's better
to split the only gauge into 2 individual ones.

feat(new_metrics): migrate metrics for network

---

run.sh

https://github.com/apache/incubator-pegasus/issues/1493
This is a cherry-pick commit to branch v2.4.
Fix rhe bug of "pegasus_server: error while loading shared libraries: libdsn_replica_server.so: cannot open shared object file: No such file or directory". It's because that the libjvm.so is not added to $LD_LIBRARY_PATH.

fix: fix start_onebox failed because of libjvm.so not found (#1494)

---

src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/pegasus_server_impl_init.cpp
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1505
All of the server-level metrics of rocksdb are migrated to the new framework,
including 2 metrics: the memory usage of block cache, and the through bytes
per second that go through the rate limiter which takes control of the write rate
of flush and compaction.
This migration are somewhat different from previous ones:
- firstly, both metrics are declared as static variables;
- then, both variables need to be defined globally;
- also, both metrics have to be initialized by assignment operator, rather than in
the member initializer lists of the constructor of user class.
To support all of these new features, some new macros are introduced.

feat(new_metrics): migrate server-level metrics of rocksdb

---

src/runtime/profiler.cpp
src/runtime/profiler_header.h

https://github.com/apache/incubator-pegasus/issues/1508
Since in https://github.com/XiaoMi/rdsn/pull/810, profiler-related remote
commands have been removed , `counter_info` and `counter_info_ptr`
have no longer been used since then. Thus could remove both of them.

refactor: remove counter_info and counter_info_ptr

---

collector/avail/detector.go
collector/config.yml
collector/main.go
collector/metrics/meta_server_metrics.go
collector/metrics/metric_collector.go
collector/metrics/replica_server_metrics.go
collector/sink/falcon_sink.go
collector/sink/prometheus_sink.go
collector/sink/sink.go

Related issue: https://github.com/apache/incubator-pegasus/issues/1206
This patch collects all raw metric data from pegasus, aggregate them into table/server/cluster level and sinks them into prometheus. If the type of the metric is replica partition, it will be aggregated into cluster level table metric.
If the type of the metric is table, it will be aggregated into cluster level table metric, it also will be aggregated into server level table metric.
If the type of the metric is server, it will be aggregated into cluster level table metric, it also will be sinked into prometheus directly.
Currently, this patch supports 3 type of prometheus metric types: counter, gauge, summary.
- Unit test
- No code
- Has exported …

feat: Aggregate table/server level metrics

---

run.sh

issue: https://github.com/apache/incubator-pegasus/issues/1520
fix invaild macro `CMAKE_BUILD_TYPE`
(`debug` -> `Debug`, `release` -> `Release`)

fix: fix invaild build type

---

src/common/fs_manager.h
src/runtime/profiler.cpp
src/runtime/profiler_header.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1523
Profiler-level metric entity is introduced and 12 profiler-related metrics are
migrate to the new framework, including the number of tasks in all queues,
the number of tasks that have been executed, the number of cancelled tasks,
the latency it takes for each task to wait in each queue before beginning to be
executed, the latency it takes for each task to be executed, the latency from
enqueue point to reply point on the server side for each RPC task, the non-timeout
latency from call point to enqueue point on the client side for each RPC task,
the body length of request received or response replied on the server side for
each RPC task, the accumulative number of dropped RPC tasks on the server
side, the accumulative number of timeout …

feat(new_metrics): migrate metrics for profiler

---

src/runtime/profiler.cpp
src/runtime/profiler_header.h

https://github.com/apache/incubator-pegasus/issues/1527
Maintained in an array that includes all of the profilers, each profiler is
indexed and accessed by its task code. Therefore, `TASK_CODE_INVALID`,
albeit meaningless, should also be pushed into this array; otherwise, all
of the profiled tasks would be indexed by the wrong task code, then also
measured by the wrong metrics.

fix(new_metrics): profiled tasks are measured by the wrong metrics

---

src/replica/replica.cpp
src/replica/replica.h

https://github.com/apache/incubator-pegasus/issues/1327
Remove all table-level metrics that are measured by perf-counters. Later,
table-level metrics would be aggregated by Go Collector, if necessary.

feat(new_metrics): remove all table-level perf-counters for each replica

---

.github/workflows/lint_and_test_cpp.yaml
run.sh
src/server/config.min.ini
src/test/function_test/config.ini
src/test/function_test/run.sh
src/test/function_test/throttle_test/test_throttle.cpp

https://github.com/apache/incubator-pegasus/issues/1529
Options used by onebox and function tests are made configurable. The default
values for these options are unchanged. Once custom options are provided as
the arguments of `run.sh`, these custom options would be used to substitute
for the current configurations. Github workflow for cpp has used custom options
to reduce the consumption of disk space.
On the other hand, to solve the problem that `throttle_test` failed frequently
fundamentally, `throttle_test` should be refactored: at the end of each test
case, onebox for each replica server should be stopped and the data should
be cleared to release the disk space. This is tracked by another issue:
https://github.com/apache/incubator-pegasus/issues/1534

fix(github): throttle_test failed frequently due to insufficient disk space

---

src/replica/mutation_log.cpp
src/replica/mutation_log.h

https://github.com/apache/incubator-pegasus/issues/1532
In https://github.com/apache/incubator-pegasus/pull/1462, all metrics of
shared log have been removed. However, there are still some perf-counters
that are used in shared log. All of them should be removed.

refactor(new_metrics): remove perf-counters that are still used in shared log

---

.github/workflows/lint_and_test_cpp.yaml
run.sh
src/common/fs_manager.cpp
src/meta/meta_backup_service.cpp
src/meta/table_metrics.cpp
src/replica/replica_base.cpp
src/runtime/profiler.cpp
src/runtime/task/task_queue.cpp
src/utils/latency_tracer.cpp
src/utils/latency_tracer.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1536
The only metric of latency tracer, namely the duration between two points
(stages), is migrated to the new framework:
- latency tracer entity is introduced as the new metric entity to which the
metric is attached;
- create new class that bind each entity and manage the metric;
- create new class that manage all entity instances, with a read-write lock
that helps improving the performance of search for the target entity;
- solve the problem of "No space left on device" for Build ASAN temporarily.

feat(new_metrics): migrate metrics for latency tracer

---

.devcontainer/devcontainer.json
.licenserc.yaml

Related issue: https://github.com/apache/incubator-pegasus/issues/1549
Support developing inside a container, ref: https://code.visualstudio.com/docs/devcontainers/containers
So that we can develop and compile Pegasus in a docker environment.
I can successfully compile the code in my WSL2 environment.

build: add a devcontainer.json

---

docker/pegasus-build-env/ubuntu1804/Dockerfile

https://github.com/apache/incubator-pegasus/issues/1559
Fix the error of `pip3 install --no-cache-dir cmake`

fix(docker): fix pegasus-build-env of ubuntu:18.04 Dockerfile

---

.github/workflows/lint_and_test_cpp.yaml
src/server/config.ini
src/server/rocksdb_wrapper.cpp

https://github.com/apache/incubator-pegasus/issues/1562
Add this option to turn off rocksdb modifying `rocksdb.external_sst_file.global_seqno`
field of external sst file during ingest process. This is used to address a coredump
caused by incorrect field value in RocksDB. This pull request fixs the bug above.
Rocksdb 6.6.4 no longer recommends using this field.
```diff
[pegasus.server]
+ rocksdb_write_global_seqno = false
```

Fix write global seqno

---

.asf.yaml

https://github.com/apache/incubator-pegasus/issues/1408
Add ruojieranyishen and ninsmiracle as collaborators.

chore(github): add some contributors into apache collaborators to allow them to use github actions

---

src/utils/simple_logger.cpp

https://github.com/apache/incubator-pegasus/issues/1572
If the logs are called in FATAL level, the process should exit.

fix(logs): fix logs in FATAL level not take effect

---

src/replica/replica_stub.cpp

https://github.com/apache/incubator-pegasus/issues/1572
Add an option to make it possible to exit the process and leave the
corrupted slog and replicas to be handled by the administrator when
open slog failed.

fix(slog): add an option to exit the process when find slog error

---

src/client/replication_ddl_client.cpp
src/meta/test/backup_test.cpp
src/server/result_writer.cpp
src/utils/fmt_logging.h
src/utils/simple_logger.cpp
src/utils/simple_logger.h
src/utils/test/logging.cpp

https://github.com/apache/incubator-pegasus/issues/1579
Following fixes are included in this PR to solve the problems:
- support core dump for fatal logging in `simple_logger::dsn_logv`;
- call fatal logging exactly once for the assertion macros `CHECK*`;
- add fail point to keep the logging test running without termination.

fix: support core dump for fatal logging in simple_logger::dsn_logv and call fatal logging exactly once for the assertion

---

.github/workflows/lint_and_test_cpp.yaml

https://github.com/apache/incubator-pegasus/issues/1576
In the workflow that builds pegasus with jemalloc, more space could be
freed after packaging is tested.

chore(github): free disk space after packaging with jemalloc in github workflows

---

.github/workflows/regular-build.yml

https://github.com/apache/incubator-pegasus/issues/1585
Free more disk space for daily building cpp by referring to https://github.com/apache/incubator-pegasus/pull/1577.
Test has been run manually on [Lint and build regularly](https://github.com/apache/incubator-pegasus/actions/workflows/regular-build.yml) for the branch [free-regular-disk-space](https://github.com/apache/incubator-pegasus/tree/free-regular-disk-space).

chore(github): free disk space for daily building on github

---

src/meta/meta_backup_service.cpp
src/meta/meta_data.cpp
src/meta/partition_guardian.cpp
src/meta/test/backup_test.cpp
src/replica/replica.cpp
src/replica/replica_2pc.cpp
src/runtime/task/task.cpp
src/server/pegasus_server_impl.cpp

https://github.com/apache/incubator-pegasus/issues/1587
Fix some wrong format string in logging and macro that are:
- still using c-style format string, which would not print the correct messages;
- calling `to_string()` method for the classes which have implemented `operator<<`.

fix: fix errors in format string for logging and macro

---

.github/workflows/lint_and_test_cpp.yaml
.github/workflows/thirdparty-regular-push.yml
docker/pegasus-build-env/centos7/Dockerfile
docker/pegasus-build-env/ubuntu1804/Dockerfile
docker/pegasus-build-env/ubuntu2004/Dockerfile
docker/pegasus-build-env/ubuntu2204/Dockerfile
scripts/pack_server.sh
thirdparty/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1348
Now that we drop supporting CentOS, this path reverts commit 862c824231bcc8309444e62d7b2d40523c8ea742.

Revert "build(thirdparty): add thirdparty for centos6 build env  (#1017)"

---

docker/thirdparties-bin/Dockerfile
docker/thirdparties-src/Dockerfile

https://github.com/apache/incubator-pegasus/issues/1604
Explicit set PORTABLE=native to avoid building failure. The failure looks like:
```
cc1plus: error: bad value ('OFF') for '-march=' switch
cc1plus: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7
westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell
skylake skylake-avx512 bonnell atom silvermont slm knl x86-64 eden-x2 nano nano-1000
nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64
athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1
btver2
```

fix(docker): fix build failure of rocksdb when PORTABLE=0

---

.github/workflows/lint_and_test_cpp.yaml
.github/workflows/thirdparty-regular-push.yml

https://github.com/apache/incubator-pegasus/issues/1604
Prior to this patch, the `thirdparties-bin-test-${OS}-${branch}` docker images are
only built for Ubuntu 18.04 for CI purpose, but some CI jobs use Ubuntu 22.04 image,
it may cause the CI failed because the Ubuntu 22.04 image is outdated (for example,
lack of or outdated of some thirdparties).
This patch unify to build and use `thirdparties-bin-test-2204-${branch}` docker image.

chore(CI): unify to use Ubuntu 22.04 for CI

---

thirdparty/CMakeLists.txt

This patch changes Pegasus to use the `v8.5.3-pegasus-encrypt` branch of
https://github.com/pegasus-kv/rocksdb.git repository.
The `v8.5.3-pegasus-encrypt` branch is based on the official `v8.5.3` tag of
facebook/rocksdb repository but adds the encryption feature which is implemented
by the Pegasus team.
There is nothing changed if not enable the encryption feature.

build(thirdparty): use v8.5.3-pegasus-encrypt branch of pegasus-kv/rocksdb

---

thirdparty/CMakeLists.txt

Set option -DWITH_OPENSSL=ON to build rocksdb with encryption feature enabled.

feat(build): build RocksDB with encryption enabled

---

thirdparty/CMakeLists.txt

Fix a build error on lower OpenSSL version, the error looks like:
```
2023-09-19T02:53:45.4093185Z #11 924.7 /root/incubator-pegasus/thirdparty/build/Source/rocksdb/encryption/encryption.cc: In function 'const EVP_CIPHER* rocksdb::encryption::GetEVPCipher(rocksdb::encryption::EncryptionMethod)':
2023-09-19T02:53:45.4094191Z #11 924.7 /root/incubator-pegasus/thirdparty/build/Source/rocksdb/encryption/encryption.cc:112:44: error: cannot convert 'rocksdb::Status' to 'const EVP_CIPHER* {aka const evp_cipher_st*}' in return
2023-09-19T02:53:45.4094713Z #11 924.7            std::string(OPENSSL_VERSION_TEXT));
2023-09-19T02:53:45.4094991Z #11 924.7                                             ^
2023-09-19T02:53:45.5599505Z #11 924.7 …
```

fix(rocksdb): update rocksdb to fix build failure on lower OpenSSL version

---

src/aio/test/CMakeLists.txt
src/block_service/test/CMakeLists.txt
src/client/test/CMakeLists.txt
src/common/test/CMakeLists.txt
src/failure_detector/test/CMakeLists.txt
src/http/test/CMakeLists.txt
src/meta/CMakeLists.txt
src/nfs/test/CMakeLists.txt
src/perf_counter/test/CMakeLists.txt
src/replica/backup/test/CMakeLists.txt
src/replica/duplication/test/CMakeLists.txt
src/test_util/test_util.h
src/utils/CMakeLists.txt
src/utils/env.cpp
src/utils/env.h
src/utils/filesystem.cpp
src/utils/filesystem.h
src/utils/fmt_logging.h
src/utils/long_adder_bench/CMakeLists.txt
src/utils/test/CMakeLists.txt
src/utils/test/env.cpp
src/utils/test/file_system_test.cpp
src/utils/test/nth_element_bench/CMakeLists.txt
src/zookeeper/test/CMakeLists.txt

This patch introduces `PegasusEnv()` to obtain the `Env` instance used by RocksDB. Then
it's possible to obtain an encrypted Env instance by `PegasusEnv(FileDataType::kSensitive)`,
the encrypted Env is used for operating on sensitive files, the writing data to the file
will be encrypted and the reading data from the file will be decrypted.
Some file operate functions and related unit tests are added as well.

feat(encryption): introduce PegasusEnv

---

src/block_service/local/local_service.cpp
src/block_service/local/local_service.h
src/block_service/test/local_service_test.cpp
src/meta/meta_bulk_load_service.h
src/test/function_test/bulk_load/CMakeLists.txt
src/test/function_test/bulk_load/test_bulk_load.cpp

There is no functional changes, but only refactor the bulk_load function test.

refactor(test): refactor bulk load function test

---

src/replica/duplication/load_from_private_log.cpp
src/replica/duplication/load_from_private_log.h
src/replica/duplication/test/duplication_test_base.h
src/replica/log_file.cpp
src/replica/log_file.h
src/replica/mutation_log.cpp
src/replica/mutation_log.h
src/replica/mutation_log_replay.cpp
src/replica/mutation_log_utils.cpp
src/replica/mutation_log_utils.h
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/replication_app_base.cpp
src/replica/test/mock_utils.h
src/replica/test/mutation_log_test.cpp
src/server/config.ini
src/server/pegasus_server_impl.cpp
src/server/test/config.ini
src/utils/autoref_ptr.h
src/utils/fmt_logging.h

https://github.com/apache/incubator-pegasus/issues/1593
In https://github.com/XiaoMi/rdsn/pull/1019 we've written private logs as
WAL instead of shared logs, which also means shared log files would never
be appended with new mutations.
However, obsolete shared logs that had been applied to rocksdb were not
removed since then. There is at least 1 shared log file which is never removed.
We should change this policy of garbage collection, to delete all obsolete
shared log files.
To facilitate the garbage collection of shared log files, we also trigger checkpoints
which would flush rocksdb data to disk for each replica that has prevented shared
log files from being removed for garbage collection. It is necessary to limit the
number of submitted replicas that would be flushed at a time to …

feat(slog): flush and remove all shared logs for garbage collection

---

src/aio/native_linux_aio_provider.cpp
src/aio/test/aio.cpp

There is no functional changes, but only refactor the aio unit test.
The `aio_pwrite_incomplete` fail point injection has been removed, it's useless in
the following aio refactor.

refactor(aio_test): refactor aio unit test

---

src/block_service/local/CMakeLists.txt
src/block_service/local/local_service.cpp
src/block_service/test/local_service_test.cpp
src/replica/CMakeLists.txt
src/utils/env.cpp
src/utils/env.h

There is no functional changes, but only refactor the local service and related unit test.
And now FLAGS_enable_direct_io takes effect on local block service.

refactor(local_service): use rocksdb API to read/write file

---

src/replica/bulk_load/replica_bulk_loader.cpp
src/replica/replica_restore.cpp
src/server/pegasus_write_service_impl.h
src/utils/filesystem.cpp
src/utils/filesystem.h
src/utils/test/file_system_test.cpp
src/utils/test/file_utils.cpp

There is no functional changes, but only refactor the files read/write method
of filesystem module.

refactor(file_system): use rocksdb API to read/write file

---

src/replica/bulk_load/replica_bulk_loader.cpp
src/utils/filesystem.cpp
src/utils/filesystem.h

Remove `read_file()` and `write_file()` from `dsn::utils::filesystem` namespace.

refactor(file_system): remove useless read/write_file()

---

.licenserc.yaml
src/block_service/block_service.h
src/geo/bench/bench.cpp
src/meta/test/main.cpp
src/nfs/nfs_node_simple.cpp
src/nfs/nfs_node_simple.h
src/nfs/nfs_server_impl.cpp
src/nfs/nfs_server_impl.h
src/server/test/pegasus_server_impl_test.cpp
src/test/function_test/base_api/test_copy.cpp

This patch includes changes:
- Set default values of fields of structre `upload_response` and `file_handle_info_on_server`.
- Call `close_service()` when `nfs_node_simple::stop()`.
- Code refactor for nfs_server_impl.cpp.
- Check the start and stop status of the service in pegasus_server_impl_test.cpp.
- Add some comments.
- Fix typos.

refactor: some minor refactors without functional changes

---

.github/workflows/lint_and_test_cpp.yaml
src/block_service/test/hdfs_service_test.cpp
src/test_util/test_util.h

https://github.com/apache/incubator-pegasus/issues/1631
Add retry logic for test `HDFSClientTest.test_rename_path_while_writing`, fix an
used-after-free ASAN issue and remove tar files after downloading from artifacts
to reduce space consumption.

fix(ut): fix flaky unit test test_rename_path_while_writing

---

thirdparty/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1604
In pegasus, both [prometheus-cpp](https://github.com/jupp0r/prometheus-cpp)
and [http client](https://github.com/apache/incubator-pegasus/pull/1583) are
based on [libcurl](https://curl.se/libcurl/c/).
Above all, an important version 8.4.0 for libcurl, which has fixed severity HIGH
security problem(https://github.com/curl/curl/discussions/12026), would be
released in Oct 11.
Therefore, we should bump libcurl from 7.47.0 to 8.4.0.

build(thirdparty): bump libcurl from 7.47.0 to 8.4.0

---

src/utils/filesystem.cpp
src/utils/filesystem.h
src/utils/test/file_utils.cpp

- Remove the useless return value of `get_normalized_path()`
- Simplify the code of file_utils.cpp

refactor(filesystem): refactor file_utils unit tests

---

src/aio/CMakeLists.txt
src/aio/aio_provider.h
src/aio/disk_engine.cpp
src/aio/disk_engine.h
src/aio/file_io.cpp
src/aio/file_io.h
src/aio/native_linux_aio_provider.cpp
src/aio/native_linux_aio_provider.h
src/aio/test/CMakeLists.txt
src/aio/test/aio.cpp
src/aio/test/config.ini
src/meta/meta_state_service_simple.cpp
src/nfs/nfs_client_impl.cpp
src/nfs/nfs_server_impl.cpp
src/replica/duplication/test/load_from_private_log_test.cpp
src/replica/log_file.cpp
src/replica/storage/simple_kv/simple_kv.server.impl.cpp
src/replica/storage/simple_kv/test/simple_kv.server.impl.cpp
src/replica/test/mutation_log_test.cpp
src/runtime/test/CMakeLists.txt
src/runtime/test/task_test.cpp
src/test_util/test_util.cpp
src/test_util/test_util.h
src/utils/long_adder_bench/long_adder_bench.cpp
src/utils/test/env.cpp

This is a dependent work to implement encryption at rest, we can use the capacity of
rocksdb encryption after this patch.
- Use rocksdb APIs to implement class `native_linux_aio_provider`. Both of the
implementations are using `pread()` and `pwrite()` system calls, so there isn't
significant performance changes, see the newly added simple benchmark performance
comparation below.
- Separate the file read and write operations for class `aio_provider`

feature(aio): use rocksdb APIs to re-implement the aio module

---

.github/workflows/lint_and_test_cpp.yaml

https://github.com/apache/incubator-pegasus/issues/1642
Remove release tarballs before unit tests in case there is no space left on device,
referring to https://github.com/apache/incubator-pegasus/pull/1630.

chore(github): remove release tarballs to free more disk space for unit tests

---

run.sh

https://github.com/apache/incubator-pegasus/issues/1645
This patch is to disable AddressSanitizerOneDefinitionRuleViolation, see
https://github.com/google/sanitizers/issues/1017 for details.
This PR is to cherry-pick #1611 into v2.5 to solve issue #1645.

fix(ASAN): avoid reporting false 'odr-violation' issues (cherry-pick #1611)

---

cmake_modules/BaseFunctions.cmake
src/meta/meta_service.cpp

https://github.com/apache/incubator-pegasus/issues/1647
The standard followed by [v2.5](https://github.com/apache/incubator-pegasus/tree/v2.5)
would be C++14. However, Compilation on MacOS failed due to some errors, such as:
- no member named 'make_unique' in namespace 'std'
- initialized lambda captures are a C++14 extension
- 'ext/alloc_traits.h' file not found
Most of the errors are about C++14. `cmake` directives should be fixed to make C++14
compilation on MacOS work well.

fix(build): fix compilation error on MacOS for C++14

---

src/replica/duplication/load_from_private_log.cpp
src/replica/duplication/load_from_private_log.h
src/replica/duplication/test/duplication_test_base.h
src/replica/log_file.cpp
src/replica/log_file.h
src/replica/mutation_log.cpp
src/replica/mutation_log.h
src/replica/mutation_log_replay.cpp
src/replica/mutation_log_utils.cpp
src/replica/mutation_log_utils.h
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/replication_app_base.cpp
src/replica/test/mock_utils.h
src/replica/test/mutation_log_test.cpp
src/server/config.ini
src/server/pegasus_server_impl.cpp
src/server/test/config.ini
src/utils/autoref_ptr.h
src/utils/fmt_logging.h

https://github.com/apache/incubator-pegasus/issues/1593
In https://github.com/XiaoMi/rdsn/pull/1019 we've written private logs as
WAL instead of shared logs, which also means shared log files would never
be appended with new mutations.
However, obsolete shared logs that had been applied to rocksdb were not
removed since then. There is at least 1 shared log file which is never removed.
We should change this policy of garbage collection, to delete all obsolete
shared log files.
To facilitate the garbage collection of shared log files, we also trigger checkpoints
which would flush rocksdb data to disk for each replica that has prevented shared
log files from being removed for garbage collection. It is necessary to limit the
number of submitted replicas that would be flushed at a time to …

feat(slog): flush and remove all shared logs for garbage collection (cherry-pick #1594)

---

.github/workflows/standardization_lint.yaml

https://github.com/apache/incubator-pegasus/issues/1551
Remove the "Check issue" from Standardization Lint because it makes other
linter failed becuse the action `neofinancial/ticket-check-action@v1.3.0`
is not allowed for Apache repos.
In fact, the issue checker is just an optional, we shall keep the pull
requests description clarify when submit or update, but an issue link is
not necessary.

chore(CI): remove the "Check issue" from Standardization Lint

---

.github/workflows/standardization_lint.yaml

https://github.com/apache/incubator-pegasus/issues/1551
Remove the "Check issue" from Standardization Lint because it makes other
linter failed becuse the action `neofinancial/ticket-check-action@v1.3.0`
is not allowed for Apache repos.
In fact, the issue checker is just an optional, we shall keep the pull
requests description clarify when submit or update, but an issue link is
not necessary.
This PR is to cherry-pick #1652 into v2.5 to solve issue #1551.

chore(CI): remove the "Check issue" from Standardization Lint (cherry-pick #1652)

---

docker/pegasus-build-env/ubuntu1804/Dockerfile

https://github.com/apache/incubator-pegasus/issues/1654
Fix the DL3042 warning by adding `--no-cache-dir`.

fix(CI): Fix the "Lint Dockerfile" action failure

---

docker/pegasus-build-env/ubuntu1804/Dockerfile

https://github.com/apache/incubator-pegasus/issues/1654
Fix the DL3042 warning by adding `--no-cache-dir`.

fix(CI): Fix the "Lint Dockerfile" action failure (cherry-pick #1656)

---

java-client/scripts/ci-test.sh
scala-client/scripts/ci-test.sh

https://github.com/apache/incubator-pegasus/issues/1663
Scala client depends on java client. Before java client is built, thrift sources
should be generated.

fix(scala-client): generate thrift sources for scala client

---

src/server/hotkey_collector.cpp

The hotkey log should not redacted when encrytion are at set.
Modify ‘c_escape_sensitive_string’ back to ‘c_escape_string’
- Unit test

fix(log): not redacted hotkey log

---

java-client/pom.xml
nodejs-client/package.json
python-client/pypegasus/__init__.py
scala-client/build.sbt
src/client_lib/mutation.cpp
src/include/pegasus/version.h

Upgrade the version of pegasus server and clients:
- upgrade the version to 2.5.0-SPAPSHOT for cpp server, java and scala client;
- upgrade the version to 2.5.0 for python and nodejs client;
- no need to upgrader version for go client, since it has been bound to git branch.
All of the server and clients would be released on [v2.5](https://github.com/apache/incubator-pegasus/tree/v2.5).

chore(version): update the version of pegasus server and client of each language to 2.5.0

---

java-client/scripts/ci-test.sh
scala-client/scripts/ci-test.sh

https://github.com/apache/incubator-pegasus/issues/1663
Scala client depends on java client. Before java client is built, thrift sources
should be generated.
This PR is to cherry-pick #1662 into v2.5 to solve issue #1663.

fix: generate thrift sources for scala client (cherry-pick #1662)

---

java-client/pom.xml
nodejs-client/package.json
python-client/pypegasus/__init__.py
scala-client/build.sbt
src/client_lib/mutation.cpp
src/include/pegasus/version.h

Upgrade the version of pegasus server and clients:
- upgrade the version to 2.5.0-SPAPSHOT for cpp server, java and scala client;
- upgrade the version to 2.5.0 for python and nodejs client;
- no need to upgrader version for go client, since it has been bound to git branch.
All of the server and clients would be released on [v2.5](https://github.com/apache/incubator-pegasus/tree/v2.5).
This PR is to cherry-pick #1660 into v2.5.

chore(version): update the version of pegasus server and client of each language to 2.5.0 (cherry-pick #1660)

---

NOTICE

This PR is to cherry-pick #1671 into v2.5.

chore: update NOTICE year to 2023 (cherry-pick #1671)

---

.licenserc.yaml
LICENSE
scripts/check_license.py

https://github.com/apache/incubator-pegasus/issues/1676
There are several tasks/steps for this PR:
- develop a script to check the consistency between `.licenserc.yaml` and all files of the project.
- according to the check result, fix `.licenserc.yaml`.
- according to the fixed `.licenserc.yaml`, amend `LICENSE`.
License checker could be run just by `python3 scripts/check_license.py`.
This PR is to cherry-pick #1674 into v2.5 to solve issue #1676.

chore(license): add license checker for copyright and fix license files (cherry-pick #1674)

---

thirdparty/CMakeLists.txt

Introduce abseil as thridparty for using abseil_strings method  
Abseil LTS 20230802.1 is introduced to thridparty/CMakelist.txt and to complie.
kms key manager client need to use Abseil_strings some methods.

feat(thirdparty): Introduce abseil

---

src/client/replication_ddl_client.cpp

This is a patch to simplify code, also to check whether the previous patch(5e9a2a9dcaa8be988e1ea8e745bd7fc8621e2609) works.
Note: In `{{{}}}`, `{{` and `}}` are used to escape, the left `{}` is used for `replacement fields`, see https://fmt.dev/latest/syntax.html.
Manual tests of the shell:
```
>>> ls_backup_policy
[1]
name                  : p1
backup_provider_type  : local_service
backup_interval       : 86400s
app_ids               : {1}
start_time            : 01:00
status                : enabled
backup_history_count  : 10
...
[3]
name                  : p3
backup_provider_type  : local_service
backup_interval       : 86400s
app_ids               : {1, 2}
start_time            : 01:00
status                : enabled
backup_history_count  : 10
ls backup policy succeed
>>> …
```

refactor: use fmt:join to simplify code

---

scripts/pack_server.sh
scripts/pack_tools.sh
thirdparty/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1604
Upgrade gperftools to 2.13 which is the latest release.

chore(thirdparty): Bump gperftools to 2.13

---

src/http/pprof_http_service.cpp

In https://github.com/XiaoMi/rdsn/pull/433, we updated the way to get heap profile
by using
```
HeapProfilerStart(...);
sleep(seconds);
GetHeapProfile();
HeapProfilerStop();
```
instead of
```
MallocExtension::instance()->GetHeapSample(...);
```
It provides a way to analyse which pieces of code allocated (and possibly freed)
how much memory during the time the request processed on the server. However, in
the scenario of a server already in heavy memory consumption but growing very
slow, it's hard to tell which pieces of code allocated the most of the memory.
This patch adds the heap sampling back, and keep the heap profiling as well.
Both of the two ways are using the `pprof/heap` method, the difference is whether
the `seconds` parameter appears.
When the `seconds` parameter appears, …

feat(pprof): Supports both heap profiling and heap sampling

---

src/http/http_client.cpp
src/http/http_client.h
src/http/http_method.h
thirdparty/CMakeLists.txt

The key manager get eek from kms should set CURLOPT_HTTPAUTH with negotiate.
compile libcurl with gssapi
- No code
src/http/http_client.cpp
src/http/http_client.h
src/http/http_method.h
thirdparty/CMakeLists.txt

feat(thirdparty): compile curl with gssapi

---

run.sh

This is a compromised method to resolve the crash in `stacktrace_generic_fp` as
mentioned in https://github.com/apache/incubator-pegasus/issues/1685.
Remember to set the enviroment variable `TCMALLOC_STACKTRACE_METHOD` to other value if
you see this crash stack in your enviroment.
I will reseach more about this issue to fix it fully.

fix: use libgcc instead of generic_fp as default stacktrace

---

admin-cli/client/meta.go
admin-cli/go.sum

https://github.com/apache/incubator-pegasus/issues/1698
Do not set the `backupPath` field of `StartBackupAppRequest` if it's not set
to avoid an `ERR_INVALID_PARAMETERS` error from server. The error is caused
by a conflict check on server side between `StartBackupAppRequest.backupPath`
and `[block_service.hdfs_service].{args}`, the latter has defined a default
backup path.

fix(admin-cli): fix the command reports incorrect ERR_INVALID_PARAMETERS error

---

src/client/replication_ddl_client.cpp

- Print `hint_message` when `add_backup_policy`, `disable_backup_policy`,
`enable_backup_policy` or `update_backup_policy` failed. The hint messages
are currently used in admin-cli only.
- Return corresponding error code when `query_restore` failed.

feat(ddl_client): add failure logs when backup or restore commands failed

---

run.sh
src/server/config.ini

This patch adds `hdfs_service` related configs to `src/server/config.ini`, and
add an option `--hdfs_service_args` to `start_onebox` command of `run.sh`.

feat(HDFS): Add hdfs_service related configs in server.ini and run.sh

---

.licenserc.yaml
HISTORY.md

Add a new file `HISTORY.md` to record the change log of each version. The change log of version 2.5 is firstly added.

chore: add change log for version 2.5

---

.github/workflows/lint_and_test_cpp.yaml
run.sh
scripts/config_hdfs.sh

When run Pegasus to use the feature of backup data to HDFS (restore data from
HDFS is the same), it's needed to set the CLASSPATH enviroment variables, now
it is done by scripts/config_hdfs.sh. However, we have to source this script
manually before starting onebox.
This patch sources the script in ./run.sh automatically, updates config_hdfs.sh
to download hadoop package is it's not exist, and removes explicilt calling of
scripts/config_hdfs.sh in CI.

feat: source config_hdfs.sh automatically before starting onebox

---

.github/workflows/labeler.yml

https://github.com/actions/labeler/releases/tag/v5.0.0 has an imcompatible
changes of the config file, this patch use the v4 to keep compatiblity.

chore(CI): Use actions/labeler@v4 to keep compatiblity

---

.github/workflows/build-push-env-docker.yml
.github/workflows/thirdparty-regular-push.yml
docker/README.md
docker/ci-env/Dockerfile
docker/pegasus-docker-compose/README.md
docker/pegasus-docker-compose/build_docker.sh
docker/pegasus-docker-compose/image_for_prebuilt_bin/Dockerfile
docker/thirdparties-bin/Dockerfile
docker/thirdparties-src/Dockerfile

Since build-env-* images should be built for released versions and master branch, we could append branch name to the tag to create image for each branch.

build(images): append branch name to the tag of each build-env-* image to support building image for each branch

---

.github/workflows/labeler.yml

https://github.com/actions/labeler/releases/tag/v5.0.0 has an imcompatible
changes of the config file, this patch use the v4 to keep compatiblity.
This PR is to cherry-pick #1711 into v2.5.

chore(CI): use actions/labeler@v4 to keep compatiblity (cherry-pick #1711)

---

.github/workflows/build-push-env-docker.yml
.github/workflows/thirdparty-regular-push.yml
docker/README.md
docker/ci-env/Dockerfile
docker/pegasus-docker-compose/README.md
docker/pegasus-docker-compose/build_docker.sh
docker/pegasus-docker-compose/image_for_prebuilt_bin/Dockerfile
docker/thirdparties-bin/Dockerfile
docker/thirdparties-src/Dockerfile

Since build-env-* images may vary for different releases, they should
be built for released and master branches. We need to append branch
name to the tag to create image for each branch.
This PR is to cherry-pick #1763 into v2.5.

build(images): append branch name to the tag of each build-env-* image to support building image for each branch (cherry-pick #1763)

---

docker/pegasus-build-env/ubuntu1804/Dockerfile

https://github.com/apache/incubator-pegasus/issues/1559
Fix the error of `pip3 install --no-cache-dir cmake`
This PR is to cherry-pick #1558 to solve #1559.

fix(docker): fix pegasus-build-env of ubuntu:18.04 Dockerfile (cherry-pick #1558)

---

.github/workflows/standardization_lint.yaml
docker/pegasus-build-env/centos6/Dockerfile
docker/pegasus-build-env/centos7/Dockerfile

https://github.com/apache/incubator-pegasus/issues/1347
Fix error "ImportError: No module named skbuild" while building CentOS 6 and 7.
This PR is to cherry-pick #1356 to solve #1347.
The reported error is:
```
#15 [11/13] RUN pip install --no-cache-dir cmake
#15 1.602 Collecting cmake
#15 2.225   Downloading https://files.pythonhosted.org/packages/3e/6b/76ca411a4317bdc0012de597c245a59c824aef1f71dd83e8de0b5ec9bc32/cmake-3.27.9.tar.gz (42kB)
#15 2.325     Complete output from command python setup.py egg_info:
#15 2.325     Traceback (most recent call last):
#15 2.325       File "<string>", line 1, in <module>
#15 2.325       File "/tmp/pip-build-56Lgw_/cmake/setup.py", line 8, in <module>
#15 2.325         from skbuild import setup
#15 2.325     ImportError: No module named skbuild
#15 …
```

fix: fix centos image build (cherry-pick #1356)

---

src/block_service/local/local_service.cpp
src/block_service/local/local_service.h
src/block_service/test/local_service_test.cpp

Add function `dump_to_file` and `load_from_file` to class `file_metadata` to
dump the object to a file in JSON format and load the object from a file in
JSON format.

refactor(local_service): minor refactor on file_metadata

---

.gitignore
run.sh
src/block_service/local/local_service.h
src/test/function_test/backup_restore/test_backup_and_restore.cpp
src/test/function_test/base_api/integration_test.cpp
src/test/function_test/base_api/test_batch_get.cpp
src/test/function_test/base_api/test_copy.cpp
src/test/function_test/base_api/test_scan.cpp
src/test/function_test/bulk_load/CMakeLists.txt
src/test/function_test/bulk_load/test_bulk_load.cpp
src/test/function_test/restore/test_restore.cpp
src/test/function_test/utils/test_util.cpp
src/test/function_test/utils/test_util.h

Before this patch, the Pegasus function test `bulk_load_test` will download
files from external site, it may break some ASF policies.
This patch make the test to generate bulk load test files internally, it make
the procedure transparent to developers, know what key-values are generated and
bulk loaded.

refactor(function_test): Generate bulk load files internally

---

src/shell/commands/debugger.cpp

https://github.com/apache/incubator-pegasus/issues/1772
Building jobs for Ubuntu 1804, CentOS 7 and clang-9 failed due to
"fatal error: filesystem: No such file or directory #include <filesystem>"
while the Action `Lint and build regularly` was run on Github.
The compiler versions of Ubuntu 1804, CentOS 7 and clang-9 are
gcc 7.5.0, gcc 7.3.1 and clang 9. All of these versions do not support
including `<filesystem>` header file and using `std::filesystem`. The
minimum compiler versions that support `std::filesystem` are gcc 8
and clang 10.

fix: use boost::filesystem::path instead of std::filesystem::path to be compatible with lower gcc/clang versions

---

thirdparty/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1339
RocksDB library is not built in Release version, which may cause terrible performance issues.
This PR is to cherry-pick #1340 into v2.4 to resolve #1339.

fix: fix rocksdb build type (cherry-pick #1340)

---

java-client/pom.xml
java-client/src/test/java/org/apache/pegasus/base/TestRpcAddress.java
java-client/src/test/java/org/apache/pegasus/client/PegasusScannerTest.java
java-client/src/test/java/org/apache/pegasus/client/TestAdminClient.java
java-client/src/test/java/org/apache/pegasus/client/TestBasic.java
java-client/src/test/java/org/apache/pegasus/client/TestBatch.java
java-client/src/test/java/org/apache/pegasus/client/TestBatchGetByPartitions.java
java-client/src/test/java/org/apache/pegasus/client/TestBench.java
java-client/src/test/java/org/apache/pegasus/client/TestCheckAndMutate.java
java-client/src/test/java/org/apache/pegasus/client/TestCheckAndSet.java
java-client/src/test/java/org/apache/pegasus/client/TestFutureGroup.java
java-client/src/test/java/org/apache/pegasus/client/TestIncr.java
java-client/src/test/java/org/apache/pegasus/client/TestMultiThread.java
java-client/src/test/java/org/apache/pegasus/client/TestNoOperate.java
java-client/src/test/java/org/apache/pegasus/client/TestPException.java
java-client/src/test/java/org/apache/pegasus/client/TestPing.java
java-client/src/test/java/org/apache/pegasus/client/TestPingZK.java
java-client/src/test/java/org/apache/pegasus/client/TestTimeout.java
java-client/src/test/java/org/apache/pegasus/metrics/MetricsPoolTest.java
java-client/src/test/java/org/apache/pegasus/operator/ClientOperatorTest.java
java-client/src/test/java/org/apache/pegasus/rpc/async/ClusterManagerTest.java
java-client/src/test/java/org/apache/pegasus/rpc/async/InterceptorTest.java
java-client/src/test/java/org/apache/pegasus/rpc/async/MetaSessionTest.java
java-client/src/test/java/org/apache/pegasus/rpc/async/ReplicaSessionTest.java
java-client/src/test/java/org/apache/pegasus/rpc/async/TableHandlerTest.java
java-client/src/test/java/org/apache/pegasus/rpc/async/TimeoutBenchmark.java
java-client/src/test/java/org/apache/pegasus/security/NegotiationTest.java
java-client/src/test/java/org/apache/pegasus/tools/TestZstdWrapper.java
java-client/src/test/resources/simplelogger.properties

The test of java client are using junit3 and junit4 in the same time. It should change to use junit5 uniformly.
1. Change the java client test import and usage for uniformly junit5. Such as deprecated 'Assert' from usage of junit3. 
2. upgrader junit version to 5.9.3，use junit.api  and junit.jupiter.engine 
3. introduce org.hamcrest for some test
4. fix slf4j-api dependency prombles
- Unit test 
only java client unit test
pom.xml have some jar dependency problems. Exclude slf4j-api from libthrift、zookeeper、metrics-core

fix(java-client): use junit5 instead of junit3/junit4

---

scripts/pack_server.sh

https://github.com/apache/incubator-pegasus/issues/1792
Now that snappy/zstd/lz4 has not been the direct dependencies
of Pegasus(actually all of them is the dependency of rocksdb),
just remove them from pack_server.sh.

fix(scripts): drop unnecessary dependencies for pack_server.sh

---

scripts/pack_server.sh

https://github.com/apache/incubator-pegasus/issues/1795
Add dynamic library of rocksdb as the dependency of the executable binary.

fix(scripts): fix that librocksdb.so.8 was not found for the executable binary generated by pack_server.sh

---

.github/workflows/lint_and_test_cpp.yaml
scripts/pack_server.sh
thirdparty/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1805
After building was finished, sometimes librocksdb.so* would be output into
the directory `lib64` rather than `lib`, which would lead to an error that
librocksdb.so* could not be found while packing server.
To solve this problem, just specify the output dir for librocksdb.so*.

fix(rocksdb): force librocksdb.so* to be output into the directory 'lib'

---

src/replica/storage/simple_kv/test/simple_kv.server.impl.cpp
src/utils/simple_logger.cpp
src/utils/simple_logger.h

https://github.com/apache/incubator-pegasus/issues/1807
Implement `dsn_log` interface for `screen_logger` in case that there is
not any logging message being printed and the process is not terminated,
while invalid values for the options loaded from configuration file are found,
or some other errors occur that would make assertions fail.

fix(logger): logs fail to be printed to stdout and the process is not terminated for fatal errors before logging is initialized

---

.github/workflows/lint_and_test_cpp.yaml
run.sh

Now it's possible to build partial objects by specifying "-m obj1,obj2" parameter to `./run.sh build`.

feat(run.sh): make it possible to build partial objects

---

src/replica/replica_2pc.cpp
src/runtime/security/sasl_init.cpp
src/runtime/task/task_spec.h
src/utils/api_utilities.h
src/utils/fmt_logging.h
src/utils/logging.cpp
src/utils/logging_provider.h
src/utils/simple_logger.cpp
src/utils/simple_logger.h
src/utils/test/endian_test.cpp
src/utils/test/logger.cpp
src/utils/test/logging.cpp

Refactor the logging system, including:
- drop the unnecessary interface `logging_provider::dsn_logv()`
- change `dsn_log` or `dlog` to `log` for the naming of logging-related
macros, functions, classes, types and variables
- improve the tests for the logging and fix the bug that the whole
utils test directory is removed after utils tests are finished.

refactor(logging): drop the unnecessary interface, use `log` instead of `dsn_log` and improve the tests

---

cmake_modules/BaseFunctions.cmake
src/meta/CMakeLists.txt
src/meta/meta_http_service.cpp
src/utils/api_utilities.h
src/utils/metrics.h

https://github.com/apache/incubator-pegasus/issues/1817
If meta server is built without testing(i.e. `./run.sh build` without `--test`),
the macro `MOCK_TEST` dedicated to test code should not be enabled,
which might lead to unexpected behaviors.
On the other hand, meta server should not exit abnormally with core
dump even if it is built for testing(i.e. `./run.sh build --test`). Once it
finds that balancer is not initialized by mocking, it should go through
the normal process to prevent from core dump.

fix: standby meta server exits abnormally with core dump after receiving the http request `/meta/cluster`

---

src/replica/replica.cpp

Don't log "client read encountered an unhandled error: 1" when the key is not found.

fix(logging): remove too verbose log when key not found

---

cmake_modules/BaseFunctions.cmake

Mute errors like the follows, the Pegasus codebase will be checked by clang-format, so it's safe to enable the CMake option (-Wno-misleading-indentation).
```
```

fix(build): Fix Cpp build errors in recent github actions

---

src/block_service/local/local_service.cpp
src/block_service/local/local_service.h
src/block_service/test/local_service_test.cpp
src/replica/bulk_load/replica_bulk_loader.cpp
src/replica/bulk_load/replica_bulk_loader.h
src/replica/bulk_load/test/replica_bulk_loader_test.cpp
src/replica/replica_disk_migrator.cpp
src/replica/replica_restore.cpp
src/replica/replication_app_base.cpp
src/replica/replication_app_base.h
src/test/function_test/bulk_load/CMakeLists.txt
src/test/function_test/bulk_load/test_bulk_load.cpp
src/utils/filesystem.cpp
src/utils/fmt_logging.h
src/utils/load_dump_object.h
src/utils/test/load_dump_object_test.cpp

This patch mainly refactoring the objects load and dump functions.
There are 2 types of objects, one is using DEFINE_JSON_SERIALIZATION macro to make the object
can be converted to/from JSON string which corresponding to RapidJson, the other is using
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE macro which corresponding to NlohmannJson. So there are 2
types of functions (i.e. load_rjobj_from_file/dump_rjobj_to_file and
load_njobj_from_file/dump_njobj_to_file).
This patch refactor the code to use the newly added functions to do the operations, and also
add some unit tests.

refactor(json_file): Refactor the load and dump functions of JSON objects

---

.github/workflows/lint_and_test_collector.yml
collector/README.md
collector/go.mod
collector/main.go
collector/sink/falcon_sink.go
collector/sink/prometheus_sink.go
collector/sink/sink.go
collector/usage/usage_recorder.go
collector/webui/index.go

- Update collector README
- Update the url from github.com/pegasus-kv/collector to github.com/apache/incubator-pegasus/collector
- Add fmt job for collector CI

chore(collector): Add fmt job for collector CI

---

src/runtime/task/task.h
src/utils/CMakeLists.txt
src/utils/metrics.cpp
src/utils/metrics.h
src/utils/test/metrics_test.cpp

https://github.com/apache/incubator-pegasus/issues/1820
Labels are needed by metric models like Prometheus Data Model.
Therefore, cluster name, role name, host name and port should be
provided in the response to metrics query as the labels. All of these
fields would be added in the form of name/value pairs of json object.
Original entity array would be the value of a json object with name
"entities".

feat(new_metrics): add some basic fields to the response to metrics query

---

.github/workflows/lint_and_test_java-client.yml
java-client/README.md
java-client/src/test/java/org/apache/pegasus/client/TestBasic.java
java-client/src/test/java/org/apache/pegasus/rpc/async/ReplicaSessionTest.java
java-client/src/test/java/org/apache/pegasus/tools/Toollet.java

Fix the failed java-client tests, and improve some the code style, including:
- Install `net-tools` which is needed by test tool Toollet.java, it use `netstat`
to find some processes.
- Improve the flaky test testOperationTimeout.
- Use an independent hashkey for testScanRangeWithValueExpired to avoid
conflicts.
- Improve some code style.
- Update the README.md.

fix(java-client): Fix the failed java-client test

---

src/test/function_test/recovery/test_recovery.cpp
src/test/function_test/utils/test_util.cpp
src/test/function_test/utils/test_util.h

Issue: https://github.com/apache/incubator-pegasus/issues/1838
match the behavior of A and B in meta_server_list

fix: specify ambiguous meta_server_list on recovery_test

---

src/client/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1846
The module `replication_ddl_client` in `libdsn_client.a` has referenced
thrift-generated objects, which are included in `libdsn_replication_common.a`
Thus, `libdsn_replication_common.a` should be linked privately to
`libdsn_client.a`.

fix(build): fix undefined reference to thrift-generated objects while linking libdsn_client.a

---

src/redis_protocol/proxy_lib/proxy_layer.cpp
src/redis_protocol/proxy_lib/redis_parser.cpp
src/utils/fmt_logging.h

- Introduce macros LOG_WARNING_IF_PREFIX and LOG_ERROR_IF_PREFIX
- Use the *_PREFIX serial macros to simplify code in Redis proxy module

refactor(log): Use *_PREFIX macros to simplify code

---

scripts/pack_server.sh
scripts/pack_tools.sh

https://github.com/apache/incubator-pegasus/issues/1848
Copy `libtcmalloc_and_profiler.so.4` instead of `libtcmalloc_and_profiler.so`
while packaging binaries and libraries, otherwise tcmalloc library in package
would never be linked while running Pegasus.

fix(tcmalloc): add the version number as the missing postfix for libtcmalloc_and_profiler.so.* otherwise it would never be linked

---

.github/workflows/lint_and_test_cpp.yaml
run.sh
src/common/test/run.sh
src/meta/test/run.sh
src/replica/backup/test/run.sh
src/replica/bulk_load/test/run.sh
src/replica/duplication/test/run.sh
src/replica/split/test/run.sh
src/replica/storage/simple_kv/run.sh
src/replica/storage/simple_kv/test/run.sh
src/replica/test/run.sh
src/server/test/run.sh
src/test/function_test/run.sh

Now options in TEST_OPTS  are separated by comma. However, some
options contains commas itself. We could use semicolon instead of
comma. 
- Change comma in opts of some unit tests to colon.
- Change TEST_OPTS replacement method.

refactor(test): use semicolon instead of comma to separate each option in TEST_OPTS

---

src/http/http_client.cpp
src/http/http_client.h
src/http/test/http_client_test.cpp
src/utils/enum_helper.h

There are multiple components for a URL used to issue http requests,
such as scheme, host, port, path and query. However, to build each
URL by such components, we could assemble them into a string only
by fmt::format or concatenating them together with some separators.
This PR is to provide a class named http_url that help build URLs on
demand. Just specify each component we need to http_url, then
extract the URL string. We could set the extracted the URL string,
or just set http_url object itself to http client to tell what is the URL
for the http requests.

feat(http_client): add http_url class to help build URLs for http client

---

src/zookeeper/zookeeper_session.cpp

https://github.com/apache/incubator-pegasus/issues/1863

feat: Support meta_server connect to Kerberos sasl authenticated Zookeeper where KDC configured 'rdns = false'

---

src/http/http_server.cpp
src/http/http_server.h
src/utils/CMakeLists.txt
src/utils/metrics.cpp
src/utils/metrics.h
src/utils/strings.cpp
src/utils/strings.h
src/utils/test/metrics_test.cpp
src/utils/test/utils.cpp

Pegasus shell needs to fetch metrics by http client. However, building query
string is not simple. You have to write each field name yourself, and assemble
all field names/values into a valid query string.
To simplify this operation, we could allow metric filters to support exporting
the query string. Users could just set conditions they need to metric filters,
then get the query string just by a function conveniently.

feat(new_metrics): build the http query string based on metric filters

---

src/runtime/rpc/dns_resolver.cpp
src/runtime/rpc/dns_resolver.h
src/runtime/rpc/rpc_host_port.cpp

The DNS resolve function maybe slow, and the memory size of dns_resolver is
not limited currently, this patch adds 3 useful metrics to improve observability:
- dns_resolver_cache_size
- dns_resolver_resolve_duration_ns
- dns_resolver_resolve_by_dns_duration_ns

feat(dns_resolver): Add metrics for dns_resolver

---

run.sh
scripts/pack_tools.sh

https://github.com/apache/incubator-pegasus/issues/1886
Fix some problems while launching shell by `/path/to/tools/run.sh shell ...`
on production environment:
- `src/shell/config.ini` could not be found since `run.sh` was executed with
absolute path rather than relative path
- `pegasus_shell` binary could not be found for the packaged directory by
`pack_tools` which tends to used on production environment
- packaged libraries such as `libdsn_replica_server.so` could not be found
since the directory of libraries are missing in `LD_LIBRARY_PATH`
- while loading shared libraries `librocksdb.so.8` was not found which has
not be packaged into tools

fix(shell): add missing librocksdb.so.8 while packing tools and fix errors while launching shell

---

run.sh

https://github.com/apache/incubator-pegasus/issues/1895
Error occurred that config file was not found while launching Pegasus
bench. The reason is that the tools is packaged by `pack_tools` for
production environment, where `build/latest/output` could not be found
since it is only used for local test environment.

fix(shell): allow bench to be launched for the directory packaged by `pack_tools` on production environment

---

src/common/json_helper.h
src/runtime/rpc/group_host_port.h
src/runtime/rpc/rpc_host_port.cpp
src/runtime/rpc/rpc_host_port.h
src/runtime/test/host_port_test.cpp
src/utils/test/json_helper_test.cpp

This patch mainly has cchanges:
- Change the constructor `host_port(rpc_address addr)` to a static function
`host_port from_address(rpc_address addr)`. It's a good practice to keep
constructors light and fast, this function contains a reverse DNS lookup,
it may be slow.
- Change `bool from_string(const std::string &s)` to a static function
`host_port from_string(const std::string &host_port_str)` in host_port.
It seems there isn't a scenario to modify an exist host_port object by
calling obj.from_string(s), so make it as static to clarify this.
This patch also adds SCOPED_LOG_SLOW_EXECUTION to log slow operations if it
exceed 100 milliseconds.

refactor(host_port): Make some functions as static

---

src/meta/duplication/duplication_info.h
src/meta/duplication/meta_duplication_service.cpp
src/replica/duplication/replica_duplicator.h
src/replica/duplication/replica_follower.h
src/replica/replication_app_base.cpp
src/replica/replication_app_base.h
src/replica/storage/simple_kv/simple_kv.app.example.h
src/replica/storage/simple_kv/test/case.cpp
src/replica/storage/simple_kv/test/case.h
src/replica/storage/simple_kv/test/common.cpp
src/replica/storage/simple_kv/test/common.h
src/runtime/task/task_engine.cpp
src/shell/commands/data_operations.cpp
src/shell/commands/debugger.cpp
src/shell/commands/node_management.cpp
src/shell/commands/rebalance.cpp
src/shell/commands/recovery.cpp
src/shell/commands/table_management.cpp
src/utils/latency_tracer.cpp

There is no functional changes, but only refactor to simplify the code.

refactor(fmt): Use operator<< instead of explict to_string() (2nd)

---

scripts/pack_tools.sh

https://github.com/apache/incubator-pegasus/issues/1900
Now that snappy/zstd/lz4 has not been the direct dependencies
of Pegasus(actually all of them is the dependency of rocksdb),
just remove them from pack_tools.sh.

fix(scripts): drop unnecessary dependencies for pack_tools.sh

---

src/common/replication_common.cpp
src/common/replication_common.h
src/meta/app_balance_policy.cpp
src/meta/meta_service.cpp
src/meta/meta_service.h
src/meta/partition_guardian.cpp
src/meta/partition_guardian.h
src/meta/server_state.cpp
src/meta/test/meta_test_base.cpp
src/meta/test/meta_test_base.h
src/meta/test/update_configuration_test.cpp
src/nfs/nfs_client_impl.cpp
src/nfs/nfs_server_impl.cpp
src/replica/backup/cold_backup_context.cpp
src/replica/bulk_load/replica_bulk_loader.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/utils/command_manager.cpp
src/utils/command_manager.h

- Simplify the registration of boolean remote command, now it can be registered
by `ommand_manager::register_bool_command(bool &value, const std::string &command, const std::string &help)`
- Change the type of `node_live_percentage_threshold_for_update` from
uint64 to int32, there is no impact bacause it's a percentage which
is range in [0, 100].
- Change the type of `replica_assign_delay_ms_for_dropouts` from uint64
to int64, there is less impact bacause int64 is big enough to set a
milliseconds time interval (maximum to 106751991167 days).
- Change the type of `max_copy_rate_megabytes_per_disk`,
`max_send_rate_megabytes_per_disk` to int64, there is no impact
bacause its range is enlarged.
- Use FLAGS_max_concurrent_bulk_load_downloading_count directly and remove
it from …

refactor(command_manager): Simplify command_manager code

---

scripts/config_hdfs.sh
src/block_service/hdfs/hdfs_service.cpp

Resolve https://github.com/apache/incubator-pegasus/issues/1913.
Reduces the use of operating system signals by the JVM by exporting
LIBHDFS_OPTS="-Xrs" to resolve the issue of unexpected exit order of
JVM threads and Pegasus threads.
See details: https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html

fix(hdfs): export LIBHDFS_OPTS=-Xrs to ensure server could exit normally

---

src/shell/command_helper.h
src/shell/commands/data_operations.cpp
src/shell/commands/node_management.cpp
src/shell/commands/table_management.cpp
src/utils/metrics.cpp
src/utils/metrics.h
src/utils/string_conv.h

This is the 1st part of migrating metrics for `app_stat` to new framework,
since there are many (59) metrics to be migrated and both table-level and
partition-level should be supported.
Since `app_stat` command has more dimensions for stats, i.e. table id and
partition id, an abstract class `aggregate_stats` is introduced to allow users
to perform their self-defined aggregations on fetched metrics.

feat(new_metrics): show table stats by shell `app_stat` command based on new metrics (part 1)

---

src/shell/command_helper.h
src/shell/commands/node_management.cpp

This is the 2nd part of migrating metrics for `app_stat` to new framework,
implementing partition-level aggregations for a specific table.

feat(new_metrics): show table stats by shell `app_stat` command based on new metrics (part 2)

---

src/security/negotiation.cpp
src/zookeeper/zookeeper_session.cpp

Reference:
zookeeper 3.7 client
https://github.com/apache/zookeeper/blob/branch-3.7/zookeeper-client/zookeeper-client-c/src/cli.c
Notes:
If you want to use kerberos zookeeper before, you just need to set [security]
enable_zookeeper_kerberos to "true" and do some kerberos configurations. 
After this commit, you also need to set [zookeeper] sasl_mechanisms_type
to "GSSAPI". Otherwise, you'll get an error log prompting you to make changes.
Some configurations are added:
```diff
[zookeeper]
sasl_service_name = zookeeper
sasl_service_fqdn =
sasl_mechanisms_type =
sasl_user_name =
sasl_realm =
sasl_password_file =
```

refactor: optimize zookeeper client init for sasl

---

src/shell/command_helper.h

Support more metrics new for both table-level and replica-level
aggregations (sums and increases), including throttling, splitting,
bulk load ingestion and RocksDB.

feat(new_metrics): show table stats by shell `app_stat` command based on new metrics (part 3)

---

src/shell/command_helper.h

Support more metrics new for both table-level and replica-level
aggregations (sums and increases), including RocksDB and the
bytes of each read/write requests. Now all of the metrics that
should be supported have been added.

feat(new_metrics): show table stats by shell `app_stat` command based on new metrics (part 4)

---

src/shell/command_helper.h
src/shell/commands/node_management.cpp
src/shell/commands/table_management.cpp
src/shell/main.cpp

Support specifying `sample_interval_ms` options while executing
commands `app_stat` and `nodes`, to give the custom duration
while aggregating rates on stats.

feat(shell): support options `sample_interval_ms` for shell `app_stat` and `nodes` commands

---

CMakeLists.txt
thirdparty/CMakeLists.txt

https://github.com/apache/incubator-pegasus/issues/1927
Since `DOWNLOAD_EXTRACT_TIMESTAMP` was introduced in version 3.24,
the minimum required version of cmake should be increased from 3.11.0 to
3.24.0. The document of the website would also be updated.

fix(cmake): increase the minimum required version of cmake to 3.24.0

---

java-client/src/main/java/org/apache/pegasus/client/ClientOptions.java
java-client/src/main/java/org/apache/pegasus/client/retry/DefaultRetryPolicy.java
java-client/src/main/java/org/apache/pegasus/client/retry/ExponentialBackoffRetryPolicy.java
java-client/src/main/java/org/apache/pegasus/client/retry/RetryPolicies.java
java-client/src/main/java/org/apache/pegasus/client/retry/RetryPolicy.java
java-client/src/main/java/org/apache/pegasus/rpc/async/ClientRequestRound.java
java-client/src/main/java/org/apache/pegasus/rpc/async/ClusterManager.java
java-client/src/main/java/org/apache/pegasus/rpc/async/ReplicaSession.java
java-client/src/main/java/org/apache/pegasus/rpc/async/TableHandler.java
java-client/src/test/java/org/apache/pegasus/client/retry/TestDefaultRetryPolicy.java
java-client/src/test/java/org/apache/pegasus/client/retry/TestExponentialBackoffRetryPolicy.java

Introduces a retry mechanism into the Java client to enhance user
convenience and robustness.
It can be enabled by calling `retryPolicy()`, `retryBaseInterval()`
and `retryMaxTimes()` in when construct ClientOptions objects.

feat(java-client): Introduce exponentialBackoff retry mechanism

---

src/client/partition_resolver.cpp
src/client/partition_resolver.h
src/client/partition_resolver_simple.cpp
src/client/partition_resolver_simple.h

Make get_partition_index() as public accessable, then we can reuse it in
CLI tools, for example https://github.com/apache/incubator-pegasus/pull/1930.

refactor(partition_resolver): Make get_partition_index() as public accessable

---

src/replica/replica_stub.cpp
src/utils/blob.h

This patch fixes the bug of the garbage partition with pidx of N is missing
gargabed after partition split function aborted on the table which has N
partitions.
Also add a small convenient function `bool empty()` for class blob.

fix(partition_split): Fix the missing garbage partition

---

docker/pegasus-build-env/centos7/Dockerfile

https://github.com/apache/incubator-pegasus/issues/1940
The problem is that docker image for compilation environment failed to be built due to "cannot verify archive.apache.org's certificate":
```
#8 [4/6] RUN wget --progress=dot:giga https://archive.apache.org/dist/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz -P /opt/maven     && cd /opt/maven     && tar -zxf apache-maven-3.8.3-bin.tar.gz     && rm apache-maven-3.8.3-bin.tar.gz
#8 0.086 --2024-03-08 08:48:50--  https://archive.apache.org/dist/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
#8 0.092 Resolving archive.apache.org (archive.apache.org)... 65.108.204.189, 2a01:4f9:1a:a084::2
#8 0.124 Connecting to archive.apache.org (archive.apache.org)|65.108.204.189|:443... connected.
#8 0.479 ERROR: cannot verify …
```

fix(image): enable verifying certificate for CentOS 7

---

src/shell/command_executor.h
src/shell/command_helper.h
src/shell/commands.h
src/shell/commands/local_partition_split.cpp
src/shell/main.cpp

This patch introduces a new CLI tool `local_partition_split`, which is used
to split the local partitions offline.
Similar to the online partition split feature, it's helpful to split the
table which has large amount of data but with a few partitions into more
partitions to improve the throughput and lower latency.
Besides, this tool is possible to be used on older Pegasus versions, if you
want to do that, it's necessary to cherr-pick this patch to the corresponding
older branch and rebuild the tool, then this tool will use corresponding
version of RocksDB library to generate new replicas.

feat(local_partition_split): Add local_partition_split CLI tool

---

src/meta/greedy_load_balancer.cpp
src/meta/greedy_load_balancer.h

After scaling out, Pegasus determines whether the shards are balanced by checking if the balance operation counts are equal to 0. However, since the meta server returns counts = 0 when it cannot collect all replicas information, this leads to the premature termination of balancing. Therefore, in such cases, the counts should be equal to -1
A new bool variable  introduce into class greedy_load_balancer to control balance operation count whether be -1.
```
class greedy_load_balancer{
private:
bool _all_replca_infos_collected;
}
```

fix(balance): Distinguish cluster balanced or collecting balance info interruptted

---

src/replica/duplication/duplication_sync_timer.cpp
src/replica/duplication/duplication_sync_timer.h
src/replica/duplication/test/duplication_sync_timer_test.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h

Actually both `get_all_primaries()` and `get_all_replicas()` are operating the members
of `replica_stub`, thus it's better to move both of them to `replica_stub`. See also
https://github.com/apache/incubator-pegasus/pull/1608.

refactor(duplication): move get_all_replicas/get_all_primaries from duplication_sync_timer to replica_stub

---

src/replica/duplication/duplication_sync_timer.cpp
src/replica/replica.cpp
src/replica/replica.h

It is not safe to get `_duplication_mgr` as raw pointer or `std::unique_ptr`. For example,
`r->close()`would be called in `replica_stub::close_replica` without protection of any lock.
Once `_duplication_mgr.reset()` is called in `replica::close()`(`r->close()`), `std::unique_ptr`
or raw pointer would become `nullptr`, which is not thread-safe among multiple threads.
Since `_duplication_mgr` might be called and reset in different threads, it's better to use
`std::shared_ptr` instead. See also https://github.com/apache/incubator-pegasus/pull/1608.

fix(duplication): get duplication manager as shared_ptr in case raw pointer has been reset to null

---

src/http/builtin_http_calls.cpp
src/http/config_http_service.cpp
src/http/http_server.cpp
src/http/http_server.h
src/http/pprof_http_service.cpp
src/http/pprof_http_service.h
src/http/test/http_server_test.cpp
src/http/test/main.cpp
src/meta/meta_http_service.cpp
src/meta/meta_http_service.h
src/replica/replica_http_service.h
src/utils/flags.cpp
src/utils/metrics.cpp

This patch improves the help description of HTTP APIs.
Before this patch, the path and parameters are output. The path is duplicate
because we can obtain all the paths directly (e.g. `curl 127.0.0.1:34601/`).
After this patch, the help description is more readable and we don't have to
maintain the website docs, e.g.
```
$ curl 127.0.0.1:34601/
{
"/": "List all supported calls.",
"/config": "name=<config_name>. Gets the details of a specified config. Only the configs which are registered by DSN_DEFINE_xxx macro can be queried.",
"/configs": "List all configs. Only the configs which are registered by DSN_DEFINE_xxx macro can be queried.",
"/meta/app": "name=<app_name>[&detail]. Query app info.",
"/meta/app/duplication": "name=<app_name>. Query app duplication info.", …
```

refactor(HTTP): Improve the help description of HTTP APIs

---

src/common/backup_common.cpp
src/common/backup_common.h
src/replica/replica_stub.cpp

Behavior changes:
Change the checkpoint directory name in remote storage system (e.g. HDFS)
from chkpt_<ip>_<port> to chkpt_<host>_<port>.

feat(FQDN): Use chkpt_<host>_<port> as the backup path

---

src/runtime/rpc/rpc_message.cpp

fix(message_ex): Fix the crash caused by message_ex::copy() in server internally

---

src/meta/test/backup_test.cpp
src/meta/test/balancer_simulator/balancer_simulator.cpp
src/meta/test/balancer_validator.cpp
src/meta/test/meta_data.cpp
src/meta/test/meta_duplication_service_test.cpp
src/meta/test/meta_partition_guardian_test.cpp
src/meta/test/meta_test_base.cpp
src/meta/test/misc/misc.cpp
src/meta/test/misc/misc.h
src/meta/test/state_sync_test.cpp
src/meta/test/update_configuration_test.cpp

Simplify the 2 forms of generate_node_list(...), they are widely used in
tests, they generate a std::vector with std::pair<host_port, rpc_address>
before, this patch simplify the code to generate std::vector with host_host
elements only.

refactor(FQDN): Simplify function generate_node_list()

---

src/client/partition_resolver_manager.cpp
src/client/partition_resolver_simple.cpp
src/client/replication_ddl_client.cpp
src/common/replication_common.cpp
src/common/replication_other_types.h
src/meta/meta_data.h
src/meta/server_state.cpp
src/meta/test/balancer_validator.cpp
src/meta/test/meta_bulk_load_service_test.cpp
src/meta/test/update_configuration_test.cpp
src/replica/bulk_load/replica_bulk_loader.cpp
src/replica/replica.h
src/replica/replica_config.cpp
src/replica/replica_context.cpp
src/replica/replica_stub.cpp
src/replica/storage/simple_kv/test/checker.cpp
src/replica/storage/simple_kv/test/common.cpp
src/runtime/global_config.cpp
src/runtime/rpc/group_address.h
src/runtime/rpc/group_host_port.h
src/shell/commands/data_operations.cpp
src/shell/commands/node_management.cpp
src/shell/commands/table_management.cpp
src/utils/metrics.h
src/utils/utils.h

This patch includes minor refactor works:
- Unify to use underscore naming (xxx_xxx_xxx) instead of camel case naming
- Redude if-else depth for pieces of code
- Rename some variable names because of variable shadowing
- Introduce `utils::contains` to simplify code

refactor: Fix some clang warnings

---

idl/duplication.thrift
src/client/replication_ddl_client.cpp
src/client/replication_ddl_client.h
src/common/duplication_common.cpp
src/meta/duplication/duplication_info.cpp
src/meta/duplication/duplication_info.h
src/meta/duplication/meta_duplication_service.cpp
src/meta/duplication/meta_duplication_service.h
src/meta/test/duplication_info_test.cpp
src/meta/test/meta_duplication_service_test.cpp
src/shell/command_helper.h
src/shell/commands/duplication.cpp
src/shell/commands/local_partition_split.cpp
src/shell/main.cpp

While duplicating from a cluster A only including one node where all tables have
just one replica to another cluster B including at least 3 nodes where all tables have
3 replicas, the target table on B would be also created with one replica. Thus we
should allow a duplication to be created with specified replica count.

feat(duplication): allow remote replica count to be specified for duplication

---

src/replica/replica.cpp
src/replica/replica.h
src/replica/replica_chkpt.cpp
src/replica/replica_config.cpp
src/replica/replica_stub.cpp

Sometimes we have to disable plog garbage collection. For example, to duplicate
data to the target cluster, we could firstly disable plog garbage collection, then do
copy_data. After copy_data is finished, a duplication with DS_LOG status could be
added to continue to duplicate data in plog to target cluster; at the same time, plog
garbage collection certainly should be enabled again.
Therefore a new configuration is added to enable/disable plog garbage collection:
```diff
[replication]
+ plog_gc_enabled = true
```

feat(plog): garbage collection is allowed to be enabled/disabled  for plog

---

src/replica/replica_stub.cpp
src/security/access_controller.cpp

Separate the cluster_name and encryption key configurations for clearer usage.
A new config [security] encryption_cluster_key_name has been introduced for managing kms key:
```diff
[security]
+encryption_cluster_key_name
```

feat(encryption): add a new security configuration for encryption key 

---

src/common/common.cpp
src/common/common.h
src/common/duplication_common.cpp
src/common/duplication_common.h
src/common/test/common_test.cpp
src/common/test/duplication_common_test.cpp
src/meta/duplication/meta_duplication_service.cpp
src/server/pegasus_mutation_duplicator.cpp
src/server/pegasus_write_service.cpp
src/server/pegasus_write_service.h
src/server/pegasus_write_service_impl.h
src/server/rocksdb_wrapper.cpp
src/server/test/pegasus_mutation_duplicator_test.cpp
src/test_util/test_util.h
src/utils/fmt_logging.h

The purpose of this PR is to optimize configurations for duplications.
Firstly, many Pegasus clusters are configured with the same `cluster_name`
(namely `[replication]cluster_name`). However, once we decide to duplicate
tables between them, their `cluster_name` have to be changed to be distinguished
from each other -- this might lead to side effects.
Secondly, consider a scenario where many clusters are duplicated to a target
cluster. This means we have to add many cluster ids to the `*.ini` file of the target
cluster, and the target cluster might be restarted very frequently.
Thus following options are added to solve both problems:
```diff
[replication]
+ dup_cluster_name =
+ dup_ignore_other_cluster_ids = false
```
`[replication]dup_cluster_name` is added only for duplication in case …

feat(duplication): add options to support cluster name only used for duplication and allow any other cluster id except myself to be ignored

---

src/server/pegasus_server_impl_init.cpp

There are 2 options stats_dump_period_sec and stats_persist_period_sec in
RocksDB to adjust the period to dump/persist stat, each RocksDB instance
creates 2 dependent threads for this aim.
A replica server is possible to serve thousands of replicas, it means
thousands of RocksDB instances are possible to be running in one process,
then thousands of threads will be created will may consume much resouce.
This patch introduces 2 options, then it's possible to disable the threads
by setting them to 0.

feat: Add 2 options to limit thread count

---

thirdparty/CMakeLists.txt

Fix build failures like:
1.
```
/bin/ld: /.../thirdparty/output/lib/libcurl.a(libcurl_la-content_encoding.o): in function `brotli_close_writer':
content_encoding.c:(.text+0x2c): undefined reference to `BrotliDecoderDestroyInstance'
```
2.
```
/bin/ld: /.../thirdparty/output/lib/libcurl.a(libcurl_la-easy.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `malloc' which may bind externally can not be used when making a shared object; recompile with -fPIC
/bin/ld: /.../thirdparty/output/lib/libcurl.a(libcurl_la-easy.o)(.text+0x30): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `malloc'
```
3.
```
/bin/ld: idn.c:(.text+0x34): undefined reference to `idn2_lookup_ul'
```

fix(aarch64): Fix build failure on ARM architecture chips

---

src/runtime/global_config.h
src/runtime/service_api_c.cpp
src/utils/config_helper.h
src/utils/logging.cpp
src/utils/logging_provider.h

Add a new configuration 'log_dir' to indicate the directory to place the
logs especially. 'data_dir' will be used if it's empty.
```diff
[core]
+log_dir = 
```

feat(logging): Support to specify log directory

---

src/runtime/service_api_c.cpp
src/utils/simple_logger.cpp
src/utils/simple_logger.h

Mainly including:
- Using fmt::format/print instead of sprintf/printf, which is more convenient
and faster
- Add some configuration validators
- Encapsulate print_header(), print_long_header() and print_body() for
screen_logger and simple_logger
- Add more comments
- Naming improvment

refactor(logging): Minor refactor on logging module

---

src/runtime/tracer.cpp
src/utils/simple_logger.cpp
src/utils/simple_logger.h
src/utils/test/logger.cpp

- A new symlink is added to point to the latest log file, the symlink is in
the same directory as the log files.
**Behavior change:**
- Log file is rolled by `max_log_file_bytes` configuration (64MB by default)
instead of the fixed line count, i.e. 200000.
- Log files are named as `log.<yyyyMMdd_hhmmss_SSS>`, e.g. log.20240524_1806_235
instead of `log.<index>.txt`, e.g. log.123.txt
```diff
[tools.simple_logger]
+max_log_file_bytes =
```

feat(logging): Fill timestamp in log file name and limit single file size and total count

---

src/failure_detector/test/run.sh
src/meta/test/meta_state/run.sh
src/meta/test/run.sh
src/replica/backup/test/run.sh
src/replica/bulk_load/test/run.sh
src/replica/duplication/test/run.sh
src/replica/split/test/run.sh
src/replica/storage/simple_kv/run.sh
src/replica/storage/simple_kv/test/run.sh
src/runtime/service_api_c.cpp
src/runtime/test/run.sh
src/runtime/tracer.cpp
src/utils/logging.cpp
src/utils/logging_provider.h
src/utils/simple_logger.cpp
src/utils/simple_logger.h
src/utils/test/clear.sh
src/utils/test/logger.cpp
src/utils/test/main.cpp
src/utils/test/run.sh
src/zookeeper/test/run.sh

This patch fills the log file name with the role name. For example, the replica
server log file name is in the form of `replica.log.<yyyyMMdd_hhmmss_SSS>`,
while the meta server log file name is in the form of `meta.log.<yyyyMMdd_hhmmss_SSS>`.
If the role name is empty (typically in unit tests), it will fall back to use
a new configudation `base_name` in `tools.simple_logger` section, it's default
as `pegasus`. Then, the log file is in the form of `pegasus.log.<yyyyMMdd_hhmmss_SSS>`.
```diff
[tools.simple_logger]
+base_name = pegasus
```

feat: Distinguish log file names

---

src/meta/CMakeLists.txt
src/meta/meta_backup_service.cpp
src/meta/meta_backup_service.h
src/meta/test/meta_backup_test.cpp

Because the backup policy name will be used as a metric name and label, it
should not contain any invalid character (e.g. `-`), otherwise, it lead crash.
This patch adds a validator to ensure there are only allowed characters in
backup policy name.

fix(backup): validate backup policy name

---

.github/workflows/lint_and_test_cpp.yaml
thirdparty/CMakeLists.txt

- Add a new job `Build Debug on CentOS 7`
- Rename the `macOS` job to `Build Release on macOS`
- Fix the link error on CentOS 7 and revert some modification of commit d00b25136aeb04c70eb62ba4ea8b0250804483a8

chore(CI): Add building debug version job on CentOS 7 and fix link errors

---

src/client/replication_ddl_client.cpp
src/client/replication_ddl_client.h
src/meta/meta_backup_service.cpp
src/shell/commands/cold_backup.cpp
src/shell/main.cpp

Add JSON output to some backup policy commands to facilitate the writing of automation scripts.
Backup policy commands including:
- ls_backup_policy
- query_backup_policy
ls_backup_policy Output example by Tabler format
```
[p1]
backup_provider_type  : hdfs_service
backup_interval       : 86400s
app_ids               : {3}
start_time            : 03:36
status                : enabled
backup_history_count  : 1
[p2]
backup_provider_type  : hdfs_service
backup_interval       : 86400s
app_ids               : {3}
start_time            : 20:25
status                : enabled
backup_history_count  : 1
```
ls_backup_policy Output example by JSON format
```
{
"p1": {
"backup_provider_type": "hdfs_service",
"backup_interval": "86400s",
"app_ids": "{3}",
"start_time": "03:36",
"status": "enabled", …
```

feat(shell): Add JSON format data output to some backup_policy commands

---

.github/actions/build_pegasus/action.yaml
.github/workflows/lint_and_test_cpp.yaml
scripts/pack_client.sh
scripts/pack_common.sh
scripts/pack_server.sh
scripts/pack_tools.sh

This patch adds a new flag `--separate_servers` to indicate whether to pack `pegasus_collector`，`pegasus_meta_server` and `pegasus_replica_server` binaries, otherwise a combined `pegasus_server` binary will be packed in the pegasus_server_xxx.tar. 
When build server in option `--separate_servers`,the corresponding option to use pack command is:
```
./run.sh pack_server -s  or ./run.sh pack_server --separate_servers
./run.sh pack_tools -s   or  ./run.sh pack_tools --separate_servers
```

chore(pack): Support to pack server binaries separately

---

src/shell/command_helper.h
src/shell/commands/cold_backup.cpp

The marco `PARSE_STRS` execute strs with `param_index`，and it only
execute the number of params_index of input strs.
The marco `PARSE_OPT_STRS` can execute input strs with flag.
The historical flag input mode should be continued.

fix(shell): Add PARSE_OPT_STRS marco for shell command execute  flag input mode

---

src/client/replication_ddl_client.cpp
src/failure_detector/test/failure_detector.cpp
src/meta/meta_bulk_load_service.cpp
src/meta/server_state.cpp
src/redis_protocol/proxy_lib/proxy_layer.cpp
src/redis_protocol/proxy_lib/proxy_layer.h
src/replica/storage/simple_kv/test/case.cpp
src/runtime/rpc/asio_net_provider.cpp
src/runtime/rpc/asio_net_provider.h
src/runtime/rpc/group_host_port.h
src/runtime/rpc/network.cpp
src/runtime/rpc/network.sim.cpp
src/runtime/rpc/rpc_engine.cpp
src/runtime/rpc/rpc_host_port.cpp
src/runtime/rpc/rpc_message.h
src/runtime/service_api_c.cpp
src/runtime/test/host_port_test.cpp

https://github.com/apache/incubator-pegasus/issues/2007
In servers, we assume that the remote IPs may can't be reverse resolved, in
this case, warning or error messages are logged instead of crashing.
But in tests, we assume that all the IPs can be reverse resolved.

fix(FQDN): Fix the bug of crash caused by un-resolved IP address

---

java-client/README.md
rfcs/2020-08-27-metric-api.md

https://github.com/apache/incubator-pegasus/issues/2047
Use "github.com/open-falcon" instead of dead link "open-falcon.org".

chore: fix dead link open-falcon.org

---

src/common/consensus.thrift
src/replica/duplication/duplication_pipeline.cpp
src/replica/duplication/mutation_batch.cpp
src/replica/duplication/mutation_batch.h
src/replica/duplication/replica_duplicator.h
src/replica/duplication/test/duplication_test_base.h
src/replica/duplication/test/mutation_batch_test.cpp
src/replica/mutation_log.cpp
src/replica/mutation_log.h
src/replica/replica.h
src/replica/test/mutation_log_test.cpp
src/replica/test/replica_test_base.h

https://github.com/apache/incubator-pegasus/issues/2050
As is described by the issue, the problem is that we have to waits 2 ~ 3 minutes
(until some empty write gets in) before the last mutation is duplicated to the remote
cluster.
The reason is that the last committed decree of the last mutation (i.e.
`mutation.data.header.last_committed_decree`), rather than the decree of the
last mutation (i.e. `mutation.data.header.decree`), is chosen as the max decree
that is duplicated to the remote cluster. Instead, the max committed decree should
be chosen as the max decree that is duplicated to the remote cluster.
After the optimization, the delay has been reduced from 2 ~ 3 minutes to about
0.1 seconds.

fix(duplication): reduce the delay before last mutation is duplicated to the remote cluster

---

.github/workflows/lint_and_test_java-client.yml
java-client/README.md
java-client/pom.xml
java-client/scripts/download_thrift.sh

fix #1664 
ref: https://issues.apache.org/jira/browse/THRIFT-1536
ref: https://github.com/apache/parquet-mr/pull/600
- Unit test
- No code

feat(java-client): add maven-thrift-plugin

---

run.sh

Use run.sh start pegasus shell will create a symbolic link every time. But in docker production environment. It cant create a symbolic link in the only-read filesystem of container. So when symbolic link is exist we should not create.

chore(run.sh): create a symbolic link of pegasus_shell only doesnt exist

---

scripts/downgrade_node.sh

The downgrade_node scripts usually used in the scale down replica server. The function of downgrade_node scripts implementation with wildchar of shell output.
- The character matching is not success for everysingle line in shell output. So add "set -e" will exit with 1 and report failed. 
- Fix a shell grammar promblem.

fix(scripts): fix downgrade_node script doesnt work 

---

idl/backup.thrift
src/client/replication_ddl_client.cpp
src/client/replication_ddl_client.h
src/meta/meta_backup_service.cpp
src/shell/commands.h
src/shell/commands/cold_backup.cpp
src/shell/main.cpp

Before this patch, once a backup policy is added and enabled, it's
impossible to disable it when a new job of the policy is starting,
even if there are some reasons block the job to complete.
This patch add a new flag '-f|--force' to disable the policy by force,
then it's possible to stop the job after restarting the servers.

feat(backup): Add --force option for 'disable_backup_policy' shell command

---

src/block_service/hdfs/hdfs_service.cpp

After refactoring to use RocksDB APIs to read files from local
filesystem, it may cause stack overflow when the file to read
is larger than the stack size (say 8MB).
This patch changes to use heap instead of stack to store the
file content.

fix(backup): Fix the stack overflow when read large sst file

---

src/nfs/nfs_client_impl.cpp
src/nfs/nfs_server_impl.cpp
src/utils/command_manager.cpp
src/utils/command_manager.h

Some remote commands shell output are format by json. And some remote command are not.
- Changes the output of register_int_command、register_bool_command to JSON format to improve readability
by programs (e.g., Python scripts)

feat(remote_command): change some  remote_command shell output to JSON format

---

.github/workflows/lint_and_test_cpp.yaml
src/replica/duplication/replica_duplicator.cpp
src/replica/duplication/replica_duplicator.h
src/replica/duplication/test/duplication_test_base.h
src/replica/duplication/test/replica_duplicator_test.cpp
src/replica/replica.h
src/replica/replica_chkpt.cpp
src/replica/test/mock_utils.h
src/replica/test/replica_test.cpp
src/utils/errors.h

https://github.com/apache/incubator-pegasus/issues/2069
To create the checkpoint of the replica with 0 or 1 record immediately:
- set the min decree for checkpoint to at least 1, which means the checkpoint
would inevitably be created even if the replica is empty.
- for the empty replica, an empty write would be committed to increase the
decree to at least 1 to ensure that the checkpoint would be created.
- the max decree in rocksdb memtable (the last applied decree) is considered
as the min decree that should be covered by the checkpoint, which means
currently all of the data in current rocksdb should be included into the created
checkpoint.
The following configuration is added to control the retry interval for triggering
checkpoint:
```diff
[replication]
+ …
```

fix(duplication): create checkpoint for the replica with 0 or 1 record

---

.github/workflows/lint_and_test_cpp.yaml

https://github.com/actions/runner/issues/2906

chore(CI): Add envs in build_debug_on_centos7 to ensure job can be run on centOS 7

---

.github/workflows/build-push-env-docker.yml
.github/workflows/regular-build.yml
.github/workflows/thirdparty-regular-push.yml

The glibc version on ubuntu1804 and centos7 is lower than the node20 required, so
we need to force the node version to 16 when running CI.
See more details: https://github.com/actions/checkout/issues/1809

chore(CI): Force CI to run on node16

---

.github/workflows/build-push-env-docker.yml
.github/workflows/regular-build.yml
.github/workflows/thirdparty-regular-push.yml

To solve problem in GitHub actions:
```
Run actions/checkout@v4
/usr/bin/docker exec  e63787d641b0351b6c65ad895ccd98db84d6796141ad087c4952bc7f68b03753 sh -c "cat /etc/*release | grep ^ID"
/__e/node[20](https://github.com/apache/incubator-pegasus/actions/runs/9908766114/job/27375256228#step:3:21)/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

chore(CI): Force to use actions/checkout@v3 when OS maybe CentOS 7 or Ubuntu 18.04

---

src/shell/commands/node_management.cpp
src/utils/command_manager.h

This patch refactors the code for the `remote_command` shell CLI tool,
now uses `argh::parser` instead of `getopt_long`. And now the error
output is colored to notice the administors.
The effected commands are `server_info`, `server_stat`, `flush_log` and
`remote_command`.
To keep compatible, `remote_command server-info`, `remote_command server_info`
and `server_info` are equal. The same to `server_stat` and `flush_log`.
Behavior changes:
- If there are some errors, the tool return false instead of true, then
the USAGE can be output for hint.
- The output is organized as JSON format, and the embeded structures are
also in JSON format. (This is very useful for thirdparty tools to parse
the output.)
Example:
```
>>> remote_command server-info -l b334667ddf87:34801
{
"command": "server-info …
```

refactor(shell): Refactor on 'remote_command' command

---

src/utils/logging_provider.h
src/utils/simple_logger.cpp
src/utils/simple_logger.h
src/utils/test/fmt_logging_test.cpp

If using `screen_logger`, the logs are only printed to stdout.
This patch introduces a new config
`[tools.screen_logger]stderr_start_level_on_stdout`
to define the lowest level of log messages to be copied to
stderr in addition to stdout. This is useful for testing.
A test using `ASSERT_DEATH` is added to check the logs are printed
to stderr indeed.

feat(logging): Make it possible to print logs to stderr when using screen_logger

---

thirdparty/CMakeLists.txt

This is a previous work of https://github.com/apache/incubator-pegasus/pull/2083.
This patch introduces [spdlog](https://github.com/gabime/spdlog) as a thirdparty
to prepare the docker image, then the #2083 can use it to run CI.
spdlog is a very fast C++ logging library, you can see the benchmarks:
https://github.com/gabime/spdlog?tab=readme-ov-file#benchmarks. spdlog using
`libfmt` to format message content, it is fast and compatible with the current
logging practice in Pegasus. It's a good choice to replace the current
`simple_logger` or `screen_logger` implementation in Pegasus.

feat(logging): Introduce spdlog to thirdparty

---

.clang-tidy
.github/workflows/lint_and_test_cpp.yaml
run.sh
scripts/clang_tidy.py
src/utils/simple_logger.cpp

> clang-tidy is a clang-based C++ “linter” tool. Its purpose is to provide
an extensible framework for diagnosing and fixing typical programming
errors, like style violations, interface misuse, or bugs that can be deduced
via static analysis. clang-tidy is modular and provides a convenient interface
for writing new checks.
This patch introduces clang-tidy to lint the Pegasus code, there are many
issues are needed to be fixed, it would be a very large patch if fix them all
in one patch. So only changed files will be checked in the newly added GitHub
action.
To lint the code localy before submitting the code, please follow the steps:
1. Install `clang-tidy`, now we are using clang-tidy-14.
`sudo apt-get install clang-tidy -y`
2. Setup the compilation database the clang-tidy needed. …

chore(CI): Introduce clang tidy linter

---

src/meta/duplication/duplication_info.cpp
src/meta/duplication/meta_duplication_service.cpp
src/meta/test/meta_duplication_service_test.cpp
src/meta/test/meta_test_base.cpp
src/meta/test/meta_test_base.h

https://github.com/apache/incubator-pegasus/issues/2092
While the remote table created with only one replica for the full duplication
(copying checkpoints), the duplication would get stuck in `DS_APP` status
forever due to `ERR_NOT_ENOUGH_MEMBER`. The reason is that the check
would fail once there is no secondary replica. However, for single-replica tables,
there is certainly not any secondary replica.

fix(duplication): fix unexpected ERR_NOT_ENOUGH_MEMBER while checking if the remote table with only one replica is ready for duplication

---

src/replica/duplication/replica_duplicator.cpp
src/replica/duplication/replica_duplicator.h
src/replica/duplication/test/dup_replica_http_service_test.cpp
src/replica/duplication/test/duplication_sync_timer_test.cpp
src/replica/duplication/test/mutation_batch_test.cpp
src/replica/duplication/test/replica_duplicator_manager_test.cpp
src/replica/duplication/test/replica_duplicator_test.cpp

https://github.com/apache/incubator-pegasus/issues/2098
After the replica server was restarted, `min_checkpoint_decree` would be
reset to the invalid decree(-1), which is wrong for an existing duplication that
is still in the status of `DS_PREPARE`, meaning the replica would continue
to generate checkpoints for the full duplication. The duplication in the status
of `DS_PREPARE` would call `replica_duplicator::prepare_dup()` which makes
an assertion that `min_checkpoint_decree` must be greater than 0. Therefore,
the replica server would always exit abnormally due to the failed assertion.

fix(duplication): `min_checkpoint_decree` was reset to the invalid decree after replica server was restarted

---

src/replica/duplication/duplication_pipeline.cpp

A new option is added for duplication to configure the duration of the delay
until the next execution if there is no mutation to be loaded:
```diff
[replication]
+ dup_no_mutation_load_delay_ms = 100
```

feat(duplication): add a new option to configure the duration of the delay until the next execution if there is no mutation to be loaded

---

.github/workflows/module_labeler_conf.yml

Fix https://github.com/apache/incubator-pegasus/issues/2105.

fix(github): add write permission to module labeler

---

src/utils/blob.h
src/utils/test/blob_test.cpp

Fix https://github.com/apache/incubator-pegasus/issues/2109.
Null-pointer char array with zero length is allowed to be used to initialize
`blob` object. Use `DCHECK` instead to check if the pointer is valid while
initializing `blob` object.

fix(blob): allow `blob` object to be initialized with null-pointer char array whose length must be zero

---

.licenserc.yaml
src/runtime/test/CMakeLists.txt
src/runtime/test/corrupt_message.cpp
src/runtime/test/gtest.filter
src/runtime/test/run.sh

Now the test `core.corrupt_message` is disabled by `--gtest_filter`, it's a
bit of complex because it uses an external file
(i.e. `src/runtime/test/gtest.filter`), and it just disable
`core.corrupt_message` test case. This can be simplified by adding a
`DISABLED_` prefix, and make sure all other test cases can be ran normally.

refactor(tests): Simplify the runtime module unit tests

---

src/rpc/test/net_provider_test.cpp
src/runtime/test/service_api_c.cpp
src/runtime/test/sim_lock.cpp
src/runtime/test/task_engine.cpp

The gtest provided macro `GTEST_SKIP` is better than manual `return`, the
former shows which test cases are skipped explicitly, it's more convenient
for developers to check the result.

refactor(tests): Use GTEST_SKIP macro to skip useless tests

---

.licenserc.yaml
thirdparty/CMakeLists.txt
thirdparty/fix_thrift_build_and_link_errors.patch

Fix a linkage error on MacOS, the error looks like:
```
Undefined symbols for architecture x86_64:
"int boost::math::signbit<double>(double)", referenced from:
apache::thrift::protocol::TJSONProtocol::writeJSONDouble(double) in libthrift.a(TJSONProtocol.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ 31%] Building CXX object src/block_service/test/CMakeFiles/dsn_block_service_test.dir/hdfs_service_test.cpp.o
make[2]: *** [src/base/test/base_test] Error 1
make[1]: *** [src/base/test/CMakeFiles/base_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
This error also appears on Linux when I tried to bump boost to 1.86.0. We
use a very old version of thrift (0.9.3), it uses …

fix(build): Fix a linkage error of thrift

---

.github/actions/rebuild_thirdparty_if_needed/action.yaml
.github/actions/upload_artifact/action.yaml

Fix https://github.com/apache/incubator-pegasus/issues/2128.
Only move `hadoop-bin` and `zookeeper-bin` out of third-party
directory immediately before uploading artifact.

fix(github): zookeeper-bin cannot be found while uploading artifact

---

.github/actions/rebuild_thirdparty_if_needed/action.yaml
.github/actions/unpack_prebuilt_thirdparties/action.yaml
.github/actions/upload_artifact/action.yaml
.github/workflows/lint_and_test_cpp.yaml
.github/workflows/thirdparty-regular-push.yml
admin_tools/download_hadoop.sh
admin_tools/download_package.sh
admin_tools/download_zk.sh
docker/README.md
docker/pegasus-build-env/centos7/Dockerfile
docker/thirdparties-bin/Dockerfile
docker/thirdparties-src/Dockerfile

Resolve https://github.com/apache/incubator-pegasus/issues/2136:
- move `hadoop-bin` dir into the specified position at the stage of rebuilding/unpacking
`thirdparty` instead of uploading artifact;  
- build `thirdparties-src` image on Ubuntu instead of EOL CentOS 7 to make downstream
workflows work.

fix(github): fix redundant `hadoop-bin` while uploading artifact and build `thirdparties-src` image on each OS version

---

java-client/src/main/java/org/apache/pegasus/rpc/async/ReplicaSession.java
java-client/src/main/java/org/apache/pegasus/security/AuthReplicaSessionInterceptor.java
java-client/src/test/java/org/apache/pegasus/rpc/async/ReplicaSessionTest.java

Resolve https://github.com/apache/incubator-pegasus/issues/2133.
After the session with authentication enabled to remote server is closed(e.g.
the server is killed), the flag(i.e. `authSucceed`) marking whether the session
has been authenticated is still kept `true`. Afterwards, while trying to creating
another new connection to the same remote server for this session, some requests
would be pending before it is connected successfully. Once the session is connected,
the pending requests would be sent to the remote server. Typically, the first element
of the pending queue would be a non-negotiation request(`query_cfg_request` to
the meta server for example), and the second one would be a negotiation request.
Normally, the non-negotiation request would be moved to another pending queue
for …

fix(java-client): fix `Negotiation failed` after a session with authentication enabled is closed

---

.github/workflows/build-push-env-docker.yml

https://github.com/apache/incubator-pegasus/issues/2135.
CentOS 7.5.1804 does not support `aarch64` in [sclo](https://vault.centos.org/7.5.1804/sclo/).
Thus just remove `linux/arm64` from Github workflow.
- Unit test
- No code

ci: fix the workflow building images of compilation environment for centos7 on Github

---

src/meta/meta_service.h
src/meta/server_state.cpp
src/meta/server_state.h
src/meta/test/meta_service_test_app.h
src/meta/test/server_state_test.cpp
src/meta/test/state_sync_test.cpp
src/utils/fail_point.h

https://github.com/apache/incubator-pegasus/issues/2149.
There are two problems that should be solved:
1. why the primary meta server failed with `segfault` while dropping tables ?
2. why all meta servers were never be restarted normally after the primary
meta server failed ?
A pegasus cluster would flush security policies to remote meta storage
periodically (by `update_ranger_policy_interval_sec`) in the form of environment
variables. We do this by `server_state::set_app_envs()`. However, after updating
the meta data on the remote storage (namely ZooKeeper), the table is not checked
that if it still exists while updating environment variables of local memory:
```C++
void server_state::set_app_envs(const app_env_rpc &env_rpc)
{
...
do_update_app_info(app_path, ainfo, [this, app_name, …
```

fix(meta): meta server failed and could not be started normally while setting environment variables after dropping table

---

.github/workflows/thirdparty-regular-push.yml

https://github.com/apache/incubator-pegasus/issues/2135.
Since the workflow building images of compilation environment for centos7 has
been fixed by https://github.com/apache/incubator-pegasus/pull/2145, building
thirdparty images should also be recovered.

ci: recover the workflows building thirdparty images for centos7 on Github

---

docker/pegasus-build-env/centos7/Dockerfile
docker/pegasus-build-env/ubuntu1804/Dockerfile
docker/pegasus-build-env/ubuntu2004/Dockerfile
docker/pegasus-build-env/ubuntu2204/Dockerfile
java-client/scripts/download_thrift.sh

Resolve https://github.com/apache/incubator-pegasus/issues/2155.
Change the download URL of thrift 0.11.0 tarball to Apache instead of
Github where it was removed recently.

fix(download): fix the broken download URL of thrift 0.11.0 tarball

---

idl/duplication.thrift
src/common/duplication_common.cpp
src/meta/duplication/duplication_info.cpp
src/meta/duplication/duplication_info.h
src/meta/duplication/meta_duplication_service.cpp
src/meta/test/duplication_info_test.cpp
src/meta/test/meta_duplication_service_test.cpp
src/replica/duplication/replica_duplicator_manager.cpp

`duplication_entry` is an important struct for duplication, including per-duplication
properties and progress info(confirmed decree) for each partition of a table. It
contains all useful info for a duplication. Therefore, it has been used in response to
query and sync:
- The query is requested by client, to the meta server to get the properties of
duplications of single table;
- The sync is requested by replica server, also to the meta server to sync progress.
Soon we would support a new interface to get duplications from multiple tables,
i.e. `list duplications`. It would request duplications of multiple tables, also including
per-duplication properties and progress info(confirmed decree and a new field last
committed decree). It still uses `duplication_entry` as the response to the …

feat(duplication): support duplication entry for multiple purposes

---

src/replica/replica_stub.cpp
src/replica/replica_stub.h

Currently we don't have metrics about how many primary replicas or secondary
replicas on a replica server, which means we have to find them using `nodes`
command by Pegasus shell rather than just monitoring graphs.

feat(new_metircs): collect the number of primary and secondary replicas

---

src/replica/replica_2pc.cpp

Resolve issue https://github.com/apache/incubator-pegasus/issues/2156.
Due to the flag _is_bulk_load_ingestion allowing only one RPC_RRDB_RRDB_BULK_LOAD RPC call, the throttling_controller::DELAY recall of on_client_write cannot execute RPC_RRDB_RRDB_BULK_LOAD again.

fix(bulkload): Sometime ingest will hang when encountering write throttling

---

src/replica/replica_backup.cpp
src/shell/command_utils.h
src/shell/commands/detect_hotkey.cpp
src/shell/commands/duplication.cpp

Fix https://github.com/apache/incubator-pegasus/issues/2168.

fix(shell): fix the validation for the command while there is not any positional argument

---

src/replica/replica_backup.cpp
src/shell/commands/duplication.cpp

Improvements for the command of listing duplications have been made in
the following aspects:
- change the description for the stats of duplication by status and follower
cluster to avoid misunderstanding.
- add `DS_LOG` as the prerequisite for a duplication to be considered as
finished.
- introduce a new partition-level column showing the gap between confirmed
decree and last committed decree.
- fix the options for json format and output file.

feat(duplication): improve `dups` command to make the output info easier to understand

---

src/meta/server_state.cpp
src/meta/test/server_state_test.cpp

https://github.com/apache/incubator-pegasus/issues/2149.
Previously we've fixed the problem that meta server failed due to null pointer while
deleting environment variables locally immediately after a table was dropped in
https://github.com/apache/incubator-pegasus/pull/2148. There's the same problem
while deleting environment variables.

fix(meta): fix null pointer while deleting environment variables after table was dropped

---

admin-cli/cmd/init.go
admin-cli/executor/client.go
admin-cli/executor/disk_info.go
admin-cli/executor/toolkits/tablemigrator/switcher.go
admin-cli/util/pegasus_node.go

https://github.com/apache/incubator-pegasus/issues/2160
Current admin-cli client does not provide an interface to close replica server TCP connections.
And `QueryAllNodesDiskInfo` function is difficult to use. `SendQueryDiskInfoRequest` function is private.
support close client, disconnect tcp link with replica server.
The TCP connection to the replica server cannot be closed.
After support close client，the persistent TCP connection between admincli and the replica server can be disconnected.

refactor: support close admin-cli client

---

src/server/pegasus_mutation_duplicator.cpp
src/server/pegasus_mutation_duplicator.h

#2100 
Make replica server skip `RPC_RRDB_RRDB_BULK_LOAD` code when reply the plog.
- Unit test
- Manual test

fix(duplication): deal with bulkload dup crash

---

.github/workflows/lint_and_test_cpp.yaml

Fix the issue:
> The macOS-12 environment is deprecated, consider switching to macOS-13,
> macOS-14 (macos-latest) or macOS-15. For more details, see
> https://github.com/actions/runner-images/issues/10721

chore: Upgrade to use macOS 15 in action

---

.github/workflows/build-push-env-docker.yml
.github/workflows/lint_and_test_cpp.yaml
.github/workflows/regular-build.yml
.github/workflows/standardization_lint.yaml
.github/workflows/thirdparty-regular-push.yml
docker/README.md
docker/pegasus-build-env/rocky9/Dockerfile
docker/pegasus-build-env/rockylinux9/Dockerfile
docker/thirdparties-bin/Dockerfile
docker/thirdparties-src/Dockerfile

Since the node16 has been removed in Github actions, the CentOS 7 is hard to run as
a runner, we have to make many tricky works if we want to do that.
As an alternative, this patch introduces RockyLinux 9 as a new github runner.
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

chore(gha): introduce RockyLinux as an action runner

---

docker/pegasus-build-env/rockylinux9/Dockerfile

`ccache` is not distributed by the Rockylinux official repository, instead, we
can install it though `EPEL`.

fix(rockylinux): add the missing ccache package

---

src/meta/server_state.cpp
src/meta/test/server_state_test.cpp
src/replica/replica_backup.cpp

https://github.com/apache/incubator-pegasus/issues/2149.
Previously we've fixed the problem that meta server failed due to null pointer while
setting environment variables locally immediately after a table was dropped in
https://github.com/apache/incubator-pegasus/pull/2148. There's the same problem
while clearing environment variables.

fix(meta): fix null pointer while clearing environment variables after table was dropped

---

src/server/rocksdb_wrapper.cpp
src/server/rocksdb_wrapper.h

Currently the wrapper operates RocksDB data still by default column family handler.
To make data/meta column family both specified explicitly while accessing RocksDB
instance, introduce data column family handler into the wrapper.

refactor: specify data column family explicitly for RocksDB wrapper

---

.github/actions/download_artifact/action.yaml
.github/actions/upload_artifact/action.yaml

As the actions/download-artifact@v3 and actions/upload-artifact@v3 are scheduled for deprecation on November 30, 2024, this patch updates them to v4.
https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact
https://github.com/actions/download-artifact?tab=readme-ov-file#actionsdownload-artifact

chore: update actions download-artifact and up-artifact to v4

---

java-client/pom.xml

Fix https://github.com/apache/incubator-pegasus/issues/2188.
`idl/utils.thrift` was introduced before and has not been added into java client
to generate necessary source files which make workflow for building failed. It
should also be excluded from spotless check just like what have been done for
other thrift files.

fix(java-client): package `org.apache.pegasus.utils` does not exist while building java client

---

idl/rrdb.thrift
src/server/pegasus_server_write.h
src/server/pegasus_write_service.h
src/server/pegasus_write_service_impl.h
src/server/rocksdb_wrapper.cpp
src/server/test/pegasus_write_service_impl_test.cpp
src/utils/blob.h

Implement two APIs making `incr` request idempotent in `pegasus_write_service::impl`:
- translate an `incr` request (non-idempotent) into a single-put request (idempotent),
and process the possible errors during the translation, e.g. failed to read base value for
increment from the RocksDB instance;
- apply the single-put request into the RocksDB instance and make response for `incr`.

feat(make_idempotent): support making `incr` request idempotent in `pegasus_write_service::impl`

---

admin_tools/pegasus_manual_compact.sh

… remote_command -t replica-server replica.query-compact  shell command.
[#2190](https://github.com/apache/incubator-pegasus/issues/2190)
The [commit 2d68748](https://github.com/apache/incubator-pegasus/commit/2d68748264500a3fb3850a0dcfc8af8e8595a19a#:~:text=info%5B%22recent_enqueue_at%22%5D) changed the output format of the shell command remote_command -t replica-server replica.query-compact ${app_id}, which caused the wait_manual_compact function to still parse the output based on the original format, leading to incorrect behavior. It has now been fixed by modifying the parsing method.

fix(scripts): Fix the way the wait_manual_compact function parses the shell output

---

src/replica/duplication/replica_duplicator.cpp

https://github.com/apache/incubator-pegasus/issues/2183
We can make the task code configurable, allowing the thread priority incremental
loading from private logs of to be adjusted from **LOW** to **COMMON**, thereby
enabling support for low-latency real-time synchronization.
I do some test cases as following:
In these test cases, I first wrote 8k QPS of write traffic to the master cluster (this is the traffic that my test cluster will not generate dup log backlogs) to verify the effect of the priority modification. Then I wrote 20k QPS of write traffic to the master cluster (this is the traffic that my test cluster will generate a certain degree of dup log backlogs) to verify the effect of the priority modification.
| load/ship task priority | load_from_private_log task priority | qps  | …

feat(duplication): make the task code for incremental loading from private logs configurable

---

src/replica/bulk_load/replica_bulk_loader.cpp
src/replica/bulk_load/replica_bulk_loader.h
src/server/pegasus_mutation_duplicator.cpp

Related issue:
https://github.com/apache/incubator-pegasus/issues/2006.
Avoid using _metadata.files reference ，and add a  read_lock 
Because bulkload imports a large amount of data.
- Manual test
After fix : Table ingest_p4_10G partition1 is missing files, and the table ballot does not increase after bulkload.
```c++
[2024/5/23 15:11:10] [general]
[2024/5/23 15:11:10] app_name           : ingest_p4_10G
[2024/5/23 15:11:10] app_id             : 100          
[2024/5/23 15:11:10] partition_count    : 4            
[2024/5/23 15:11:10] max_replica_count  : 3            
[2024/5/23 15:11:10] 
[2024/5/23 15:11:10] [replicas]
[2024/5/23 15:11:10] pidx  ballot  replica_count  primary                              secondaries …
```

fix(bulk_load): fix core dump while downloading sst files

---

src/common/bulk_load_common.cpp
src/common/bulk_load_common.h
src/meta/meta_bulk_load_service.cpp

https://github.com/apache/incubator-pegasus/issues/2194
The main reason is that during the ingest phase, the time between meta's RPC_BULK_LOAD transmissions is too long (once every 10 seconds). Shortening this time interval can cut down the partition write-blocking time.
Before：partition ingest time 30s.
After refactor: partition ingest time 300~900ms.

feat(bulk_load): reduce partition ingest time

---

admin_tools/pegasus_manual_compact.sh

[#2203](https://github.com/apache/incubator-pegasus/issues/2203)
We can modify pegasus_manual_compact.sh to accept --cluster or --config parameters(but not both simultaneously). When the --config parameter is used, the shell commands inside will use ./run.sh shell --config config_file_path, so there is no need to generate new files, which avoids the directory permission issue.

fix(scripts): Add the --config parameter to pegasus_manual_compact.sh

---

src/common/replication_other_types.h
src/meta/test/meta_partition_guardian_test.cpp
src/meta/test/misc/misc.cpp
src/meta/test/update_configuration_test.cpp
src/replica/replica_config.cpp
src/replica/replica_stub.cpp
src/rpc/rpc_host_port.cpp
src/rpc/rpc_host_port.h

This patch unifies the code like
```
remove_node(src.node, dst.nodes);
remove_node(src.hp_node, dst.hp_nodes);
```
and
```
remove_node(node, dst.nodes);
remove_node(hp_node, dst.hp_nodes);
```
to
```
REMOVE_IP_AND_HOST_PORT_BY_OBJ(src, node, dst, nodes);
```
and
```
REMOVE_IP_AND_HOST_PORT(node, hp_node, dst, nodes);
```
to simplify code and ensure nothing missed.

refactor(FQDN): Minor refactor on remove_node()

---

.github/actions/rebuild_thirdparty_if_needed/action.yaml

Resolve https://github.com/apache/incubator-pegasus/issues/2219.
Fix workflows that failed as dorny/paths-filter@v2 is not allowed to be used.

ci: bump dorny/paths-filter from v2 to v3.0.2

---

src/client/replication_ddl_client.cpp
src/client/replication_ddl_client.h
src/geo/test/geo_test.cpp
src/shell/command_helper.h
src/shell/command_utils.h
src/shell/commands/detect_hotkey.cpp
src/shell/commands/duplication.cpp
src/shell/commands/table_management.cpp
src/shell/main.cpp
src/test/function_test/base_api/test_copy.cpp
src/test/function_test/base_api/test_scan.cpp
src/test/function_test/recovery/test_recovery.cpp
src/test/function_test/utils/test_util.cpp
src/test/function_test/utils/test_util.h

Support `atomic_idempotent` for `create` and `ls` by:
- Add a flag to the `create` command to decide whether the created table is
`atomic_idempotent` (false by default).
- Add a column `atomic_idempotent` to the result shown by `ls` command.

feat(make_idempotent): support `atomic_idempotent` for `create` and `ls` commands on shell

---

src/shell/commands/node_management.cpp

Add metrics related to the number of replicas as the 2rd part to be shown by
`server_stat` command.

feat(new_metrics): support `server_stat` command showing some important server-level metrics (part 2)

---

src/shell/commands.h
src/shell/commands/table_management.cpp
src/shell/main.cpp

Following commands are supported on shell to operate `atomic_idempotent`,
which decides whether all atomic requests written to a table are idempotent":
- `get_atomic_idempotent` 
- `enable_atomic_idempotent`
- `disable_atomic_idempotent`
All of these commands are based on a table, thus an argument `app_name`
is required.

feat(make_idempotent): support getting/enabling/disabling `atomic_idempotent` on shell

---

idl/rrdb.thrift
src/base/pegasus_key_schema.h
src/server/pegasus_write_service_impl.h
src/server/result_writer.cpp
src/server/rocksdb_wrapper.cpp
src/server/rocksdb_wrapper.h
src/utils/blob.h
src/utils/test/utils.cpp

Implement two APIs in `pegasus_write_service::impl` to make `check_and_set`
requests idempotent:
- implement `make_idempotent()` function to translate a `check_and_set` request
into the single-put request which is naturally idempotent, and process the possible
errors during the translation, e.g. failed to read the check value or did not pass the
check;
- implement `put()` function to apply the single-put request into the RocksDB
instance and make response for `check_and_set`.
Also refactor `validate_check()` function to make the check for `check_and_set`
and `check_and_mutate` conditions more clearer and readable.

feat(make_idempotent): support making `check_and_set` request idempotent in `pegasus_write_service::impl`

---

.github/workflows/lint_and_test_scala-client.yml

Resolve https://github.com/apache/incubator-pegasus/issues/2237.
Install `sbt` with [sdkman](https://get.sdkman.io) before checking format. Also
bump actions/cache from v2 to v3 for Scala workflows.

ci(github): fix that sbt could not be found while checking format for Scala

---

.github/workflows/build-push-env-docker.yml
.github/workflows/lint_and_test_admin-cli.yml
.github/workflows/lint_and_test_collector.yml
.github/workflows/lint_and_test_go-client.yml
.github/workflows/lint_and_test_pegic.yml
.github/workflows/regular-build.yml
.golangci.yml
docker/pegasus-build-env/go/Dockerfile
docker/pegasus-build-env/ubuntu2204/Dockerfile

Resolve https://github.com/apache/incubator-pegasus/issues/2241.
Go workflows run on Ubuntu 20.04 because Go client uses thrift-compiler 0.13.0
to generate code and the thrift-compiler version on Ubuntu 20.04 is 0.13.0. However
Ubuntu 20.04 runner has been retired and removed on 2025-04-15. To solve this
problem, we choose to build thrift 0.13.0 in a image based on Ubuntu 22.04.
Also add Collector to the workflow for regular building.

ci(github): fix Go workflows which failed due to Ubuntu 20.04 retirement

---

src/server/pegasus_write_service.cpp
src/server/pegasus_write_service.h

Implement higher-level APIs `make_idempotent()` and `put()` on
`pegasus_write_service` for `check_and_set` request. Both of them
will Internally call APIs provided by `pegasus_write_service::impl`.
Two metrics are also introduced to measure the duration that make
`incr` and `check_and_set` idempotent.

feat(make_idempotent): support making `check_and_set` request idempotent in `pegasus_write_service`

---

idl/utils.thrift
src/block_service/test/block_service_manager_test.cpp
src/common/consensus.thrift
src/replica/bulk_load/test/replica_bulk_loader_test.cpp
src/replica/mutation.h
src/replica/replica.h
src/replica/replica_chkpt.cpp
src/replica/replica_stub.cpp
src/replica/replica_stub.h
src/replica/test/replica_test.cpp
src/server/pegasus_server_impl.cpp
src/server/pegasus_server_impl.h
src/server/test/CMakeLists.txt
src/server/test/capacity_unit_calculator_test.cpp
src/server/test/hotkey_collector_test.cpp
src/server/test/manual_compact_service_test.cpp
src/server/test/pegasus_compression_options_test.cpp
src/server/test/pegasus_server_impl_test.cpp
src/server/test/pegasus_server_test_base.h
src/server/test/pegasus_server_write_test.cpp
src/server/test/pegasus_write_service_impl_test.cpp
src/server/test/pegasus_write_service_test.cpp
src/server/test/rocksdb_wrapper_test.cpp
src/test_util/test_util.cpp
src/test_util/test_util.h
src/utils/checksum.cpp
src/utils/checksum.h
src/utils/test/CMakeLists.txt
src/utils/test/checksum_test.cpp
src/utils/test_macros.h

https://github.com/apache/incubator-pegasus/issues/2242
When a dup follower requests the latest checkpoint information from the dup
master, the server supports returning the size and checksum of each file under
the checkpoint directory. This allows the client to decide which files to fetch:
- if it is the first time downloading the checkpoint, all files need to be downloaded;
- if it is the second time or later, only files that are missing or partially downloaded
locally need to be fetched.
Additionally, the client is allowed to specify the checksum algorithm to use —
currently, only MD5 is supported.

feat(duplication): support resumable download for checkpoint files during full duplication on the server side

---

idl/rrdb.thrift
src/base/idl_utils.h
src/server/pegasus_write_service_impl.h
src/server/rocksdb_wrapper.cpp
src/server/rocksdb_wrapper.h

Implement two APIs in `pegasus_write_service::impl` to make `check_and_mutate`
requests idempotent.
Unlike `incr` and `check_and_set`, a `check_and_mutate` request may be translated
into multiple `put` and `remove` requests. To conveniently store both in the same
`std::vector`, they are all converted into `update_request` objects, with the `type`
field used to distinguish between them:
- implement `make_idempotent()` function to translate a `check_and_mutate` request
into multiple single-put and single-remove requests which are naturally idempotent,
and process the possible errors during the translation, e.g. failed to read the check
value or did not pass the check;
- implement `put()` function to apply multiple single-put and …

feat(make_idempotent): support making `check_and_mutate` request idempotent in `pegasus_write_service::impl`

---

thirdparty/CMakeLists.txt
thirdparty/fix_absl_build_on_macos_arm64.patch

Fix the build failure on MacOS with M chips, the error is:
```
c++: error: unsupported option '-msse4.1' for target 'arm64-apple-darwin24.4.0'
```
Add the patch from https://github.com/abseil/abseil-cpp/commit/26ee072e14dea17fa8870d47cd7e8b4cc1c95e93

fix: fix build failure on Apple M chips

---

src/shell/sds/sds.c

Hi Development Team,
I identified a potential vulnerability in a clone function sdsMakeRoomFor()
in `src/shell/sds/sds.c` sourced from [redis/redis](https://github.com/redis/redis).
This issue, originally reported in [CVE-2021-41099](https://nvd.nist.gov/vuln/detail/CVE-2021-41099),
was resolved in the repository via this commit https://github.com/redis/redis/commit/c6ad876774f3cc11e32681ea02a2eead00f2c521.
This PR applies the corresponding patch to fix the vulnerability in this codebase.
Please review at your convenience. Thank you!

Fix potential vulnerable cloned function

---

go-client/session/meta_call.go
go-client/session/meta_session.go

Fix https://github.com/apache/incubator-pegasus/issues/2256.
The data race was caused by:
1. The `issueBackupMetas()` function returns without waiting for all subroutines
to complete;
2. Concurrent access (read/write) to the `metas` member (the session list) of the
`metaCall` struct was not properly synchronized with mutual exclusion.

fix(go-client): fix the data race issue caused by concurrent read/write access to the session list of `metaCall`

---

.github/actions/rebuild_thirdparty_if_needed/action.yaml
.github/workflows/lint_and_test_go-client.yml
.github/workflows/lint_and_test_java-client.yml
.github/workflows/lint_and_test_scala-client.yml
.github/workflows/test_nodejs-client.yml
.github/workflows/test_python-client.yml

Resolve https://github.com/apache/incubator-pegasus/issues/2276.
According to the the reply from INFRA team[1] and the doc of infrastructure
actions[2], the actions in allow list must be pinned to a SHA rather than a tag
as of August 1st.
Only the action `rebuild_thirdparty_if_needed`[3] uses `dorny/paths-filter`.
Events are also added to the workflows depending on it so that they could be
triggered once it is changed.
1. https://issues.apache.org/jira/browse/INFRA-27084
2. https://github.com/apache/infrastructure-actions/?tab=readme-ov-file#adding-a-new-action-to-the-allow-list
3. https://github.com/apache/incubator-pegasus/blob/master/.github/actions/rebuild_thirdparty_if_needed/action.yaml#L22

ci(github): pin the action `dorny/paths-filter` to the commit SHA pointing to `v3.0.2`

---

src/aio/test/aio.cpp
src/server/test/pegasus_server_write_test.cpp
src/shell/commands/local_partition_split.cpp

Fix https://github.com/apache/incubator-pegasus/issues/2291.
Variable-length arrays are used somewhere in our codes.  However, as a Clang
extension, currently they are considered as errors while building on macOS.
Therefore, we will replace them with some structures such as `std::vector` or
`std::unique_ptr` to eliminate the compilation errors.

fix(build): replace variable-length arrays with proper structures to fix compilation errors on macOS

---

docker/pegasus-build-env/ubuntu1804/Dockerfile
docker/pegasus-build-env/ubuntu2004/Dockerfile
docker/pegasus-build-env/ubuntu2204/Dockerfile

https://github.com/apache/incubator-pegasus/issues/2292
To support tests that connect to ZooKeeper via SASL, auth modules should be
introduced. Otherwise, those tests would fail due to missing necessary mechanisms.

build(images): install pluggable authentication modules for Cyrus SASL on Ubuntu to provide auth mechanisms required for tests
